# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: client_info.pyc (Python 3.11)

'''Helpers for providing client information.

Client information is used to send information about the calling client,
such as the library and Python version, to API services.
'''
import platform
from typing import Union
from google.api_core import version as api_core_version
_PY_VERSION = platform.python_version()
_GRPC_VERSION: Union[(str, None)] = api_core_version.__version__

try:
    import grpc
    _GRPC_VERSION = grpc.__version__
except ImportError:
    _GRPC_VERSION = None


class ClientInfo(object):
    """Client information used to generate a user-agent for API calls.

    This user-agent information is sent along with API calls to allow the
    receiving service to do analytics on which versions of Python and Google
    libraries are being used.

    Args:
        python_version (str): The Python interpreter version, for example,
            ``'3.9.6'``.
        grpc_version (Optional[str]): The gRPC library version.
        api_core_version (str): The google-api-core library version.
        gapic_version (Optional[str]): The version of gapic-generated client
            library, if the library was generated by gapic.
        client_library_version (Optional[str]): The version of the client
            library, generally used if the client library was not generated
            by gapic or if additional functionality was built on top of
            a gapic client library.
        user_agent (Optional[str]): Prefix to the user agent header. This is
            used to supply information such as application name or partner tool.
            Recommended format: ``application-or-tool-ID/major.minor.version``.
        rest_version (Optional[str]): A string with labeled versions of the
            dependencies used for REST transport.
        protobuf_runtime_version (Optional[str]): The protobuf runtime version.
    """
    
    def __init__(self, python_version, grpc_version, api_core_version, gapic_version, client_library_version, user_agent, rest_version, protobuf_runtime_version = (_PY_VERSION, _GRPC_VERSION, _API_CORE_VERSION, None, None, None, None, None)):
        self.python_version = python_version
        self.grpc_version = grpc_version
        self.api_core_version = api_core_version
        self.gapic_version = gapic_version
        self.client_library_version = client_library_version
        self.user_agent = user_agent
        self.rest_version = rest_version
        self.protobuf_runtime_version = protobuf_runtime_version

    
    def to_user_agent(self):
        '''Returns the user-agent string for this client info.'''
        ua = ''
    # WARNING: Decompyle incomplete
