# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: randomimpl.pyc (Python 3.11)

'''
Implement the random and np.random module functions.
'''
import math
import random
import numpy as np
from llvmlite import ir
from numba.core.cgutils import is_nonelike, is_empty_tuple
from numba.core.extending import intrinsic, overload, register_jitable
from numba.core.imputils import Registry
from numba.core.typing import signature
from numba.core import types, cgutils
from numba.core.errors import NumbaTypeError
from numba.np.random._constants import LONG_MAX
registry = Registry('randomimpl')
lower = registry.lower
int32_t = ir.IntType(32)
int64_t = ir.IntType(64)

def const_int(x):
    return ir.Constant(int32_t, x)

double = ir.DoubleType()
N = 624
N_const = ir.Constant(int32_t, N)
rnd_state_t = ir.LiteralStructType([
    int32_t,
    ir.ArrayType(int32_t, N),
    int32_t,
    double,
    int32_t])
rnd_state_ptr_t = ir.PointerType(rnd_state_t)

def get_state_ptr(context, builder, name):
    '''
    Get a pointer to the given thread-local random state
    (depending on *name*: "py" or "np").
    If the state isn\'t initialized, it is lazily initialized with
    system entropy.
    '''
    pass
# WARNING: Decompyle incomplete


def get_py_state_ptr(context, builder):
    '''
    Get a pointer to the thread-local Python random state.
    '''
    return get_state_ptr(context, builder, 'py')


def get_np_state_ptr(context, builder):
    '''
    Get a pointer to the thread-local Numpy random state.
    '''
    return get_state_ptr(context, builder, 'np')


def get_internal_state_ptr(context, builder):
    '''
    Get a pointer to the thread-local internal random state.
    '''
    return get_state_ptr(context, builder, 'internal')


def get_index_ptr(builder, state_ptr):
    return cgutils.gep_inbounds(builder, state_ptr, 0, 0)


def get_array_ptr(builder, state_ptr):
    return cgutils.gep_inbounds(builder, state_ptr, 0, 1)


def get_has_gauss_ptr(builder, state_ptr):
    return cgutils.gep_inbounds(builder, state_ptr, 0, 2)


def get_gauss_ptr(builder, state_ptr):
    return cgutils.gep_inbounds(builder, state_ptr, 0, 3)


def get_rnd_shuffle(builder):
    '''
    Get the internal function to shuffle the MT taste.
    '''
    fnty = ir.FunctionType(ir.VoidType(), (rnd_state_ptr_t,))
    fn = cgutils.get_or_insert_function(builder.function.module, fnty, 'numba_rnd_shuffle')
    fn.args[0].add_attribute('nocapture')
    return fn


def get_next_int32(context, builder, state_ptr):
    '''
    Get the next int32 generated by the PRNG at *state_ptr*.
    '''
    idxptr = get_index_ptr(builder, state_ptr)
    idx = builder.load(idxptr)
    need_reshuffle = builder.icmp_unsigned('>=', idx, N_const)
    cgutils.if_unlikely(builder, need_reshuffle)
    fn = get_rnd_shuffle(builder)
    builder.call(fn, (state_ptr,))
    builder.store(const_int(0), idxptr)
    None(None, None)


def get_next_double(context, builder, state_ptr):
    '''
    Get the next double generated by the PRNG at *state_ptr*.
    '''
    a = builder.lshr(get_next_int32(context, builder, state_ptr), const_int(5))
    b = builder.lshr(get_next_int32(context, builder, state_ptr), const_int(6))
    a = builder.uitofp(a, double)
    b = builder.uitofp(b, double)
    return builder.fdiv(builder.fadd(b, builder.fmul(a, ir.Constant(double, 6.71089e+07))), ir.Constant(double, 9.0072e+15))


def get_next_int(context, builder, state_ptr, nbits, is_numpy):
    '''
    Get the next integer with width *nbits*.
    '''
    pass
# WARNING: Decompyle incomplete

seed_impl = (lambda a: pass# WARNING: Decompyle incomplete
)()
seed_impl = (lambda seed: if isinstance(seed, types.Integer):
_seed_impl('np'))()

def _seed_impl(state_type):
    pass
# WARNING: Decompyle incomplete

random_impl = (lambda : pass# WARNING: Decompyle incomplete
)()
random_impl0 = (lambda : pass# WARNING: Decompyle incomplete
)()()()()
random_impl1 = (lambda size = (None,): if is_nonelike(size):
(lambda size = (None,): np.random.random())
    if None(size):
        return (lambda size = (None,): np.array(np.random.random()))
    if None(size, types.Integer) or isinstance(size, types.UniTuple) or isinstance(size.dtype, types.Integer):
        
        def _impl(size = (None,)):
            out = np.empty(size)
            out_flat = out.flat
            for idx in range(out.size):
                out_flat[idx] = np.random.random()
                return out

        return _impl
    return None
)()()()()
gauss_impl = (lambda mu, sigma: pass# WARNING: Decompyle incomplete
)()()
np_gauss_impl0 = (lambda : (lambda : np.random.normal(0, 1))
)()()
np_gauss_impl1 = (lambda loc: if isinstance(loc, (types.Float, types.Integer)):
(lambda loc: np.random.normal(loc, 1))
)()
np_gauss_impl2 = (lambda loc, scale: pass# WARNING: Decompyle incomplete
)()
standard_normal_impl1 = (lambda size: if is_nonelike(size):
(lambda size: np.random.standard_normal())
    if None(size):
        return (lambda size: np.array(np.random.standard_normal()))
    if None(size, types.Integer) or isinstance(size, types.UniTuple) or isinstance(size.dtype, types.Integer):
        
        def _impl(size):
            out = np.empty(size)
            out_flat = out.flat
            for idx in range(out.size):
                out_flat[idx] = np.random.standard_normal()
                return out

        return _impl
    return None
)()
np_gauss_impl3 = (lambda loc, scale, size: if isinstance(loc, (types.Float, types.Integer)) and isinstance(scale, (types.Float, types.Integer)) and is_nonelike(size):
(lambda loc, scale, size: np.random.normal(loc, scale))
    if None(loc, (types.Float, types.Integer)) and isinstance(scale, (types.Float, types.Integer)) and is_empty_tuple(size):
        return (lambda loc, scale, size: np.array(np.random.normal(loc, scale)))
    if None(loc, (types.Float, types.Integer)) or isinstance(scale, (types.Float, types.Integer)):
        if isinstance(size, types.Integer) or isinstance(size, types.UniTuple) or isinstance(size.dtype, types.Integer):
            
            def _impl(loc, scale, size):
                out = np.empty(size)
                out_flat = out.flat
                for idx in range(out.size):
                    out_flat[idx] = np.random.normal(loc, scale)
                    return out

            return _impl
        return None
    return None
    return None
)()

def _gauss_pair_impl(_random):
    pass
# WARNING: Decompyle incomplete


def _gauss_impl(state, loc_preprocessor, scale_preprocessor):
    pass
# WARNING: Decompyle incomplete


def _double_preprocessor(value):
    pass
# WARNING: Decompyle incomplete

getrandbits_impl = (lambda k: pass# WARNING: Decompyle incomplete
)()

def _randrange_impl(context, builder, start, stop, step, ty, signed, state):
    pass
# WARNING: Decompyle incomplete

randrange_impl_1 = (lambda start: if isinstance(start, types.Integer):
(lambda start: random.randrange(0, start, 1))
)()
randrange_impl_2 = (lambda start, stop: if isinstance(start, types.Integer) or isinstance(stop, types.Integer):
(lambda start, stop: random.randrange(start, stop, 1))
    return None
)()

def _randrange_preprocessor(bitwidth, ty):
