# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: _migration.pyc (Python 3.11)

import sys
from typing import Any, Callable
from pydantic.warnings import PydanticDeprecatedSince20
from version import version_short
MOVED_IN_V2 = {
    'pydantic.utils:version_info': 'pydantic.version:version_info',
    'pydantic.error_wrappers:ValidationError': 'pydantic:ValidationError',
    'pydantic.utils:to_camel': 'pydantic.alias_generators:to_pascal',
    'pydantic.utils:to_lower_camel': 'pydantic.alias_generators:to_camel',
    'pydantic:PyObject': 'pydantic.types:ImportString',
    'pydantic.types:PyObject': 'pydantic.types:ImportString',
    'pydantic.generics:GenericModel': 'pydantic.BaseModel' }
DEPRECATED_MOVED_IN_V2 = {
    'pydantic.tools:schema_of': 'pydantic.deprecated.tools:schema_of',
    'pydantic.tools:parse_obj_as': 'pydantic.deprecated.tools:parse_obj_as',
    'pydantic.tools:schema_json_of': 'pydantic.deprecated.tools:schema_json_of',
    'pydantic.json:pydantic_encoder': 'pydantic.deprecated.json:pydantic_encoder',
    'pydantic:validate_arguments': 'pydantic.deprecated.decorator:validate_arguments',
    'pydantic.json:custom_pydantic_encoder': 'pydantic.deprecated.json:custom_pydantic_encoder',
    'pydantic.json:timedelta_isoformat': 'pydantic.deprecated.json:timedelta_isoformat',
    'pydantic.decorator:validate_arguments': 'pydantic.deprecated.decorator:validate_arguments',
    'pydantic.class_validators:validator': 'pydantic.deprecated.class_validators:validator',
    'pydantic.class_validators:root_validator': 'pydantic.deprecated.class_validators:root_validator',
    'pydantic.config:BaseConfig': 'pydantic.deprecated.config:BaseConfig',
    'pydantic.config:Extra': 'pydantic.deprecated.config:Extra' }
REDIRECT_TO_V1 = ('deep_update', 'GetterDict', 'lenient_issubclass', 'lenient_isinstance', 'is_valid_field', 'update_not_none', 'import_string', 'Representation', 'ROOT_KEY', 'smart_deepcopy', 'sequence_like')()
REMOVED_IN_V2 = {
    'pydantic:NoneStr',
    'pydantic:Protocol',
    'pydantic:Required',
    'pydantic:StrBytes',
    'pydantic:compiled',
    'pydantic:NoneBytes',
    'pydantic:stricturl',
    'pydantic:JsonWrapper',
    'pydantic:NoneStrBytes',
    'pydantic:parse_raw_as',
    'pydantic.types:NoneStr',
    'pydantic.typing:IntStr',
    'pydantic.typing:SetStr',
    'pydantic:parse_file_as',
    'pydantic.types:StrBytes',
    'pydantic.typing:DictAny',
    'pydantic.typing:ListStr',
    'pydantic.typing:StrPath',
    'pydantic:ConstrainedInt',
    'pydantic:ConstrainedSet',
    'pydantic:ConstrainedStr',
    'pydantic:validate_model',
    'pydantic.errors:SetError',
    'pydantic.errors:StrError',
    'pydantic.errors:UrlError',
    'pydantic.types:NoneBytes',
    'pydantic.typing:NoneType',
    'pydantic.typing:ReprArgs',
    'pydantic.typing:get_args',
    'pydantic.typing:is_union',
    'pydantic.utils:get_model',
    'pydantic.utils:path_type',
    'pydantic:ConstrainedDate',
    'pydantic:ConstrainedList',
    'pydantic.errors:BoolError',
    'pydantic.errors:DateError',
    'pydantic.errors:DictError',
    'pydantic.errors:EnumError',
    'pydantic.errors:JsonError',
    'pydantic.errors:ListError',
    'pydantic.errors:PathError',
    'pydantic.errors:TimeError',
    'pydantic.errors:UUIDError',
    'pydantic.utils:ValueItems',
    'pydantic.utils:in_ipython',
    'pydantic:ConstrainedBytes',
    'pydantic:ConstrainedFloat',
    'pydantic.config:get_config',
    'pydantic.errors:BytesError',
    'pydantic.errors:ClassError',
    'pydantic.errors:ColorError',
    'pydantic.errors:EmailError',
    'pydantic.errors:ExtraError',
    'pydantic.errors:FloatError',
    'pydantic.errors:TupleError',
    'pydantic.types:JsonWrapper',
    'pydantic.typing:DictStrAny',
    'pydantic.typing:get_origin',
    'pydantic.utils:PyObjectStr',
    'pydantic.errors:ConfigError',
    'pydantic.networks:stricturl',
    'pydantic.tools:parse_raw_as',
    'pydantic.types:NoneStrBytes',
    'pydantic.typing:AnyCallable',
    'pydantic.typing:is_classvar',
    'pydantic.typing:is_finalvar',
    'pydantic.typing:is_new_type',
    'pydantic.typing:typing_base',
    'pydantic:ConstrainedDecimal',
    'pydantic.errors:DecimalError',
    'pydantic.errors:IntEnumError',
    'pydantic.errors:IntegerError',
    'pydantic.errors:MissingError',
    'pydantic.errors:NotNoneError',
    'pydantic.errors:PatternError',
    'pydantic.errors:UrlHostError',
    'pydantic.errors:UrlPortError',
    'pydantic.main:validate_model',
    'pydantic.tools:parse_file_as',
    'pydantic.typing:is_none_type',
    'pydantic.typing:is_typeddict',
    'pydantic.errors:CallableError',
    'pydantic.errors:DateTimeError',
    'pydantic.errors:DurationError',
    'pydantic.errors:HashableError',
    'pydantic.errors:JsonTypeError',
    'pydantic.errors:NotDigitError',
    'pydantic.errors:PyObjectError',
    'pydantic.errors:SequenceError',
    'pydantic.errors:StrRegexError',
    'pydantic.errors:SubclassError',
    'pydantic.errors:UrlExtraError',
    'pydantic.types:ConstrainedInt',
    'pydantic.types:ConstrainedSet',
    'pydantic.types:ConstrainedStr',
    'pydantic.typing:DictIntStrAny',
    'pydantic.typing:WithArgsTypes',
    'pydantic.typing:get_sub_types',
    'pydantic.typing:is_namedtuple',
    'pydantic.utils:ClassAttribute',
    'pydantic:ConstrainedFrozenSet',
    'pydantic.config:inherit_config',
    'pydantic.config:prepare_config',
    'pydantic.errors:FrozenSetError',
    'pydantic.errors:UrlSchemeError',
    'pydantic.types:ConstrainedDate',
    'pydantic.types:ConstrainedList',
    'pydantic.typing:AnyClassMethod',
    'pydantic.typing:TupleGenerator',
    'pydantic.errors:EnumMemberError',
    'pydantic.errors:InvalidByteSize',
    'pydantic.errors:StrictBoolError',
    'pydantic.errors:UrlHostTldError',
    'pydantic.types:ConstrainedBytes',
    'pydantic.types:ConstrainedFloat',
    'pydantic.typing:display_as_type',
    'pydantic.typing:is_literal_type',
    'pydantic.errors:IPv4AddressError',
    'pydantic.errors:IPv4NetworkError',
    'pydantic.errors:IPv6AddressError',
    'pydantic.errors:IPv6NetworkError',
    'pydantic.errors:NumberNotGeError',
    'pydantic.errors:NumberNotGtError',
    'pydantic.errors:NumberNotLeError',
    'pydantic.errors:NumberNotLtError',
    'pydantic.errors:TupleLengthError',
    'pydantic.errors:UUIDVersionError',
    'pydantic.errors:UrlUserInfoError',
    'pydantic.typing:MappingIntStrAny',
    'pydantic.typing:NoArgAnyCallable',
    'pydantic.typing:is_callable_type',
    'pydantic.utils:DUNDER_ATTRIBUTES',
    'pydantic.errors:PathNotAFileError',
    'pydantic.errors:PydanticTypeError',
    'pydantic.errors:SetMaxLengthError',
    'pydantic.errors:SetMinLengthError',
    'pydantic.types:ConstrainedDecimal',
    'pydantic.typing:AbstractSetIntStr',
    'pydantic.typing:CallableGenerator',
    'pydantic.datetime_parse:parse_date',
    'pydantic.datetime_parse:parse_time',
    'pydantic.errors:ArbitraryTypeError',
    'pydantic.errors:DataclassTypeError',
    'pydantic.errors:IPv4InterfaceError',
    'pydantic.errors:IPv6InterfaceError',
    'pydantic.errors:IPvAnyAddressError',
    'pydantic.errors:IPvAnyNetworkError',
    'pydantic.errors:ListMaxLengthError',
    'pydantic.errors:ListMinLengthError',
    'pydantic.errors:NoneIsAllowedError',
    'pydantic.errors:PathNotExistsError',
    'pydantic.errors:PydanticValueError',
    'pydantic.errors:WrongConstantError',
    'pydantic.typing:all_literal_values',
    'pydantic.typing:get_all_type_hints',
    'pydantic.typing:new_type_supertype',
    'pydantic.utils:almost_equal_floats',
    'pydantic.utils:is_valid_identifier',
    'pydantic.utils:validate_field_name',
    'pydantic.dataclasses:set_validation',
    'pydantic.errors:InvalidByteSizeUnit',
    'pydantic.errors:LuhnValidationError',
    'pydantic.types:ConstrainedFrozenSet',
    'pydantic.typing:evaluate_forwardref',
    'pydantic.typing:resolve_annotations',
    'pydantic.error_wrappers:ErrorWrapper',
    'pydantic.errors:AnyStrMaxLengthError',
    'pydantic.errors:AnyStrMinLengthError',
    'pydantic.errors:IPvAnyInterfaceError',
    'pydantic.errors:InvalidDiscriminator',
    'pydantic.errors:ListUniqueItemsError',
    'pydantic.errors:MissingDiscriminator',
    'pydantic.typing:is_typeddict_special',
    'pydantic:create_model_from_typeddict',
    'pydantic.errors:DateNotInThePastError',
    'pydantic.errors:DecimalMaxDigitsError',
    'pydantic.errors:DecimalMaxPlacesError',
    'pydantic.errors:InvalidLengthForBrand',
    'pydantic.errors:NoneIsNotAllowedError',
    'pydantic:create_model_from_namedtuple',
    'pydantic.datetime_parse:parse_datetime',
    'pydantic.datetime_parse:parse_duration',
    'pydantic.errors:NumberNotMultipleError',
    'pydantic.errors:PathNotADirectoryError',
    'pydantic.errors:DateNotInTheFutureError',
    'pydantic.errors:DecimalIsNotFiniteError',
    'pydantic.errors:DecimalWholeDigitsError',
    'pydantic.errors:FrozenSetMaxLengthError',
    'pydantic.errors:FrozenSetMinLengthError',
    'pydantic.errors:UrlSchemePermittedError',
    'pydantic.typing:update_field_forward_refs',
    'pydantic.typing:update_model_forward_refs',
    'pydantic.dataclasses:make_dataclass_validator',
    'pydantic.utils:get_unique_discriminator_alias',
    'pydantic.utils:get_discriminator_alias_and_values',
    'pydantic.dataclasses:create_pydantic_model_from_dataclass'}

def getattr_migration(module = None):
    '''Implement PEP 562 for objects that were either moved or removed on the migration
    to V2.

    Args:
        module: The module name.

    Returns:
        A callable that will raise an error if the object is not found.
    '''
    pass
# WARNING: Decompyle incomplete
