# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: nodes.pyc (Python 3.11)

'''AST nodes generated by the parser for the compiler. Also provides
some node tree helper functions used by the parser and compiler in order
to normalize nodes.
'''
import inspect
import operator
import typing as t
from collections import deque
from markupsafe import Markup
from utils import _PassArg
if t.TYPE_CHECKING:
    import typing_extensions as te
    from environment import Environment
_NodeBound = t.TypeVar('_NodeBound', bound = 'Node')
_binop_to_func: t.Dict[(str, t.Callable[([
    t.Any,
    t.Any], t.Any)])] = {
    '*': operator.mul,
    '/': operator.truediv,
    '//': operator.floordiv,
    '**': operator.pow,
    '%': operator.mod,
    '+': operator.add,
    '-': operator.sub }
_uaop_to_func: t.Dict[(str, t.Callable[([
    t.Any], t.Any)])] = {
    'not': operator.not_,
    '+': operator.pos,
    '-': operator.neg }
_cmpop_to_func: t.Dict[(str, t.Callable[([
    t.Any,
    t.Any], t.Any)])] = {
    'eq': operator.eq,
    'ne': operator.ne,
    'gt': operator.gt,
    'gteq': operator.ge,
    'lt': operator.lt,
    'lteq': operator.le,
    'in': (lambda a, b: a in b),
    'notin': (lambda a, b: a not in b) }

class Impossible(Exception):
    '''Raised if the node could not perform a requested action.'''
    pass


class NodeType(type):
    '''A metaclass for nodes that handles the field and attribute
    inheritance.  fields and attributes from the parent class are
    automatically forwarded to the child.'''
    
    def __new__(mcs, name, bases, d):
        pass
    # WARNING: Decompyle incomplete



class EvalContext:
    '''Holds evaluation time information.  Custom attributes can be attached
    to it in extensions.
    '''
    
    def __init__(self = None, environment = None, template_name = None):
        self.environment = environment
        if callable(environment.autoescape):
            self.autoescape = environment.autoescape(template_name)
        else:
            self.autoescape = environment.autoescape
        self.volatile = False

    
    def save(self = None):
        return self.__dict__.copy()

    
    def revert(self = None, old = None):
        self.__dict__.clear()
        self.__dict__.update(old)



def get_eval_context(node = None, ctx = None):
    pass
# WARNING: Decompyle incomplete


def Node():
    '''Node'''
    __doc__ = 'Baseclass for all Jinja nodes.  There are a number of nodes available\n    of different types.  There are four major types:\n\n    -   :class:`Stmt`: statements\n    -   :class:`Expr`: expressions\n    -   :class:`Helper`: helper nodes\n    -   :class:`Template`: the outermost wrapper node\n\n    All nodes have fields and attributes.  Fields may be other nodes, lists,\n    or arbitrary values.  Fields are passed to the constructor as regular\n    positional arguments, attributes as keyword arguments.  Each node has\n    two attributes: `lineno` (the line number of the node) and `environment`.\n    The `environment` attribute is set at the end of the parsing process for\n    all nodes automatically.\n    '
    fields: t.Tuple[(str, ...)] = ()
    attributes: t.Tuple[(str, ...)] = ('lineno', 'environment')
    environment: t.Optional['Environment'] = True
    
    def __init__(self = None, *fields, **attributes):
        if self.abstract:
            raise TypeError('abstract nodes are not instantiable')
        if fields:
            if len(fields) != len(self.fields):
                if not self.fields:
                    raise TypeError(f'''{type(self).__name__!r} takes 0 arguments''')
                raise TypeError(f'''{type(self).__name__!r} takes 0 or {len(self.fields)} argument{'s' if len(self.fields) != 1 else ''}''')
            for name, arg in zip(self.fields, fields):
                setattr(self, name, arg)
                for attr in self.attributes:
                    setattr(self, attr, attributes.pop(attr, None))
                    if attributes:
                        raise TypeError(f'''unknown attribute {next(iter(attributes))!r}''')
                    return None

    
    def iter_fields(self = None, exclude = None, only = None):
        """This method iterates over all fields that are defined and yields
        ``(key, value)`` tuples.  Per default all fields are returned, but
        it's possible to limit that to some fields by providing the `only`
        parameter or to exclude some using the `exclude` parameter.  Both
        should be sets or tuples of field names.
        """
        pass
    # WARNING: Decompyle incomplete

    
    def iter_child_nodes(self = None, exclude = None, only = None):
        '''Iterates over all direct child nodes of the node.  This iterates
        over all fields and yields the values of they are nodes.  If the value
        of a field is a list all the nodes in that list are returned.
        '''
        pass
    # WARNING: Decompyle incomplete

    
    def find(self = None, node_type = None):
        '''Find the first node of a given type.  If no such node exists the
        return value is `None`.
        '''
        for result in self.find_all(node_type):
            
            return None, result
            return None

    
    def find_all(self = None, node_type = None):
        '''Find all the nodes of a given type.  If the type is a tuple,
        the check is performed for any of the tuple items.
        '''
        pass
    # WARNING: Decompyle incomplete

    
    def set_ctx(self = None, ctx = None):
        """Reset the context of a node and all child nodes.  Per default the
        parser will all generate nodes that have a 'load' context as it's the
        most common one.  This method is used in the parser to set assignment
        targets and other nodes to a store context.
        """
        todo = deque([
            self])
    # WARNING: Decompyle incomplete

    
    def set_lineno(self = None, lineno = None, override = None):
        '''Set the line numbers of the node and children.'''
        todo = deque([
            self])
    # WARNING: Decompyle incomplete

    
    def set_environment(self = None, environment = None):
        '''Set the environment for all nodes.'''
        todo = deque([
            self])
    # WARNING: Decompyle incomplete

    
    def __eq__(self = None, other = None):
        if type(self) is not type(other):
            return NotImplemented
        return None(self.iter_fields()) == tuple(other.iter_fields())

    __hash__ = object.__hash__
    
    def __repr__(self = None):
        pass
    # WARNING: Decompyle incomplete

    
    def dump(self = None):
        pass
    # WARNING: Decompyle incomplete


Node = <NODE:27>(Node, 'Node', metaclass = NodeType)

class Stmt(Node):
    '''Base node for all statements.'''
    abstract = True


class Helper(Node):
    '''Nodes that exist in a specific context only.'''
    abstract = True


class Template(Node):
    '''Node that represents a template.  This must be the outermost node that
    is passed to the compiler.
    '''
    body: t.List[Node] = ('body',)


class Output(Stmt):
    '''A node that holds multiple expressions which are then printed out.
    This is used both for the `print` statement and the regular template data.
    '''
    nodes: t.List['Expr'] = ('nodes',)


class Extends(Stmt):
    '''Represents an extends statement.'''
    template: 'Expr' = ('template',)


class For(Stmt):
    '''The for loop.  `target` is the target for the iteration (usually a
    :class:`Name` or :class:`Tuple`), `iter` the iterable.  `body` is a list
    of nodes that are used as loop-body, and `else_` a list of nodes for the
    `else` block.  If no else node exists it has to be an empty list.

    For filtered nodes an expression can be stored as `test`, otherwise `None`.
    '''
    recursive: bool = ('target', 'iter', 'body', 'else_', 'test', 'recursive')


class If(Stmt):
    '''If `test` is true, `body` is rendered, else `else_`.'''
    else_: t.List[Node] = ('test', 'body', 'elif_', 'else_')


class Macro(Stmt):
    '''A macro definition.  `name` is the name of the macro, `args` a list of
    arguments and `defaults` a list of defaults if there are any.  `body` is
    a list of nodes for the macro body.
    '''
    body: t.List[Node] = ('name', 'args', 'defaults', 'body')


class CallBlock(Stmt):
    '''Like a macro without a name but a call instead.  `call` is called with
    the unnamed macro as `caller` argument this node holds.
    '''
    body: t.List[Node] = ('call', 'args', 'defaults', 'body')


class FilterBlock(Stmt):
    '''Node for filter sections.'''
    filter: 'Filter' = ('body', 'filter')


class With(Stmt):
    '''Specific node for with statements.  In older versions of Jinja the
    with statement was implemented on the base of the `Scope` node instead.

    .. versionadded:: 2.9.3
    '''
    body: t.List[Node] = ('targets', 'values', 'body')


class Block(Stmt):
    '''A node that represents a block.

    .. versionchanged:: 3.0.0
        the `required` field was added.
    '''
    required: bool = ('name', 'body', 'scoped', 'required')


class Include(Stmt):
    '''A node that represents the include tag.'''
    ignore_missing: bool = ('template', 'with_context', 'ignore_missing')


class Import(Stmt):
    '''A node that represents the import tag.'''
    with_context: bool = ('template', 'target', 'with_context')


class FromImport(Stmt):
    """A node that represents the from import tag.  It's important to not
    pass unsafe names to the name attribute.  The compiler translates the
    attribute lookups directly into getattr calls and does *not* use the
    subscript callback of the interface.  As exported variables may not
    start with double underscores (which the parser asserts) this is not a
    problem for regular Jinja code, but if this node is used in an extension
    extra care must be taken.

    The list of names may contain tuples if aliases are wanted.
    """
    with_context: bool = ('template', 'names', 'with_context')


class ExprStmt(Stmt):
    '''A statement that evaluates an expression and discards the result.'''
    node: Node = ('node',)


class Assign(Stmt):
    '''Assigns an expression to a target.'''
    node: Node = ('target', 'node')


class AssignBlock(Stmt):
    '''Assigns a block to a target.'''
    body: t.List[Node] = ('target', 'filter', 'body')


class Expr(Node):
    '''Baseclass for all expressions.'''
    abstract = True
    
    def as_const(self = None, eval_ctx = None):
        '''Return the value of the expression as constant or raise
        :exc:`Impossible` if this was not possible.

        An :class:`EvalContext` can be provided, if none is given
        a default context is created which requires the nodes to have
        an attached environment.

        .. versionchanged:: 2.4
           the `eval_ctx` parameter was added.
        '''
        raise Impossible()

    
    def can_assign(self = None):
        """Check if it's possible to assign something to this node."""
        return False



class BinExpr(Expr):
    '''Baseclass for all binary expressions.'''
    operator: str = ('left', 'right')
    abstract = True
    
    def as_const(self = None, eval_ctx = None):
        eval_ctx = get_eval_context(self, eval_ctx)
        if eval_ctx.environment.sandboxed and self.operator in eval_ctx.environment.intercepted_binops:
            raise Impossible()
        f = _binop_to_func[self.operator]
        
        try:
            return f(self.left.as_const(eval_ctx), self.right.as_const(eval_ctx))
        except Exception:
            e = None
            raise Impossible(), e
            e = None
            del e




class UnaryExpr(Expr):
    '''Baseclass for all unary expressions.'''
    operator: str = ('node',)
    abstract = True
    
    def as_const(self = None, eval_ctx = None):
        eval_ctx = get_eval_context(self, eval_ctx)
        if eval_ctx.environment.sandboxed and self.operator in eval_ctx.environment.intercepted_unops:
            raise Impossible()
        f = _uaop_to_func[self.operator]
        
        try:
            return f(self.node.as_const(eval_ctx))
        except Exception:
            e = None
            raise Impossible(), e
            e = None
            del e




class Name(Expr):
    '''Looks up a name or stores a value in a name.
    The `ctx` of the node can be one of the following values:

    -   `store`: store a value in the name
    -   `load`: load that name
    -   `param`: like `store` but if the name was defined as function parameter.
    '''
    ctx: str = ('name', 'ctx')
    
    def can_assign(self = None):
        return self.name not in frozenset({'None', 'True', 'none', 'true', 'False', 'false'})



class NSRef(Expr):
    '''Reference to a namespace value assignment'''
    attr: str = ('name', 'attr')
    
    def can_assign(self = None):
        return True



class Literal(Expr):
    '''Baseclass for literals.'''
    abstract = True


class Const(Literal):
    '''All constant values.  The parser will return this node for simple
    constants such as ``42`` or ``"foo"`` but it can be used to store more
    complex values such as lists too.  Only constants with a safe
    representation (objects where ``eval(repr(x)) == x`` is true).
    '''
    value: t.Any = ('value',)
    
    def as_const(self = None, eval_ctx = None):
        return self.value

    from_untrusted = (lambda cls = None, value = None, lineno = classmethod, environment = (None, None): has_safe_repr = has_safe_reprimport compilerif not has_safe_repr(value):
raise Impossible()cls(value, lineno = lineno, environment = environment))()


class TemplateData(Literal):
    '''A constant template string.'''
    data: str = ('data',)
    
    def as_const(self = None, eval_ctx = None):
        eval_ctx = get_eval_context(self, eval_ctx)
        if eval_ctx.volatile:
            raise Impossible()
        if eval_ctx.autoescape:
            return Markup(self.data)
        return None.data



class Tuple(Literal):
    '''For loop unpacking and some other things like multiple arguments
    for subscripts.  Like for :class:`Name` `ctx` specifies if the tuple
    is used for loading the names or storing.
    '''
    ctx: str = ('items', 'ctx')
    
    def as_const(self = None, eval_ctx = None):
        pass
    # WARNING: Decompyle incomplete

    
    def can_assign(self = None):
        for item in self.items:
            if not item.can_assign():
                return False
            return True



class List(Literal):
    '''Any list literal such as ``[1, 2, 3]``'''
    items: t.List[Expr] = ('items',)
    
    def as_const(self = None, eval_ctx = None):
        pass
    # WARNING: Decompyle incomplete



class Dict(Literal):
    '''Any dict literal such as ``{1: 2, 3: 4}``.  The items must be a list of
    :class:`Pair` nodes.
    '''
    items: t.List['Pair'] = ('items',)
    
    def as_const(self = None, eval_ctx = None):
        pass
    # WARNING: Decompyle incomplete



class Pair(Helper):
    '''A key, value pair for dicts.'''
    value: Expr = ('key', 'value')
    
    def as_const(self = None, eval_ctx = None):
        eval_ctx = get_eval_context(self, eval_ctx)
        return (self.key.as_const(eval_ctx), self.value.as_const(eval_ctx))



class Keyword(Helper):
    '''A key, value pair for keyword arguments where key is a string.'''
    value: Expr = ('key', 'value')
    
    def as_const(self = None, eval_ctx = None):
        eval_ctx = get_eval_context(self, eval_ctx)
        return (self.key, self.value.as_const(eval_ctx))



class CondExpr(Expr):
    '''A conditional expression (inline if expression).  (``{{
    foo if bar else baz }}``)
    '''
    expr2: t.Optional[Expr] = ('test', 'expr1', 'expr2')
    
    def as_const(self = None, eval_ctx = None):
        eval_ctx = get_eval_context(self, eval_ctx)
        if self.test.as_const(eval_ctx):
            return self.expr1.as_const(eval_ctx)
    # WARNING: Decompyle incomplete



def args_as_const(node = None, eval_ctx = None):
    pass
# WARNING: Decompyle incomplete


class _FilterTestCommon(Expr):
    dyn_kwargs: t.Optional[Expr] = ('node', 'name', 'args', 'kwargs', 'dyn_args', 'dyn_kwargs')
    abstract = True
    _is_filter = True
    
    def as_const(self = None, eval_ctx = None):
        eval_ctx = get_eval_context(self, eval_ctx)
        if eval_ctx.volatile:
            raise Impossible()
        if self._is_filter:
            env_map = eval_ctx.environment.filters
        else:
            env_map = eval_ctx.environment.tests
        func = env_map.get(self.name)
        pass_arg = _PassArg.from_obj(func)
    # WARNING: Decompyle incomplete



class Filter(_FilterTestCommon):
    pass
# WARNING: Decompyle incomplete


class Test(_FilterTestCommon):
    '''Apply a test to an expression. ``name`` is the name of the test,
    the other field are the same as :class:`Call`.

    .. versionchanged:: 3.0
        ``as_const`` shares the same logic for filters and tests. Tests
        check for volatile, async, and ``@pass_context`` etc.
        decorators.
    '''
    _is_filter = False


class Call(Expr):
    '''Calls an expression.  `args` is a list of arguments, `kwargs` a list
    of keyword arguments (list of :class:`Keyword` nodes), and `dyn_args`
    and `dyn_kwargs` has to be either `None` or a node that is used as
    node for dynamic positional (``*args``) or keyword (``**kwargs``)
    arguments.
    '''
    dyn_kwargs: t.Optional[Expr] = ('node', 'args', 'kwargs', 'dyn_args', 'dyn_kwargs')


class Getitem(Expr):
    '''Get an attribute or item from an expression and prefer the item.'''
    ctx: str = ('node', 'arg', 'ctx')
    
    def as_const(self = None, eval_ctx = None):
        if self.ctx != 'load':
            raise Impossible()
        eval_ctx = get_eval_context(self, eval_ctx)
        
        try:
            return eval_ctx.environment.getitem(self.node.as_const(eval_ctx), self.arg.as_const(eval_ctx))
        except Exception:
            e = None
            raise Impossible(), e
            e = None
            del e




class Getattr(Expr):
    '''Get an attribute or item from an expression that is a ascii-only
    bytestring and prefer the attribute.
    '''
    ctx: str = ('node', 'attr', 'ctx')
    
    def as_const(self = None, eval_ctx = None):
        if self.ctx != 'load':
            raise Impossible()
        eval_ctx = get_eval_context(self, eval_ctx)
        
        try:
            return eval_ctx.environment.getattr(self.node.as_const(eval_ctx), self.attr)
        except Exception:
            e = None
            raise Impossible(), e
            e = None
            del e




class Slice(Expr):
    '''Represents a slice object.  This must only be used as argument for
    :class:`Subscript`.
    '''
    step: t.Optional[Expr] = ('start', 'stop', 'step')
    
    def as_const(self = None, eval_ctx = None):
        pass
    # WARNING: Decompyle incomplete



class Concat(Expr):
    '''Concatenates the list of expressions provided after converting
    them to strings.
    '''
    nodes: t.List[Expr] = ('nodes',)
    
    def as_const(self = None, eval_ctx = None):
        pass
    # WARNING: Decompyle incomplete



class Compare(Expr):
    '''Compares an expression with some other expressions.  `ops` must be a
    list of :class:`Operand`\\s.
    '''
    ops: t.List['Operand'] = ('expr', 'ops')
    
    def as_const(self = None, eval_ctx = None):
        eval_ctx = get_eval_context(self, eval_ctx)
        result = self.expr.as_const(eval_ctx)
        value = self.expr.as_const(eval_ctx)
        
        try:
            for op in self.ops:
                new_value = op.expr.as_const(eval_ctx)
                result = _cmpop_to_func[op.op](value, new_value)
                if not result:
                    return False
                value = None
        except Exception:
            e = None
            raise Impossible(), e
            e = None
            del e
            return result




class Operand(Helper):
    '''Holds an operator and an expression.'''
    expr: Expr = ('op', 'expr')


class Mul(BinExpr):
    '''Multiplies the left with the right node.'''
    operator = '*'


class Div(BinExpr):
    '''Divides the left by the right node.'''
    operator = '/'


class FloorDiv(BinExpr):
    '''Divides the left by the right node and converts the
    result into an integer by truncating.
    '''
    operator = '//'


class Add(BinExpr):
    '''Add the left to the right node.'''
    operator = '+'


class Sub(BinExpr):
    '''Subtract the right from the left node.'''
    operator = '-'


class Mod(BinExpr):
    '''Left modulo right.'''
    operator = '%'


class Pow(BinExpr):
    '''Left to the power of right.'''
    operator = '**'


class And(BinExpr):
    '''Short circuited AND.'''
    operator = 'and'
    
    def as_const(self = None, eval_ctx = None):
