# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: mock.pyc (Python 3.11)

from __future__ import annotations
from operator import attrgetter
import typing
from typing import Any
from typing import Callable
from typing import cast
from typing import Optional
from typing import Type
from typing import Union
from  import url as _url
from  import util
if typing.TYPE_CHECKING:
    from base import Engine
    from interfaces import _CoreAnyExecuteParams
    from interfaces import CoreExecuteOptionsParameter
    from interfaces import Dialect
    from url import URL
    from sql.base import Executable
    from sql.ddl import InvokeDDLBase
    from sql.schema import HasSchemaAttr
    from sql.visitors import Visitable

class MockConnection:
    
    def __init__(self = None, dialect = None, execute = None):
        self._dialect = dialect
        self._execute_impl = execute

    engine: 'Engine' = cast(Any, property((lambda s: s)))
    dialect: 'Dialect' = cast(Any, property(attrgetter('_dialect')))
    name: 'str' = cast(Any, property((lambda s: s._dialect.name)))
    
    def connect(self = None, **kwargs):
        return self

    
    def schema_for_object(self = None, obj = None):
        return obj.schema

    
    def execution_options(self = None, **kw):
        return self

    
    def _run_ddl_visitor(self = None, visitorcallable = None, element = None, **kwargs):
        kwargs['checkfirst'] = False
    # WARNING: Decompyle incomplete

    
    def execute(self = None, obj = None, parameters = None, execution_options = (None, None)):
        return self._execute_impl(obj, parameters)



def create_mock_engine(url = None, executor = None, **kw):
    '''Create a "mock" engine used for echoing DDL.

    This is a utility function used for debugging or storing the output of DDL
    sequences as generated by :meth:`_schema.MetaData.create_all`
    and related methods.

    The function accepts a URL which is used only to determine the kind of
    dialect to be used, as well as an "executor" callable function which
    will receive a SQL expression object and parameters, which can then be
    echoed or otherwise printed.   The executor\'s return value is not handled,
    nor does the engine allow regular string statements to be invoked, and
    is therefore only useful for DDL that is sent to the database without
    receiving any results.

    E.g.::

        from sqlalchemy import create_mock_engine


        def dump(sql, *multiparams, **params):
            print(sql.compile(dialect=engine.dialect))


        engine = create_mock_engine("postgresql+psycopg2://", dump)
        metadata.create_all(engine, checkfirst=False)

    :param url: A string URL which typically needs to contain only the
     database backend name.

    :param executor: a callable which receives the arguments ``sql``,
     ``*multiparams`` and ``**params``.  The ``sql`` parameter is typically
     an instance of :class:`.ExecutableDDLElement`, which can then be compiled
     into a string using :meth:`.ExecutableDDLElement.compile`.

    .. versionadded:: 1.4 - the :func:`.create_mock_engine` function replaces
       the previous "mock" engine strategy used with
       :func:`_sa.create_engine`.

    .. seealso::

        :ref:`faq_ddl_as_string`

    '''
    u = _url.make_url(url)
    dialect_cls = u.get_dialect()
    dialect_args = { }
# WARNING: Decompyle incomplete
