# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: image.pyc (Python 3.11)

from typing import Optional
from _models import BaseModel
__all__ = [
    'Image']

class Image(BaseModel):
    '''Represents the content or the URL of an image generated by the OpenAI API.'''
    b64_json: Optional[str] = None
    revised_prompt: Optional[str] = None
    url: Optional[str] = None
