# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: __init__.pyc (Python 3.11)

"""
Perceptual image hashing library

Example:

>>> from PIL import Image
>>> import imagehash
>>> hash = imagehash.average_hash(Image.open('test.png'))
>>> print(hash)
d879f8f89b1bbf
>>> otherhash = imagehash.average_hash(Image.open('other.bmp'))
>>> print(otherhash)
ffff3720200ffff
>>> print(hash == otherhash)
False
>>> print(hash - otherhash)
36
>>> for r in range(1, 30, 5):
...\trothash = imagehash.average_hash(Image.open('test.png').rotate(r))
...\tprint('Rotation by %d: %d Hamming difference' % (r, hash - rothash))
...
Rotation by 1: 2 Hamming difference
Rotation by 6: 11 Hamming difference
Rotation by 11: 13 Hamming difference
Rotation by 16: 17 Hamming difference
Rotation by 21: 19 Hamming difference
Rotation by 26: 21 Hamming difference
>>>
"""
from __future__ import absolute_import, division, print_function
import sys
import numpy
from PIL import Image, ImageFilter

try:
    ANTIALIAS = Image.Resampling.LANCZOS
except AttributeError:
    ANTIALIAS = Image.ANTIALIAS

__version__ = '4.3.1'

def _binary_array_to_hex(arr):
    '''
\tinternal function to make a hex string out of a binary array.
\t'''
    bit_string = (lambda .0: pass# WARNING: Decompyle incomplete
)(1 * arr.flatten()())
    width = int(numpy.ceil(len(bit_string) / 4))
    return '{:0>{width}x}'.format(int(bit_string, 2), width = width)


class ImageHash:
    '''
\tHash encapsulation. Can be used for dictionary keys and comparisons.
\t'''
    
    def __init__(self, binary_array):
        self.hash = binary_array

    
    def __str__(self):
        return _binary_array_to_hex(self.hash.flatten())

    
    def __repr__(self):
        return repr(self.hash)

    
    def __sub__(self, other):
        pass
    # WARNING: Decompyle incomplete

    
    def __eq__(self, other):
        pass
    # WARNING: Decompyle incomplete

    
    def __ne__(self, other):
        pass
    # WARNING: Decompyle incomplete

    
    def __hash__(self):
        return (lambda .0: pass# WARNING: Decompyle incomplete
)(enumerate(self.hash.flatten())())

    
    def __len__(self):
        return self.hash.size



try:
    from typing import Literal
    WhashMode = Literal[('haar', 'db4')]
except ImportError:
    WhashMode = str


try:
    import numpy.typing as numpy
    NDArray = numpy.typing.NDArray[numpy.bool_]
except (AttributeError, ImportError):
    NDArray = list

if sys.version_info >= (3, 3):
    
    try:
        MeanFunc = Callable[([
            NDArray], float)]
        HashFunc = Callable[([
            Image.Image], ImageHash)]
    except TypeError:
        MeanFunc = Callable
        HashFunc = Callable

    
    def hex_to_hash(hexstr):
        '''
\tConvert a stored hash (hex, as retrieved from str(Imagehash))
\tback to a Imagehash object.

\tNotes:
\t1. This algorithm assumes all hashes are either
\t\t\tbidimensional arrays with dimensions hash_size * hash_size,
\t\t\tor onedimensional arrays with dimensions binbits * 14.
\t2. This algorithm does not work for hash_size < 2.
\t'''
        pass
    # WARNING: Decompyle incomplete

    
    def hex_to_flathash(hexstr, hashsize):
        hash_size = int(len(hexstr) * 4 / hashsize)
        binary_array = '{:0>{width}b}'.format(int(hexstr, 16), width = hash_size * hashsize)
        hash_array = (lambda .0: [ bool(int(d)) for d in .0 ])([
            binary_array()])[-hash_size * hashsize:]
        return ImageHash(hash_array)

    
    def hex_to_multihash(hexstr):
        '''
\tConvert a stored multihash (hex, as retrieved from str(ImageMultiHash))
\tback to an ImageMultiHash object.

\tThis function is based on hex_to_hash so the same caveats apply. Namely:

\t1. This algorithm assumes all hashes are either
\t\t\tbidimensional arrays with dimensions hash_size * hash_size,
\t\t\tor onedimensional arrays with dimensions binbits * 14.
\t2. This algorithm does not work for hash_size < 2.
\t'''
        split = hexstr.split(',')
        hashes = split()
        return ImageMultiHash(hashes)

    
    def old_hex_to_hash(hexstr, hash_size = (8,)):
        '''
\tConvert a stored hash (hex, as retrieved from str(Imagehash))
\tback to a Imagehash object. This method should be used for
\thashes generated by ImageHash up to version 3.7. For hashes
\tgenerated by newer versions of ImageHash, hex_to_hash should
\tbe used instead.
\t'''
        pass
    # WARNING: Decompyle incomplete

    
    def average_hash(image, hash_size, mean = (8, numpy.mean)):
        '''
\tAverage Hash computation

\tImplementation follows http://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html

\tStep by step explanation: https://web.archive.org/web/20171112054354/https://www.safaribooksonline.com/blog/2013/11/26/image-hashing-with-python/ # noqa: E501

\t@image must be a PIL instance.
\t@mean how to determine the average luminescence. can try numpy.median instead.
\t'''
        if hash_size < 2:
            raise ValueError('Hash size must be greater than or equal to 2')
        image = image.convert('L').resize((hash_size, hash_size), ANTIALIAS)
        pixels = numpy.asarray(image)
        avg = mean(pixels)
        diff = pixels > avg
        return ImageHash(diff)

    
    def phash(image, hash_size, highfreq_factor = (8, 4)):
        '''
\tPerceptual Hash computation.

\tImplementation follows http://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html

\t@image must be a PIL instance.
\t'''
        if hash_size < 2:
            raise ValueError('Hash size must be greater than or equal to 2')
        import scipy.fftpack as scipy
        img_size = hash_size * highfreq_factor
        image = image.convert('L').resize((img_size, img_size), ANTIALIAS)
        pixels = numpy.asarray(image)
        dct = scipy.fftpack.dct(scipy.fftpack.dct(pixels, axis = 0), axis = 1)
        dctlowfreq = dct[(:hash_size, :hash_size)]
        med = numpy.median(dctlowfreq)
        diff = dctlowfreq > med
        return ImageHash(diff)

    
    def phash_simple(image, hash_size, highfreq_factor = (8, 4)):
        '''
\tPerceptual Hash computation.

\tImplementation follows http://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html

\t@image must be a PIL instance.
\t'''
        import scipy.fftpack as scipy
        img_size = hash_size * highfreq_factor
        image = image.convert('L').resize((img_size, img_size), ANTIALIAS)
        pixels = numpy.asarray(image)
        dct = scipy.fftpack.dct(pixels)
        dctlowfreq = dct[(:hash_size, 1:hash_size + 1)]
        avg = dctlowfreq.mean()
        diff = dctlowfreq > avg
        return ImageHash(diff)

    
    def dhash(image, hash_size = (8,)):
        '''
\tDifference Hash computation.

\tfollowing http://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html

\tcomputes differences horizontally

\t@image must be a PIL instance.
\t'''
        if hash_size < 2:
            raise ValueError('Hash size must be greater than or equal to 2')
        image = image.convert('L').resize((hash_size + 1, hash_size), ANTIALIAS)
        pixels = numpy.asarray(image)
        diff = pixels[(:, 1:)] > pixels[(:, :-1)]
        return ImageHash(diff)

    
    def dhash_vertical(image, hash_size = (8,)):
        '''
\tDifference Hash computation.

\tfollowing http://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html

\tcomputes differences vertically

\t@image must be a PIL instance.
\t'''
        image = image.convert('L').resize((hash_size, hash_size + 1), ANTIALIAS)
        pixels = numpy.asarray(image)
        diff = pixels[(1:, :)] > pixels[(:-1, :)]
        return ImageHash(diff)

    
    def whash(image, hash_size, image_scale, mode, remove_max_haar_ll = (8, None, 'haar', True)):
        """
\tWavelet Hash computation.

\tbased on https://www.kaggle.com/c/avito-duplicate-ads-detection/

\t@image must be a PIL instance.
\t@hash_size must be a power of 2 and less than @image_scale.
\t@image_scale must be power of 2 and less than image size. By default is equal to max
\t\t\t\t\tpower of 2 for an input image.
\t@mode (see modes in pywt library):
\t\t\t\t\t'haar' - Haar wavelets, by default
\t\t\t\t\t'db4' - Daubechies wavelets
\t@remove_max_haar_ll - remove the lowest low level (LL) frequency using Haar wavelet.
\t"""
        import pywt
    # WARNING: Decompyle incomplete

    
    def colorhash(image, binbits = (3,)):
        '''
\tColor Hash computation.

\tComputes fractions of image in intensity, hue and saturation bins:

\t* the first binbits encode the black fraction of the image
\t* the next binbits encode the gray fraction of the remaining image (low saturation)
\t* the next 6*binbits encode the fraction in 6 bins of saturation, for highly saturated parts of the remaining image
\t* the next 6*binbits encode the fraction in 6 bins of saturation, for mildly saturated parts of the remaining image

\t@binbits number of bits to use to encode each pixel fractions
\t'''
        pass
    # WARNING: Decompyle incomplete

    
    class ImageMultiHash:
        '''
\tThis is an image hash containing a list of individual hashes for segments of the image.
\tThe matching logic is implemented as described in Efficient Cropping-Resistant Robust Image Hashing
\t'''
        
        def __init__(self, hashes):
            self.segment_hashes = hashes

        
        def __eq__(self, other):
            pass
        # WARNING: Decompyle incomplete

        
        def __ne__(self, other):
            return not self.matches(other)

        
        def __sub__(self, other, hamming_cutoff, bit_error_rate = (None, None)):
            (matches, sum_distance) = self.hash_diff(other, hamming_cutoff, bit_error_rate)
            max_difference = len(self.segment_hashes)
            if matches == 0:
                return max_difference
            max_distance = None * len(self.segment_hashes[0])
            tie_breaker = 0 - float(sum_distance) / max_distance
            match_score = matches + tie_breaker
            return max_difference - match_score

        
        def __hash__(self):
            return tuple((lambda .0: pass# WARNING: Decompyle incomplete
)(self.segment_hashes()))

        
        def __str__(self):
            return (lambda .0: pass# WARNING: Decompyle incomplete
)(self.segment_hashes())

        
        def __repr__(self):
            return repr(self.segment_hashes)

        
        def hash_diff(self, other_hash, hamming_cutoff, bit_error_rate = (None, None)):
            '''
\t\tGets the difference between two multi-hashes, as a tuple. The first element of the tuple is the number of
\t\tmatching segments, and the second element is the sum of the hamming distances of matching hashes.
\t\tNOTE: Do not order directly by this tuple, as higher is better for matches, and worse for hamming cutoff.
\t\t:param other_hash: The image multi hash to compare against
\t\t:param hamming_cutoff: The maximum hamming distance to a region hash in the target hash
\t\t:param bit_error_rate: Percentage of bits which can be incorrect, an alternative to the hamming cutoff. The
\t\tdefault of 0.25 means that the segment hashes can be up to 25% different
\t\t'''
            pass
        # WARNING: Decompyle incomplete

        
        def matches(self, other_hash, region_cutoff, hamming_cutoff, bit_error_rate = (1, None, None)):
            '''
\t\tChecks whether this hash matches another crop resistant hash, `other_hash`.
\t\t:param other_hash: The image multi hash to compare against
\t\t:param region_cutoff: The minimum number of regions which must have a matching hash
\t\t:param hamming_cutoff: The maximum hamming distance to a region hash in the target hash
\t\t:param bit_error_rate: Percentage of bits which can be incorrect, an alternative to the hamming cutoff. The
\t\tdefault of 0.25 means that the segment hashes can be up to 25% different
\t\t'''
            (matches, _) = self.hash_diff(other_hash, hamming_cutoff, bit_error_rate)
            return matches >= region_cutoff

        
        def best_match(self, other_hashes, hamming_cutoff, bit_error_rate = (None, None)):
            '''
\t\tReturns the hash in a list which is the best match to the current hash
\t\t:param other_hashes: A list of image multi hashes to compare against
\t\t:param hamming_cutoff: The maximum hamming distance to a region hash in the target hash
\t\t:param bit_error_rate: Percentage of bits which can be incorrect, an alternative to the hamming cutoff.
\t\tDefaults to 0.25 if unset, which means the hash can be 25% different
\t\t'''
            pass
        # WARNING: Decompyle incomplete


    
    def _find_region(remaining_pixels, segmented_pixels):
        '''
\tFinds a region and returns a set of pixel coordinates for it.
\t:param remaining_pixels: A numpy bool array, with True meaning the pixels are remaining to segment
\t:param segmented_pixels: A set of pixel coordinates which have already been assigned to segment. This will be
\tupdated with the new pixels added to the returned segment.
\t'''
        in_region = set()
        not_in_region = set()
        available_pixels = numpy.transpose(numpy.nonzero(remaining_pixels))
        start = tuple(available_pixels[0])
        in_region.add(start)
        new_pixels = in_region.copy()
        try_next = set()
        for pixel in new_pixels:
            (x, y) = pixel
            neighbours = [
                (x - 1, y),
                (x + 1, y),
                (x, y - 1),
                (x, y + 1)]
            try_next.update(neighbours)
            try_next.difference_update(segmented_pixels, not_in_region)
            if not try_next:
                pass
            else:
                new_pixels = set()
                for pixel in try_next:
                    if remaining_pixels[pixel]:
                        in_region.add(pixel)
                        new_pixels.add(pixel)
                        segmented_pixels.add(pixel)
                        continue
                    not_in_region.add(pixel)
                    return in_region

    
    def _find_all_segments(pixels, segment_threshold, min_segment_size):
        '''
\tFinds all the regions within an image pixel array, and returns a list of the regions.

\tNote: Slightly different segmentations are produced when using pillow version 6 vs. >=7, due to a change in
\trounding in the greyscale conversion.
\t:param pixels: A numpy array of the pixel brightnesses.
\t:param segment_threshold: The brightness threshold to use when differentiating between hills and valleys.
\t:param min_segment_size: The minimum number of pixels for a segment.
\t'''
        pass
    # WARNING: Decompyle incomplete

    
    def crop_resistant_hash(image, hash_func, limit_segments, segment_threshold, min_segment_size, segmentation_image_size = (None, None, 128, 500, 300)):
        '''
\tCreates a CropResistantHash object, by the algorithm described in the paper "Efficient Cropping-Resistant Robust
\tImage Hashing". DOI 10.1109/ARES.2014.85
\tThis algorithm partitions the image into bright and dark segments, using a watershed-like algorithm, and then does
\tan image hash on each segment. This makes the image much more resistant to cropping than other algorithms, with
\tthe paper claiming resistance to up to 50% cropping, while most other algorithms stop at about 5% cropping.

\tNote: Slightly different segmentations are produced when using pillow version 6 vs. >=7, due to a change in
\trounding in the greyscale conversion. This leads to a slightly different result.
\t:param image: The image to hash
\t:param hash_func: The hashing function to use
\t:param limit_segments: If you have storage requirements, you can limit to hashing only the M largest segments
\t:param segment_threshold: Brightness threshold between hills and valleys. This should be static, putting it between
\tpeak and trough dynamically breaks the matching
\t:param min_segment_size: Minimum number of pixels for a hashable segment
\t:param segmentation_image_size: Size which the image is resized to before segmentation
\t'''
        pass
    # WARNING: Decompyle incomplete

    return None
