# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: hostfxr.pyc (Python 3.11)

import sys
cdef = []
if sys.platform == 'win32':
    cdef.append('typedef wchar_t char_t;')
else:
    cdef.append('typedef char char_t;')
cdef.append('\nenum hostfxr_delegate_type\n{\n    hdt_com_activation,\n    hdt_load_in_memory_assembly,\n    hdt_winrt_activation,\n    hdt_com_register,\n    hdt_com_unregister,\n    hdt_load_assembly_and_get_function_pointer\n};\n\nint32_t hostfxr_main(const int argc, const char_t **argv);\n\nint32_t hostfxr_main_startupinfo(\n    const int argc,\n    const char_t **argv,\n    const char_t *host_path,\n    const char_t *dotnet_root,\n    const char_t *app_path);\n\ntypedef void (*hostfxr_error_writer_fn)(const char_t *message);\nhostfxr_error_writer_fn hostfxr_set_error_writer(hostfxr_error_writer_fn error_writer);\n\ntypedef void* hostfxr_handle;\ntypedef struct hostfxr_initialize_parameters\n{\n    size_t size;\n    const char_t *host_path;\n    const char_t *dotnet_root;\n} hostfxr_initialize_parameters;\n\nint32_t hostfxr_initialize_for_dotnet_command_line(\n    int argc,\n    const char_t **argv,\n    const hostfxr_initialize_parameters *parameters,\n    /*out*/ hostfxr_handle *host_context_handle);\nint32_t hostfxr_initialize_for_runtime_config(\n    const char_t *runtime_config_path,\n    const hostfxr_initialize_parameters *parameters,\n    /*out*/ hostfxr_handle *host_context_handle);\n\nint32_t hostfxr_get_runtime_property_value(\n    const hostfxr_handle host_context_handle,\n    const char_t *name,\n    /*out*/ const char_t **value);\nint32_t hostfxr_set_runtime_property_value(\n    const hostfxr_handle host_context_handle,\n    const char_t *name,\n    const char_t *value);\nint32_t hostfxr_get_runtime_properties(\n    const hostfxr_handle host_context_handle,\n    /*inout*/ size_t * count,\n    /*out*/ const char_t **keys,\n    /*out*/ const char_t **values);\n\nint32_t hostfxr_run_app(const hostfxr_handle host_context_handle);\nint32_t hostfxr_get_runtime_delegate(\n    const hostfxr_handle host_context_handle,\n    enum hostfxr_delegate_type type,\n    /*out*/ void **delegate);\n\nint32_t hostfxr_close(const hostfxr_handle host_context_handle);\n')
cdef.append('\n// Signature of delegate returned by coreclr_delegate_type::load_assembly_and_get_function_pointer\ntypedef int (__stdcall *load_assembly_and_get_function_pointer_fn)(\n    const char_t *assembly_path      /* Fully qualified path to assembly */,\n    const char_t *type_name          /* Assembly qualified type name */,\n    const char_t *method_name        /* Public static method name compatible with delegateType */,\n    const char_t *delegate_type_name /* Assembly qualified delegate type name or null */,\n    void         *reserved           /* Extensibility parameter (currently unused and must be 0) */,\n    /*out*/ void **delegate          /* Pointer where to store the function pointer result */);\n\n// Signature of delegate returned by load_assembly_and_get_function_pointer_fn when delegate_type_name == null (default)\ntypedef int (__stdcall *component_entry_point_fn)(void *arg, int32_t arg_size_in_bytes);\n')
