# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: fp_groups.pyc (Python 3.11)

'''Finitely Presented Groups and its algorithms. '''
from sympy.core.singleton import S
from sympy.core.symbol import symbols
from sympy.combinatorics.free_groups import FreeGroup, FreeGroupElement, free_group
from sympy.combinatorics.rewritingsystem import RewritingSystem
from sympy.combinatorics.coset_table import CosetTable, coset_enumeration_r, coset_enumeration_c
from sympy.combinatorics import PermutationGroup
from sympy.matrices.normalforms import invariant_factors
from sympy.matrices import Matrix
from sympy.polys.polytools import gcd
from sympy.printing.defaults import DefaultPrinting
from sympy.utilities import public
from sympy.utilities.magic import pollute
from itertools import product
fp_group = (lambda fr_grp, relators = ((),): _fp_group = FpGroup(fr_grp, relators)(_fp_group,) + tuple(_fp_group._generators))()
xfp_group = (lambda fr_grp, relators = ((),): _fp_group = FpGroup(fr_grp, relators)(_fp_group, _fp_group._generators))()
vfp_group = (lambda fr_grpm, relators: _fp_group = FpGroup(symbols, relators)(lambda .0: [ sym.name for sym in .0 ])(_fp_group.symbols(), _fp_group.generators)
    return _fp_group
)()

def _parse_relators(rels):
    '''Parse the passed relators.'''
    return rels


class FpGroup(DefaultPrinting):
    '''
    The FpGroup would take a FreeGroup and a list/tuple of relators, the
    relators would be specified in such a way that each of them be equal to the
    identity of the provided free group.

    '''
    is_group = True
    is_FpGroup = True
    is_PermutationGroup = False
    
    def __init__(self, fr_grp, relators):
        relators = _parse_relators(relators)
        self.free_group = fr_grp
        self.relators = relators
        self.generators = self._generators()
        self.dtype = type('FpGroupElement', (FpGroupElement,), {
            'group': self })
        self._coset_table = None
        self._is_standardized = False
        self._order = None
        self._center = None
        self._rewriting_system = RewritingSystem(self)
        self._perm_isomorphism = None

    
    def _generators(self):
        return self.free_group.generators

    
    def make_confluent(self):
        """
        Try to make the group's rewriting system confluent

        """
        self._rewriting_system.make_confluent()

    
    def reduce(self, word):
        """
        Return the reduced form of `word` in `self` according to the group's
        rewriting system. If it's confluent, the reduced form is the unique normal
        form of the word in the group.

        """
        return self._rewriting_system.reduce(word)

    
    def equals(self, word1, word2):
        """
        Compare `word1` and `word2` for equality in the group
        using the group's rewriting system. If the system is
        confluent, the returned answer is necessarily correct.
        (If it is not, `False` could be returned in some cases
        where in fact `word1 == word2`)

        """
        if self.reduce(word1 * word2 ** -1) == self.identity:
            return True
        if None._rewriting_system.is_confluent:
            return False

    identity = (lambda self: self.free_group.identity)()
    
    def __contains__(self, g):
        return g in self.free_group

    
    def subgroup(self, gens, C, homomorphism = (None, False)):
        '''
        Return the subgroup generated by `gens` using the
        Reidemeister-Schreier algorithm
        homomorphism -- When set to True, return a dictionary containing the images
                     of the presentation generators in the original group.

        Examples
        ========

        >>> from sympy.combinatorics.fp_groups import FpGroup
        >>> from sympy.combinatorics import free_group
        >>> F, x, y = free_group("x, y")
        >>> f = FpGroup(F, [x**3, y**5, (x*y)**2])
        >>> H = [x*y, x**-1*y**-1*x*y*x]
        >>> K, T = f.subgroup(H, homomorphism=True)
        >>> T(K.generators)
        [x*y, x**-1*y**2*x**-1]

        '''
        pass
    # WARNING: Decompyle incomplete

    
    def coset_enumeration(self, H, strategy, max_cosets, draft, incomplete = ('relator_based', None, None, False)):
        '''
        Return an instance of ``coset table``, when Todd-Coxeter algorithm is
        run over the ``self`` with ``H`` as subgroup, using ``strategy``
        argument as strategy. The returned coset table is compressed but not
        standardized.

        An instance of `CosetTable` for `fp_grp` can be passed as the keyword
        argument `draft` in which case the coset enumeration will start with
        that instance and attempt to complete it.

        When `incomplete` is `True` and the function is unable to complete for
        some reason, the partially complete table will be returned.

        '''
        if not max_cosets:
            max_cosets = CosetTable.coset_table_max_limit
        if strategy == 'relator_based':
            C = coset_enumeration_r(self, H, max_cosets = max_cosets, draft = draft, incomplete = incomplete)
        else:
            C = coset_enumeration_c(self, H, max_cosets = max_cosets, draft = draft, incomplete = incomplete)
        if C.is_complete():
            C.compress()
        return C

    
    def standardize_coset_table(self):
        '''
        Standardized the coset table ``self`` and makes the internal variable
        ``_is_standardized`` equal to ``True``.

        '''
        self._coset_table.standardize()
        self._is_standardized = True

    
    def coset_table(self, H, strategy, max_cosets, draft, incomplete = ('relator_based', None, None, False)):
        '''
        Return the mathematical coset table of ``self`` in ``H``.

        '''
        pass
    # WARNING: Decompyle incomplete

    
    def order(self, strategy = ('relator_based',)):
        '''
        Returns the order of the finitely presented group ``self``. It uses
        the coset enumeration with identity group as subgroup, i.e ``H=[]``.

        Examples
        ========

        >>> from sympy.combinatorics import free_group
        >>> from sympy.combinatorics.fp_groups import FpGroup
        >>> F, x, y = free_group("x, y")
        >>> f = FpGroup(F, [x, y**2])
        >>> f.order(strategy="coset_table_based")
        2

        '''
        pass
    # WARNING: Decompyle incomplete

    
    def _is_infinite(self):
        '''
        Test if the group is infinite. Return `True` if the test succeeds
        and `None` otherwise

        '''
        pass
    # WARNING: Decompyle incomplete

    
    def _finite_index_subgroup(self, s = (None,)):
        '''
        Find the elements of `self` that generate a finite index subgroup
        and, if found, return the list of elements and the coset table of `self` by
        the subgroup, otherwise return `(None, None)`

        '''
        pass
    # WARNING: Decompyle incomplete

    
    def most_frequent_generator(self):
        pass
    # WARNING: Decompyle incomplete

    
    def random(self):
        import random
        r = self.free_group.identity
        for i in range(random.randint(2, 3)):
            r = r * random.choice(self.generators) ** random.choice([
                1,
                -1])
            return r

    
    def index(self, H, strategy = ('relator_based',)):
        '''
        Return the index of subgroup ``H`` in group ``self``.

        Examples
        ========

        >>> from sympy.combinatorics import free_group
        >>> from sympy.combinatorics.fp_groups import FpGroup
        >>> F, x, y = free_group("x, y")
        >>> f = FpGroup(F, [x**5, y**4, y*x*y**3*x**3])
        >>> f.index([x])
        4

        '''
        if H == []:
            return self.order()
        C = None.coset_enumeration(H, strategy)
        return len(C.table)

    
    def __str__(self):
        if self.free_group.rank > 30:
            str_form = '<fp group with %s generators>' % self.free_group.rank
        else:
            str_form = '<fp group on the generators %s>' % str(self.generators)
        return str_form

    __repr__ = __str__
    
    def _to_perm_group(self):
        '''
        Return an isomorphic permutation group and the isomorphism.
        The implementation is dependent on coset enumeration so
        will only terminate for finite groups.

        '''
        pass
    # WARNING: Decompyle incomplete

    
    def _perm_group_list(self, method_name, *args):
        '''
        Given the name of a `PermutationGroup` method (returning a subgroup
        or a list of subgroups) and (optionally) additional arguments it takes,
        return a list or a list of lists containing the generators of this (or
        these) subgroups in terms of the generators of `self`.

        '''
        (P, T) = self._to_perm_group()
    # WARNING: Decompyle incomplete

    
    def derived_series(self):
        '''
        Return the list of lists containing the generators
        of the subgroups in the derived series of `self`.

        '''
        return self._perm_group_list('derived_series')

    
    def lower_central_series(self):
        '''
        Return the list of lists containing the generators
        of the subgroups in the lower central series of `self`.

        '''
        return self._perm_group_list('lower_central_series')

    
    def center(self):
        '''
        Return the list of generators of the center of `self`.

        '''
        return self._perm_group_list('center')

    
    def derived_subgroup(self):
        '''
        Return the list of generators of the derived subgroup of `self`.

        '''
        return self._perm_group_list('derived_subgroup')

    
    def centralizer(self, other):
        '''
        Return the list of generators of the centralizer of `other`
        (a list of elements of `self`) in `self`.

        '''
        T = self._to_perm_group()[1]
        other = T(other)
        return self._perm_group_list('centralizer', other)

    
    def normal_closure(self, other):
        '''
        Return the list of generators of the normal closure of `other`
        (a list of elements of `self`) in `self`.

        '''
        T = self._to_perm_group()[1]
        other = T(other)
        return self._perm_group_list('normal_closure', other)

    
    def _perm_property(self, attr):
        '''
        Given an attribute of a `PermutationGroup`, return
        its value for a permutation group isomorphic to `self`.

        '''
        P = self._to_perm_group()[0]
        return getattr(P, attr)

    is_abelian = (lambda self: self._perm_property('is_abelian'))()
    is_nilpotent = (lambda self: self._perm_property('is_nilpotent'))()
    is_solvable = (lambda self: self._perm_property('is_solvable'))()
    elements = (lambda self: (P, T) = self._to_perm_group()T.invert(P.elements))()
    is_cyclic = (lambda self: if len(self.generators) <= 1:
Truetry:
(P, T) = self._to_perm_group()except NotImplementedError:
raise NotImplementedError('Check for infinite Cyclic group is not implemented')P.is_cyclic)()
    
    def abelian_invariants(self):
        '''
        Return Abelian Invariants of a group.
        '''
        
        try:
            (P, T) = self._to_perm_group()
        except NotImplementedError:
            raise NotImplementedError('abelian invariants is not implementedfor infinite group')

        return P.abelian_invariants()

    
    def composition_series(self):
        '''
        Return subnormal series of maximum length for a group.
        '''
        
        try:
            (P, T) = self._to_perm_group()
        except NotImplementedError:
            raise NotImplementedError('composition series is not implementedfor infinite group')

        return P.composition_series()



class FpSubgroup(DefaultPrinting):
    pass
# WARNING: Decompyle incomplete


def low_index_subgroups(G, N, Y = ((),)):
    '''
    Implements the Low Index Subgroups algorithm, i.e find all subgroups of
    ``G`` upto a given index ``N``. This implements the method described in
    [Sim94]. This procedure involves a backtrack search over incomplete Coset
    Tables, rather than over forced coincidences.

    Parameters
    ==========

    G: An FpGroup < X|R >
    N: positive integer, representing the maximum index value for subgroups
    Y: (an optional argument) specifying a list of subgroup generators, such
    that each of the resulting subgroup contains the subgroup generated by Y.

    Examples
    ========

    >>> from sympy.combinatorics import free_group
    >>> from sympy.combinatorics.fp_groups import FpGroup, low_index_subgroups
    >>> F, x, y = free_group("x, y")
    >>> f = FpGroup(F, [x**2, y**3, (x*y)**4])
    >>> L = low_index_subgroups(f, 4)
    >>> for coset_table in L:
    ...     print(coset_table.table)
    [[0, 0, 0, 0]]
    [[0, 0, 1, 2], [1, 1, 2, 0], [3, 3, 0, 1], [2, 2, 3, 3]]
    [[0, 0, 1, 2], [2, 2, 2, 0], [1, 1, 0, 1]]
    [[1, 1, 0, 0], [0, 0, 1, 1]]

    References
    ==========

    .. [1] Holt, D., Eick, B., O\'Brien, E.
           "Handbook of Computational Group Theory"
           Section 5.4

    .. [2] Marston Conder and Peter Dobcsanyi
           "Applications and Adaptions of the Low Index Subgroups Procedure"

    '''
    pass
# WARNING: Decompyle incomplete


def descendant_subgroups(S, C, R1_c_list, x, R2, N, Y):
    A_dict = C.A_dict
    A_dict_inv = C.A_dict_inv
# WARNING: Decompyle incomplete


def try_descendant(S, C, R1_c_list, R2, N, alpha, x, beta, Y):
    '''
    Solves the problem of trying out each individual possibility
    for `\\alpha^x.

    '''
    D = C.copy()
    if beta == D.n and beta < N:
        D.table.append([
            None] * len(D.A))
        D.p.append(beta)
    D.table[alpha][D.A_dict[x]] = beta
    D.table[beta][D.A_dict_inv[x]] = alpha
    D.deduction_stack.append((alpha, x))
    if not D.process_deductions_check(R1_c_list[D.A_dict[x]], R1_c_list[D.A_dict_inv[x]]):
        return None
    for w in None:
        if not D.scan_check(0, w):
            return None
        if first_in_class(D, Y):
            descendant_subgroups(S, D, R1_c_list, x, R2, N, Y)
            return None
        return None


def first_in_class(C, Y = ((),)):
    '''
    Checks whether the subgroup ``H=G1`` corresponding to the Coset Table
    could possibly be the canonical representative of its conjugacy class.

    Parameters
    ==========

    C: CosetTable

    Returns
    =======

    bool: True/False

    If this returns False, then no descendant of C can have that property, and
    so we can abandon C. If it returns True, then we need to process further
    the node of the search tree corresponding to C, and so we call
    ``descendant_subgroups`` recursively on C.

    Examples
    ========

    >>> from sympy.combinatorics import free_group
    >>> from sympy.combinatorics.fp_groups import FpGroup, CosetTable, first_in_class
    >>> F, x, y = free_group("x, y")
    >>> f = FpGroup(F, [x**2, y**3, (x*y)**4])
    >>> C = CosetTable(f, [])
    >>> C.table = [[0, 0, None, None]]
    >>> first_in_class(C)
    True
    >>> C.table = [[1, 1, 1, None], [0, 0, None, 1]]; C.p = [0, 1]
    >>> first_in_class(C)
    True
    >>> C.table = [[1, 1, 2, 1], [0, 0, 0, None], [None, None, None, 0]]
    >>> C.p = [0, 1, 2]
    >>> first_in_class(C)
    False
    >>> C.table = [[1, 1, 1, 2], [0, 0, 2, 0], [2, None, 0, 1]]
    >>> first_in_class(C)
    False

    # TODO:: Sims points out in [Sim94] that performance can be improved by
    # remembering some of the information computed by ``first_in_class``. If
    # the ``continue alpha`` statement is executed at line 14, then the same thing
    # will happen for that value of alpha in any descendant of the table C, and so
    # the values the values of alpha for which this occurs could profitably be
    # stored and passed through to the descendants of C. Of course this would
    # make the code more complicated.

    # The code below is taken directly from the function on page 208 of [Sim94]
    # nu[alpha]

    '''
    n = C.n
    lamda = -1
    nu = [
        None] * n
    mu = [
        None] * n
    next_alpha = False
# WARNING: Decompyle incomplete


def simplify_presentation(*, change_gens, *args):
    '''
    For an instance of `FpGroup`, return a simplified isomorphic copy of
    the group (e.g. remove redundant generators or relators). Alternatively,
    a list of generators and relators can be passed in which case the
    simplified lists will be returned.

    By default, the generators of the group are unchanged. If you would
    like to remove redundant generators, set the keyword argument
    `change_gens = True`.

    '''
    if len(args) == 1:
        if not isinstance(args[0], FpGroup):
            raise TypeError('The argument must be an instance of FpGroup')
        G = args[0]
        (gens, rels) = simplify_presentation(G.generators, G.relators, change_gens = change_gens)
        if gens:
            return FpGroup(gens[0].group, rels)
        return None(FreeGroup([]), [])
    if None(args) == 2:
        rels = args[1][:]
        gens = args[0][:]
        if not gens:
            return (gens, rels)
        identity = None[0].group.identity
    elif len(args) == 0:
        m = 'Not enough arguments'
    else:
        m = 'Too many arguments'
    raise RuntimeError(m)
    prev_gens = []
    prev_rels = []
# WARNING: Decompyle incomplete


def _simplify_relators(rels):
    '''
    Simplifies a set of relators. All relators are checked to see if they are
    of the form `gen^n`. If any such relators are found then all other relators
    are processed for strings in the `gen` known order.

    Examples
    ========

    >>> from sympy.combinatorics import free_group
    >>> from sympy.combinatorics.fp_groups import _simplify_relators
    >>> F, x, y = free_group("x, y")
    >>> w1 = [x**2*y**4, x**3]
    >>> _simplify_relators(w1)
    [x**3, x**-1*y**4]

    >>> w2 = [x**2*y**-4*x**5, x**3, x**2*y**8, y**5]
    >>> _simplify_relators(w2)
    [x**-1*y**-2, x**-1*y*x**-1, x**3, y**5]

    >>> w3 = [x**6*y**4, x**4]
    >>> _simplify_relators(w3)
    [x**4, x**2*y**4]

    >>> w4 = [x**2, x**5, y**3]
    >>> _simplify_relators(w4)
    [x, y**3]

    '''
    rels = rels[:]
    if not rels:
        return []
    identity = None[0].group.identity
    exps = { }
    for i in range(len(rels)):
        rel = rels[i]
        if rel.number_syllables() == 1:
            g = rel[0]
            exp = abs(rel.array_form[0][1])
            if rel.array_form[0][1] < 0:
                rels[i] = rels[i] ** -1
                g = g ** -1
            if g in exps:
                exp = gcd(exp, exps[g].array_form[0][1])
            exps[g] = g ** exp
        one_syllables_words = list(exps.values())
        for i, rel in enumerate(rels):
            if rel in one_syllables_words:
                continue
            rel = rel.eliminate_words(one_syllables_words, _all = True)
            for g in rel.contains_generators():
                if g in exps:
                    exp = exps[g].array_form[0][1]
                    max_exp = (exp + 1) // 2
                    rel = rel.eliminate_word(g ** max_exp, g ** (max_exp - exp), _all = True)
                    rel = rel.eliminate_word(g ** (-max_exp), g ** (-(max_exp - exp)), _all = True)
                rels[i] = rel
                rels = rels()
                rels += one_syllables_words
                rels = list(set(rels))
                rels.sort()
                
                try:
                    rels.remove(identity)
                except ValueError:
                    pass

                return rels


def elimination_technique_1(gens, rels, identity):
    pass
# WARNING: Decompyle incomplete


def define_schreier_generators(C, homomorphism = (False,)):
    '''
    Parameters
    ==========

    C -- Coset table.
    homomorphism -- When set to True, return a dictionary containing the images
                     of the presentation generators in the original group.
    '''
    pass
# WARNING: Decompyle incomplete


def reidemeister_relators(C):
    pass
# WARNING: Decompyle incomplete


def rewrite(C, alpha, w):
    '''
    Parameters
    ==========

    C: CosetTable
    alpha: A live coset
    w: A word in `A*`

    Returns
    =======

    rho(tau(alpha), w)

    Examples
    ========

    >>> from sympy.combinatorics.fp_groups import FpGroup, CosetTable, define_schreier_generators, rewrite
    >>> from sympy.combinatorics import free_group
    >>> F, x, y = free_group("x, y")
    >>> f = FpGroup(F, [x**2, y**3, (x*y)**6])
    >>> C = CosetTable(f, [])
    >>> C.table = [[1, 1, 2, 3], [0, 0, 4, 5], [4, 4, 3, 0], [5, 5, 0, 2], [2, 2, 5, 1], [3, 3, 1, 4]]
    >>> C.p = [0, 1, 2, 3, 4, 5]
    >>> define_schreier_generators(C)
    >>> rewrite(C, 0, (x*y)**6)
    x_4*y_2*x_3*x_1*x_2*y_4*x_5

    '''
    v = C._schreier_free_group.identity
    for i in range(len(w)):
        x_i = w[i]
        v = v * C.P[alpha][C.A_dict[x_i]]
        alpha = C.table[alpha][C.A_dict[x_i]]
        return v


def elimination_technique_2(C):
    '''
    This technique eliminates one generator at a time. Heuristically this
    seems superior in that we may select for elimination the generator with
    shortest equivalent string at each stage.

    >>> from sympy.combinatorics import free_group
    >>> from sympy.combinatorics.fp_groups import FpGroup, coset_enumeration_r,             reidemeister_relators, define_schreier_generators, elimination_technique_2
    >>> F, x, y = free_group("x, y")
    >>> f = FpGroup(F, [x**3, y**5, (x*y)**2]); H = [x*y, x**-1*y**-1*x*y*x]
    >>> C = coset_enumeration_r(f, H)
    >>> C.compress(); C.standardize()
    >>> define_schreier_generators(C)
    >>> reidemeister_relators(C)
    >>> elimination_technique_2(C)
    ([y_1, y_2], [y_2**-3, y_2*y_1*y_2*y_1*y_2*y_1, y_1**2])

    '''
    rels = C._reidemeister_relators
    rels.sort(reverse = True)
    gens = C._schreier_generators
    for i in range(len(gens) - 1, -1, -1):
        rel = rels[i]
        for j in range(len(gens) - 1, -1, -1):
            gen = gens[j]
            if rel.generator_count(gen) == 1:
                k = rel.exponent_sum(gen)
                gen_index = rel.index(gen ** k)
                bk = rel.subword(gen_index + 1, len(rel))
                fw = rel.subword(0, gen_index)
                rep_by = (bk * fw) ** (-1 * k)
                del rels[i]
                del gens[j]
                for l in range(len(rels)):
                    rels[l] = rels[l].eliminate_word(gen, rep_by)
            C._reidemeister_relators = rels
            C._schreier_generators = gens
            return (C._schreier_generators, C._reidemeister_relators)


def reidemeister_presentation(fp_grp, H, C, homomorphism = (None, False)):
    '''
    Parameters
    ==========

    fp_group: A finitely presented group, an instance of FpGroup
    H: A subgroup whose presentation is to be found, given as a list
    of words in generators of `fp_grp`
    homomorphism: When set to True, return a homomorphism from the subgroup
                    to the parent group

    Examples
    ========

    >>> from sympy.combinatorics import free_group
    >>> from sympy.combinatorics.fp_groups import FpGroup, reidemeister_presentation
    >>> F, x, y = free_group("x, y")

    Example 5.6 Pg. 177 from [1]
    >>> f = FpGroup(F, [x**3, y**5, (x*y)**2])
    >>> H = [x*y, x**-1*y**-1*x*y*x]
    >>> reidemeister_presentation(f, H)
    ((y_1, y_2), (y_1**2, y_2**3, y_2*y_1*y_2*y_1*y_2*y_1))

    Example 5.8 Pg. 183 from [1]
    >>> f = FpGroup(F, [x**3, y**3, (x*y)**3])
    >>> H = [x*y, x*y**-1]
    >>> reidemeister_presentation(f, H)
    ((x_0, y_0), (x_0**3, y_0**3, x_0*y_0*x_0*y_0*x_0*y_0))

    Exercises Q2. Pg 187 from [1]
    >>> f = FpGroup(F, [x**2*y**2, y**-1*x*y*x**-3])
    >>> H = [x]
    >>> reidemeister_presentation(f, H)
    ((x_0,), (x_0**4,))

    Example 5.9 Pg. 183 from [1]
    >>> f = FpGroup(F, [x**3*y**-3, (x*y)**3, (x*y**-1)**2])
    >>> H = [x]
    >>> reidemeister_presentation(f, H)
    ((x_0,), (x_0**6,))

    '''
    if not C:
        C = coset_enumeration_r(fp_grp, H)
    C.compress()
    C.standardize()
    define_schreier_generators(C, homomorphism = homomorphism)
    reidemeister_relators(C)
    rels = C._reidemeister_relators
    gens = C._schreier_generators
    (gens, rels) = simplify_presentation(gens, rels, change_gens = True)
    C.schreier_generators = tuple(gens)
    C.reidemeister_relators = tuple(rels)
    if homomorphism:
        _gens = []
        for gen in gens:
            _gens.append(C._schreier_gen_elem[str(gen)])
            return (C.schreier_generators, C.reidemeister_relators, _gens)
            return (C.schreier_generators, C.reidemeister_relators)

FpGroupElement = FreeGroupElement
