# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: _agglomerative.pyc (Python 3.11)

'''Hierarchical Agglomerative Clustering

These routines perform some hierarchical agglomerative clustering of some
input data.
'''
import warnings
from heapq import heapify, heappop, heappush, heappushpop
from numbers import Integral, Real
import numpy as np
from scipy import sparse
from scipy.sparse.csgraph import connected_components
from sklearn.base import BaseEstimator, ClassNamePrefixFeaturesOutMixin, ClusterMixin, _fit_context
from sklearn.cluster import _hierarchical_fast as _hierarchical
from sklearn.cluster._feature_agglomeration import AgglomerationTransform
from sklearn.metrics import DistanceMetric
from sklearn.metrics._dist_metrics import METRIC_MAPPING64
from sklearn.metrics.pairwise import _VALID_METRICS, paired_distances
from sklearn.utils import check_array
from sklearn.utils._fast_dict import IntFloatDict
from sklearn.utils._param_validation import HasMethods, Interval, StrOptions, validate_params
from sklearn.utils.graph import _fix_connected_components
from sklearn.utils.validation import check_memory, validate_data

def _fix_connectivity(X, connectivity, affinity):
    '''
    Fixes the connectivity matrix.

    The different steps are:

    - copies it
    - makes it symmetric
    - converts it to LIL if necessary
    - completes it if necessary.

    Parameters
    ----------
    X : array-like of shape (n_samples, n_features)
        Feature matrix representing `n_samples` samples to be clustered.

    connectivity : sparse matrix, default=None
        Connectivity matrix. Defines for each sample the neighboring samples
        following a given structure of the data. The matrix is assumed to
        be symmetric and only the upper triangular half is used.
        Default is `None`, i.e, the Ward algorithm is unstructured.

    affinity : {"euclidean", "precomputed"}, default="euclidean"
        Which affinity to use. At the moment `precomputed` and
        ``euclidean`` are supported. `euclidean` uses the
        negative squared Euclidean distance between points.

    Returns
    -------
    connectivity : sparse matrix
        The fixed connectivity matrix.

    n_connected_components : int
        The number of connected components in the graph.
    '''
    n_samples = X.shape[0]
    if connectivity.shape[0] != n_samples or connectivity.shape[1] != n_samples:
        raise ValueError(f'''Wrong shape for connectivity matrix: {connectivity.shape!s} when X is {X.shape!s}''')
    connectivity = connectivity + connectivity.T
    if not sparse.issparse(connectivity):
        connectivity = sparse.lil_matrix(connectivity)
    if connectivity.format != 'lil':
        connectivity = connectivity.tolil()
    (n_connected_components, labels) = connected_components(connectivity)
    if n_connected_components > 1:
        warnings.warn('the number of connected components of the connectivity matrix is %d > 1. Completing it to avoid stopping the tree early.' % n_connected_components, stacklevel = 2)
        connectivity = _fix_connected_components(X = X, graph = connectivity, n_connected_components = n_connected_components, component_labels = labels, metric = affinity, mode = 'connectivity')
    return (connectivity, n_connected_components)


def _single_linkage_tree(connectivity, n_samples, n_nodes, n_clusters, n_connected_components, return_distance):
    '''
    Perform single linkage clustering on sparse data via the minimum
    spanning tree from scipy.sparse.csgraph, then using union-find to label.
    The parent array is then generated by walking through the tree.
    '''
    minimum_spanning_tree = minimum_spanning_tree
    import scipy.sparse.csgraph
    connectivity = connectivity.astype(np.float64, copy = False)
    epsilon_value = np.finfo(dtype = connectivity.data.dtype).eps
    connectivity.data[connectivity.data == 0] = epsilon_value
    mst = minimum_spanning_tree(connectivity.tocsr())
    mst = mst.tocoo()
    mst.data[mst.data == epsilon_value] = 0
    mst_array = np.vstack([
        mst.row,
        mst.col,
        mst.data]).T
    mst_array = mst_array[(np.argsort(mst_array.T[2], kind = 'mergesort'), :)]
    single_linkage_tree = _hierarchical._single_linkage_label(mst_array)
    children_ = single_linkage_tree[(:, :2)].astype(int)
    parent = np.arange(n_nodes, dtype = np.intp)
# WARNING: Decompyle incomplete

ward_tree = (lambda X = validate_params({
    'X': [
        'array-like'],
    'connectivity': [
        'array-like',
        'sparse matrix',
        None],
    'n_clusters': [
        Interval(Integral, 1, None, closed = 'left'),
        None],
    'return_distance': [
        'boolean'] }, prefer_skip_nested_validation = True), *, connectivity: pass# WARNING: Decompyle incomplete
)()

def linkage_tree(X, connectivity, n_clusters, linkage, affinity, return_distance = (None, None, 'complete', 'euclidean', False)):
    '''Linkage agglomerative clustering based on a Feature matrix.

    The inertia matrix uses a Heapq-based representation.

    This is the structured version, that takes into account some topological
    structure between samples.

    Read more in the :ref:`User Guide <hierarchical_clustering>`.

    Parameters
    ----------
    X : array-like of shape (n_samples, n_features)
        Feature matrix representing `n_samples` samples to be clustered.

    connectivity : sparse matrix, default=None
        Connectivity matrix. Defines for each sample the neighboring samples
        following a given structure of the data. The matrix is assumed to
        be symmetric and only the upper triangular half is used.
        Default is `None`, i.e, the Ward algorithm is unstructured.

    n_clusters : int, default=None
        Stop early the construction of the tree at `n_clusters`. This is
        useful to decrease computation time if the number of clusters is
        not small compared to the number of samples. In this case, the
        complete tree is not computed, thus the \'children\' output is of
        limited use, and the \'parents\' output should rather be used.
        This option is valid only when specifying a connectivity matrix.

    linkage : {"average", "complete", "single"}, default="complete"
        Which linkage criteria to use. The linkage criterion determines which
        distance to use between sets of observation.
            - "average" uses the average of the distances of each observation of
              the two sets.
            - "complete" or maximum linkage uses the maximum distances between
              all observations of the two sets.
            - "single" uses the minimum of the distances between all
              observations of the two sets.

    affinity : str or callable, default=\'euclidean\'
        Which metric to use. Can be \'euclidean\', \'manhattan\', or any
        distance known to paired distance (see metric.pairwise).

    return_distance : bool, default=False
        Whether or not to return the distances between the clusters.

    Returns
    -------
    children : ndarray of shape (n_nodes-1, 2)
        The children of each non-leaf node. Values less than `n_samples`
        correspond to leaves of the tree which are the original samples.
        A node `i` greater than or equal to `n_samples` is a non-leaf
        node and has children `children_[i - n_samples]`. Alternatively
        at the i-th iteration, children[i][0] and children[i][1]
        are merged to form node `n_samples + i`.

    n_connected_components : int
        The number of connected components in the graph.

    n_leaves : int
        The number of leaves in the tree.

    parents : ndarray of shape (n_nodes, ) or None
        The parent of each node. Only returned when a connectivity matrix
        is specified, elsewhere \'None\' is returned.

    distances : ndarray of shape (n_nodes-1,)
        Returned when `return_distance` is set to `True`.

        distances[i] refers to the distance between children[i][0] and
        children[i][1] when they are merged.

    See Also
    --------
    ward_tree : Hierarchical clustering with ward linkage.
    '''
    pass
# WARNING: Decompyle incomplete


def _complete_linkage(*args, **kwargs):
    kwargs['linkage'] = 'complete'
# WARNING: Decompyle incomplete


def _average_linkage(*args, **kwargs):
    kwargs['linkage'] = 'average'
# WARNING: Decompyle incomplete


def _single_linkage(*args, **kwargs):
    kwargs['linkage'] = 'single'
# WARNING: Decompyle incomplete

_TREE_BUILDERS = dict(ward = ward_tree, complete = _complete_linkage, average = _average_linkage, single = _single_linkage)

def _hc_cut(n_clusters, children, n_leaves):
    '''Function cutting the ward tree for a given number of clusters.

    Parameters
    ----------
    n_clusters : int or ndarray
        The number of clusters to form.

    children : ndarray of shape (n_nodes-1, 2)
        The children of each non-leaf node. Values less than `n_samples`
        correspond to leaves of the tree which are the original samples.
        A node `i` greater than or equal to `n_samples` is a non-leaf
        node and has children `children_[i - n_samples]`. Alternatively
        at the i-th iteration, children[i][0] and children[i][1]
        are merged to form node `n_samples + i`.

    n_leaves : int
        Number of leaves of the tree.

    Returns
    -------
    labels : array [n_samples]
        Cluster labels for each point.
    '''
    if n_clusters > n_leaves:
        raise ValueError(f'''Cannot extract more clusters than samples: {n_clusters} clusters were given for a tree with {n_leaves} leaves.''')
    nodes = [
        -(max(children[-1]) + 1)]
    for _ in range(n_clusters - 1):
        these_children = children[-nodes[0] - n_leaves]
        heappush(nodes, -these_children[0])
        heappushpop(nodes, -these_children[1])
        label = np.zeros(n_leaves, dtype = np.intp)
        for i, node in enumerate(nodes):
            label[_hierarchical._hc_get_descendent(-node, children, n_leaves)] = i
            return label


class AgglomerativeClustering(BaseEstimator, ClusterMixin):
    pass
# WARNING: Decompyle incomplete


class FeatureAgglomeration(AgglomerativeClustering, AgglomerationTransform, ClassNamePrefixFeaturesOutMixin):
    pass
# WARNING: Decompyle incomplete
