# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: loading.pyc (Python 3.11)

'''private module containing functions used to convert database
rows into object instances and associated state.

the functions here are called primarily by Query, Mapper,
as well as some of the attribute loading strategies.

'''
from __future__ import annotations
from typing import Any
from typing import Dict
from typing import Iterable
from typing import List
from typing import Mapping
from typing import Optional
from typing import Sequence
from typing import Tuple
from typing import TYPE_CHECKING
from typing import TypeVar
from typing import Union
from  import attributes
from  import exc as orm_exc
from  import path_registry
from base import _DEFER_FOR_STATE
from base import _RAISE_FOR_STATE
from base import _SET_DEFERRED_EXPIRED
from base import PassiveFlag
from context import FromStatement
from context import ORMCompileState
from context import QueryContext
from strategies import SelectInLoader
from util import _none_set
from util import state_str
from  import exc as sa_exc
from  import util
from engine import result_tuple
from engine.result import ChunkedIteratorResult
from engine.result import FrozenResult
from engine.result import SimpleResultMetaData
from sql import select
from sql import util as sql_util
from sql.selectable import ForUpdateArg
from sql.selectable import LABEL_STYLE_TABLENAME_PLUS_COL
from sql.selectable import SelectState
from util import EMPTY_DICT
if TYPE_CHECKING:
    from _typing import _IdentityKeyType
    from base import LoaderCallableStatus
    from interfaces import ORMOption
    from mapper import Mapper
    from query import Query
    from session import Session
    from state import InstanceState
    from engine.cursor import CursorResult
    from engine.interfaces import _ExecuteOptions
    from engine.result import Result
    from sql import Select
_T = TypeVar('_T', bound = Any)
_O = TypeVar('_O', bound = object)
_new_runid = util.counter()
_PopulatorDict = Dict[(str, List[Tuple[(str, Any)]])]

def instances(cursor = None, context = None):
    '''Return a :class:`.Result` given an ORM query context.

    :param cursor: a :class:`.CursorResult`, generated by a statement
     which came from :class:`.ORMCompileState`

    :param context: a :class:`.QueryContext` object

    :return: a :class:`.Result` object representing ORM results

    .. versionchanged:: 1.4 The instances() function now uses
       :class:`.Result` objects and has an all new interface.

    '''
    pass
# WARNING: Decompyle incomplete

merge_frozen_result = (lambda session, statement, frozen_result, load = (True,): pass# WARNING: Decompyle incomplete
)()
merge_result = (lambda query = util.preload_module('sqlalchemy.orm.context'), iterator = util.became_legacy_20(':func:`_orm.merge_result`', alternative = 'The function as well as the method on :class:`_orm.Query` is superseded by the :func:`_orm.merge_frozen_result` function.'), load = util.preload_module('sqlalchemy.orm.context'): pass# WARNING: Decompyle incomplete
)()()

def get_from_identity(session = None, mapper = None, key = None, passive = ('session', 'Session', 'mapper', 'Mapper[_O]', 'key', '_IdentityKeyType[_O]', 'passive', 'PassiveFlag', 'return', 'Union[LoaderCallableStatus, Optional[_O]]')):
    """Look up the given key in the given session's identity map,
    check the object for expired state if found.

    """
    instance = session.identity_map.get(key)
# WARNING: Decompyle incomplete


def load_on_ident(session = None, statement = None, key = None, *, load_options, refresh_state, with_for_update, only_load_props, no_autoflush, bind_arguments, execution_options, require_pk_cols, is_user_refresh):
    '''Load the given identity key from the database.'''
    pass
# WARNING: Decompyle incomplete


def load_on_pk_identity(session = None, statement = None, primary_key_identity = None, *, load_options, refresh_state, with_for_update, only_load_props, identity_token, no_autoflush, bind_arguments, execution_options, require_pk_cols, is_user_refresh):
    '''Load the given primary key identity from the database.'''
    pass
# WARNING: Decompyle incomplete


def _set_get_options(compile_opt, load_opt, populate_existing, version_check, only_load_props, refresh_state, identity_token, is_user_refresh = (None, None, None, None, None, None)):
    compile_options = { }
    load_options = { }
    if version_check:
        load_options['_version_check'] = version_check
    if populate_existing:
        load_options['_populate_existing'] = populate_existing
    if refresh_state:
        load_options['_refresh_state'] = refresh_state
        compile_options['_for_refresh_state'] = True
    if only_load_props:
        compile_options['_only_load_props'] = frozenset(only_load_props)
    if identity_token:
        load_options['_identity_token'] = identity_token
    if is_user_refresh:
        load_options['_is_user_refresh'] = is_user_refresh
    if load_options:
        load_opt += load_options
    if compile_options:
        compile_opt += compile_options
    return (compile_opt, load_opt)


def _setup_entity_query(compile_state, mapper, query_entity, path, adapter, column_collection, with_polymorphic, only_load_props, polymorphic_discriminator = (None, None, None), **kw):
    if with_polymorphic:
        poly_properties = mapper._iterate_polymorphic_properties(with_polymorphic)
    else:
        poly_properties = mapper._polymorphic_properties
    quick_populators = { }
    path.set(compile_state.attributes, 'memoized_setups', quick_populators)
# WARNING: Decompyle incomplete


def _warn_for_runid_changed(state):
    util.warn(f'''Loading context for {state_str(state)!s} has changed within a load/refresh handler, suggesting a row refresh operation took place. If this event handler is expected to be emitting row refresh operations within an existing load or refresh operation, set restore_load_context=True when establishing the listener to ensure the context remains unchanged when the event handler completes.''')


def _instance_processor(query_entity, mapper, context, result, path, adapter, only_load_props, refresh_state, polymorphic_discriminator, _polymorphic_from = (None, None, None, None)):
    '''Produce a mapper level row processor callable
    which processes rows into mapped instances.'''
    pass
# WARNING: Decompyle incomplete


def _load_subclass_via_in(context, path, entity, polymorphic_from, option_entities):
    pass
# WARNING: Decompyle incomplete


def _populate_full(context, row, state, dict_, isnew, load_path, loaded_instance, populate_existing, populators):
    if isnew:
        state.runid = context.runid
        for key, getter in populators['quick']:
            dict_[key] = getter(row)
            if populate_existing:
                for key, set_callable in populators['expire']:
                    dict_.pop(key, None)
                    if set_callable:
                        state.expired_attributes.add(key)
        for key, set_callable in populators['expire']:
            if set_callable:
                state.expired_attributes.add(key)
            for key, populator in populators['new']:
                populator(state, dict_, row)
                return None
                if load_path != state.load_path:
                    state.load_path = load_path
                    for key, getter in populators['quick']:
                        if key not in dict_:
                            dict_[key] = getter(row)
                        for key, populator in populators['existing']:
                            populator(state, dict_, row)
                            return None
                            for key, populator in populators['existing']:
                                populator(state, dict_, row)
                                return None


def _populate_partial(context, row, state, dict_, isnew, load_path, unloaded, populators):
    if not isnew:
        if unloaded:
            for key, getter in populators['quick']:
                if key in unloaded:
                    dict_[key] = getter(row)
                to_load = context.partials[state]
                for key, populator in populators['existing']:
                    if key in to_load:
                        populator(state, dict_, row)
                to_load = unloaded
                context.partials[state] = to_load
                for key, getter in populators['quick']:
                    if key in to_load:
                        dict_[key] = getter(row)
                    for key, set_callable in populators['expire']:
                        if key in to_load:
                            dict_.pop(key, None)
                            if set_callable:
                                state.expired_attributes.add(key)
                        for key, populator in populators['new']:
                            if key in to_load:
                                populator(state, dict_, row)
                            for key, populator in populators['eager']:
                                if key not in unloaded:
                                    populator(state, dict_, row)
                                return to_load


def _validate_version_id(mapper, state, dict_, row, getter):
    if mapper._get_state_attr_by_column(state, dict_, mapper.version_id_col) != getter(row):
        raise orm_exc.StaleDataError(f'''Instance \'{state_str(state)!s}\' has version id \'{mapper._get_state_attr_by_column(state, dict_, mapper.version_id_col)!s}\' which does not match database-loaded version id \'{getter(row)!s}\'.''')


def _decorate_polymorphic_switch(instance_fn, context, query_entity, mapper, result, path, polymorphic_discriminator, adapter, ensure_no_pk):
    pass
# WARNING: Decompyle incomplete


class PostLoad:
    '''Track loaders and states for "post load" operations.'''
    __slots__ = ('loaders', 'states', 'load_keys')
    
    def __init__(self):
        self.loaders = { }
        self.states = util.OrderedDict()
        self.load_keys = None

    
    def add_state(self, state, overwrite):
        self.states[state] = overwrite

    
    def invoke(self, context, path):
        pass
    # WARNING: Decompyle incomplete

    for_context = (lambda cls, context, path, only_load_props: pl = context.post_load_paths.get(path.path)# WARNING: Decompyle incomplete
)()
    path_exists = (lambda self, context, path, key: if path.path in context.post_load_paths:
passkey in context.post_load_paths[path.path].loaders)()
    callable_for_path = (lambda cls, context, path, limit_to_mapper, token, loader_callable: if path.path in context.post_load_paths:
pl = context.post_load_paths[path.path]else:
pl = PostLoad()context.post_load_paths[path.path] = PostLoad()pl.loaders[token] = (context, token, limit_to_mapper, loader_callable, arg, kw))()


def load_scalar_attributes(mapper, state, attribute_names, passive):
    '''initiate a column-based attribute refresh operation.'''
    pass
# WARNING: Decompyle incomplete
