# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: path_registry.pyc (Python 3.11)

'''Path tracking utilities, representing mapper graph traversals.'''
from __future__ import annotations
from functools import reduce
from itertools import chain
import logging
import operator
from typing import Any
from typing import cast
from typing import Dict
from typing import Iterator
from typing import List
from typing import Optional
from typing import overload
from typing import Sequence
from typing import Tuple
from typing import TYPE_CHECKING
from typing import Union
from  import base as orm_base
from _typing import insp_is_mapper_property
from  import exc
from  import util
from sql import visitors
from sql.cache_key import HasCacheKey
if TYPE_CHECKING:
    from _typing import _InternalEntityType
    from interfaces import StrategizedProperty
    from mapper import Mapper
    from relationships import RelationshipProperty
    from util import AliasedInsp
    from sql.cache_key import _CacheKeyTraversalType
    from sql.elements import BindParameter
    from sql.visitors import anon_map
    from util.typing import _LiteralStar
    from util.typing import TypeGuard
    
    def is_root(path = None):
        pass

    
    def is_entity(path = None):
        pass

else:
    is_root = operator.attrgetter('is_root')
    is_entity = operator.attrgetter('is_entity')
_SerializedPath = List[Any]
_StrPathToken = str
_PathElementType = Union[(_StrPathToken, '_InternalEntityType[Any]', 'StrategizedProperty[Any]')]
_PathRepresentation = Tuple[(_PathElementType, ...)]
_OddPathRepresentation = Sequence['_InternalEntityType[Any]']
_EvenPathRepresentation = Sequence[Union[('StrategizedProperty[Any]', str)]]
log = logging.getLogger(__name__)

def _unreduce_path(path = None):
    return PathRegistry.deserialize(path)

_WILDCARD_TOKEN: '_LiteralStar' = '*'
_DEFAULT_TOKEN = '_sa_default'

class PathRegistry(HasCacheKey):
    '''Represent query load paths and registry functions.

    Basically represents structures like:

    (<User mapper>, "orders", <Order mapper>, "items", <Item mapper>)

    These structures are generated by things like
    query options (joinedload(), subqueryload(), etc.) and are
    used to compose keys stored in the query._attributes dictionary
    for various options.

    They are then re-composed at query compile/result row time as
    the query is formed and as rows are fetched, where they again
    serve to compose keys to look up options in the context.attributes
    dictionary, which is copied from query._attributes.

    The path structure has a limited amount of caching, where each
    "root" ultimately pulls from a fixed registry associated with
    the first mapper, that also contains elements for each of its
    property keys.  However paths longer than two elements, which
    are the exception rather than the rule, are generated on an
    as-needed basis.

    '''
    __slots__ = ()
    is_token = False
    is_root = False
    has_entity = False
    is_property = False
    root: 'RootRegistry' = False
    _cache_key_traversal: '_CacheKeyTraversalType' = [
        ('path', visitors.ExtendedInternalTraversal.dp_has_cache_key_list)]
    
    def __eq__(self = None, other = None):
        
        try:
            if other is not None:
                pass
            return self.path == other._path_for_compare
        except AttributeError:
            util.warn('Comparison of PathRegistry to %r is not supported' % type(other))
            return False


    
    def __ne__(self = None, other = None):
        
        try:
            if not other is None:
                pass
            return self.path != other._path_for_compare
        except AttributeError:
            util.warn('Comparison of PathRegistry to %r is not supported' % type(other))
            return True


    _path_for_compare = (lambda self = None: self.path)()
    
    def odd_element(self = None, index = None):
        return self.path[index]

    
    def set(self = None, attributes = None, key = None, value = ('attributes', 'Dict[Any, Any]', 'key', 'Any', 'value', 'Any', 'return', 'None')):
        log.debug("set '%s' on path '%s' to '%s'", key, self, value)
        attributes[(key, self.natural_path)] = value

    
    def setdefault(self = None, attributes = None, key = None, value = ('attributes', 'Dict[Any, Any]', 'key', 'Any', 'value', 'Any', 'return', 'None')):
        log.debug("setdefault '%s' on path '%s' to '%s'", key, self, value)
        attributes.setdefault((key, self.natural_path), value)

    
    def get(self = None, attributes = None, key = None, value = (None,)):
        key = (key, self.natural_path)
        if key in attributes:
            return attributes[key]

    
    def __len__(self = None):
        return len(self.path)

    
    def __hash__(self = None):
        return id(self)

    __getitem__ = (lambda self = None, entity = None: pass)()
    __getitem__ = (lambda self = None, entity = None: pass)()
    __getitem__ = (lambda self = None, entity = None: pass)()
    __getitem__ = (lambda self = None, entity = None: pass)()
    __getitem__ = (lambda self = None, entity = None: pass)()
    
    def __getitem__(self = None, entity = None):
        raise NotImplementedError()

    length = (lambda self = None: len(self.path))()
    
    def pairs(self = None):
        pass
    # WARNING: Decompyle incomplete

    
    def contains_mapper(self = None, mapper = None):
        pass
    # WARNING: Decompyle incomplete

    
    def contains(self = None, attributes = None, key = None):
        return (key, self.path) in attributes

    
    def __reduce__(self = None):
        return (_unreduce_path, (self.serialize(),))

    _serialize_path = (lambda cls = None, path = None: pass# WARNING: Decompyle incomplete
)()
    _deserialize_path = (lambda cls = None, path = None: pass# WARNING: Decompyle incomplete
)()
    
    def serialize(self = None):
        path = self.path
        return self._serialize_path(path)

    deserialize = (lambda cls = None, path = None: pass# WARNING: Decompyle incomplete
)()
    per_mapper = (lambda cls = None, mapper = overload: pass)()()
    per_mapper = (lambda cls = None, mapper = overload: pass)()()
    per_mapper = (lambda cls = None, mapper = None: if mapper.is_mapper:
CachingEntityRegistry(cls.root, mapper)None(cls.root, mapper))()
    coerce = (lambda cls = None, raw = None: 
def _red(prev = None, next_ = None):
prev[next_]reduce(_red, raw, cls.root))()
    
    def __add__(self = None, other = None):
        
        def _red(prev = None, next_ = None):
            return prev[next_]

        return reduce(_red, other.path, self)

    
    def __str__(self = None):
        return f'''{(lambda .0: pass# WARNING: Decompyle incomplete
)(self.path())}]'''

    
    def __repr__(self = None):
        return f'''{self.__class__.__name__}({self.path!r})'''



class CreatesToken(PathRegistry):
    is_root: 'bool' = ()
    
    def token(self = None, token = None):
        if token.endswith(f''':{_WILDCARD_TOKEN}'''):
            return TokenRegistry(self, token)
        if None.endswith(f''':{_DEFAULT_TOKEN}'''):
            return TokenRegistry(self.root, token)
        raise None.ArgumentError(f'''invalid token: {token}''')



class RootRegistry(CreatesToken):
    '''Root registry, defers to mappers so that
    paths are maintained per-root-mapper.

    '''
    __slots__ = ()
    inherit_cache = True
    path = ()
    natural_path = ()
    has_entity = False
    is_aliased_class = False
    is_root = True
    is_unnatural = False
    
    def _getitem(self = None, entity = None):
        pass
    # WARNING: Decompyle incomplete

    
    def _truncate_recursive(self = None):
        return self

    if not TYPE_CHECKING:
        __getitem__ = _getitem
        return None

PathRegistry.root = RootRegistry()

class PathToken(str, HasCacheKey, orm_base.InspectionAttr):
    '''cacheable string token'''
    _intern: 'Dict[str, PathToken]' = { }
    
    def _gen_cache_key(self = None, anon_map = None, bindparams = None):
        return (str(self),)

    _path_for_compare = (lambda self = None: pass)()
    intern = (lambda cls = None, strvalue = None: if strvalue in cls._intern:
cls._intern[strvalue]cls._intern[strvalue] = None(strvalue)result = None(strvalue)result)()


class TokenRegistry(PathRegistry):
    __slots__ = ('token', 'parent', 'path', 'natural_path')
    parent: 'CreatesToken' = True
    
    def __init__(self = None, parent = None, token = None):
        token = PathToken.intern(token)
        self.token = token
        self.parent = parent
        self.path = parent.path + (token,)
        self.natural_path = parent.natural_path + (token,)

    has_entity = False
    is_token = True
    
    def generate_for_superclasses(self = None):
        pass
    # WARNING: Decompyle incomplete

    
    def _generate_natural_for_superclasses(self = None):
        pass
    # WARNING: Decompyle incomplete

    
    def _getitem(self = None, entity = None):
        
        try:
            return self.path[entity]
        except TypeError:
            err = None
            raise IndexError(f'''{entity}'''), err
            err = None
            del err


    if not TYPE_CHECKING:
        __getitem__ = _getitem
        return None


class PropRegistry(PathRegistry):
    __slots__ = ('prop', 'parent', 'path', 'natural_path', 'has_entity', 'entity', 'mapper', '_wildcard_path_loader_key', '_default_path_loader_key', '_loader_key', 'is_unnatural')
    inherit_cache = True
    entity: 'Optional[_InternalEntityType[Any]]' = True
    
    def __init__(self = None, parent = None, prop = None):
        insp = cast('_InternalEntityType[Any]', parent[-1])
        natural_parent = parent
        if not parent.parent.is_unnatural:
            self.is_unnatural = bool(parent.mapper.inherits)
            if insp.is_aliased_class or insp._use_mapper_path:
                parent = parent.parent[prop.parent]
                natural_parent = parent.parent[prop.parent]
            elif insp.is_aliased_class and insp.with_polymorphic_mappers and prop.parent in insp.with_polymorphic_mappers:
                subclass_entity = parent[-1]._entity_for_mapper(prop.parent)
                parent = parent.parent[subclass_entity]
                if parent.parent:
                    natural_parent = parent.parent[subclass_entity.mapper]
                    self.is_unnatural = True
                else:
                    natural_parent = parent
            elif natural_parent.parent and insp.is_aliased_class and prop.parent is not insp.mapper and insp.mapper.isa(prop.parent):
                natural_parent = parent.parent[prop.parent]
        self.prop = prop
        self.parent = parent
        self.path = parent.path + (prop,)
        self.natural_path = natural_parent.natural_path + (prop,)
        self.has_entity = prop._links_to_entity
    # WARNING: Decompyle incomplete

    
    def _truncate_recursive(self = None):
        earliest = None
    # WARNING: Decompyle incomplete

    entity_path = (lambda self = None: pass# WARNING: Decompyle incomplete
)()
    
    def _getitem(self = None, entity = None):
        if isinstance(entity, (int, slice)):
            return self.path[entity]
        return None(self, entity)

    if not TYPE_CHECKING:
        __getitem__ = _getitem
        return None


class AbstractEntityRegistry(CreatesToken):
    __slots__ = ('key', 'parent', 'is_aliased_class', 'path', 'entity', 'natural_path')
    has_entity = True
    is_aliased_class: 'bool' = True
    
    def __init__(self = None, parent = None, entity = None):
