# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: environment_vars.pyc (Python 3.11)

'''Environment variables used by :mod:`google.auth`.'''
PROJECT = 'GOOGLE_CLOUD_PROJECT'
LEGACY_PROJECT = 'GCLOUD_PROJECT'
GOOGLE_CLOUD_QUOTA_PROJECT = 'GOOGLE_CLOUD_QUOTA_PROJECT'
CREDENTIALS = 'GOOGLE_APPLICATION_CREDENTIALS'
CLOUD_SDK_CONFIG_DIR = 'CLOUDSDK_CONFIG'
GCE_METADATA_HOST = 'GCE_METADATA_HOST'
GCE_METADATA_ROOT = 'GCE_METADATA_ROOT'
GCE_METADATA_IP = 'GCE_METADATA_IP'
GOOGLE_API_USE_CLIENT_CERTIFICATE = 'GOOGLE_API_USE_CLIENT_CERTIFICATE'
LEGACY_APPENGINE_RUNTIME = 'APPENGINE_RUNTIME'
AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID'
AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY'
AWS_SESSION_TOKEN = 'AWS_SESSION_TOKEN'
AWS_REGION = 'AWS_REGION'
AWS_DEFAULT_REGION = 'AWS_DEFAULT_REGION'
GOOGLE_AUTH_TRUST_BOUNDARY_ENABLED = 'GOOGLE_AUTH_TRUST_BOUNDARY_ENABLED'
