# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: _utilities.pyc (Python 3.11)

'''Internal utilities for gRPC Python.'''
import collections
import logging
import threading
import time
from typing import Callable, Dict, Optional, Sequence
import grpc
from grpc import _common
from grpc._typing import DoneCallbackType
_LOGGER = logging.getLogger(__name__)
_DONE_CALLBACK_EXCEPTION_LOG_MESSAGE = 'Exception calling connectivity future "done" callback!'

def RpcMethodHandler():
    '''RpcMethodHandler'''
    pass

RpcMethodHandler = <NODE:27>(RpcMethodHandler, 'RpcMethodHandler', collections.namedtuple('_RpcMethodHandler', ('request_streaming', 'response_streaming', 'request_deserializer', 'response_serializer', 'unary_unary', 'unary_stream', 'stream_unary', 'stream_stream')), grpc.RpcMethodHandler)

class DictionaryGenericHandler(grpc.ServiceRpcHandler):
    _method_handlers: Dict[(str, grpc.RpcMethodHandler)] = 'DictionaryGenericHandler'
    
    def __init__(self = None, service = None, method_handlers = None):
        pass
    # WARNING: Decompyle incomplete

    
    def service_name(self = None):
        return self._name

    
    def service(self = None, handler_call_details = None):
        details_method = handler_call_details.method
        return self._method_handlers.get(details_method)



class _ChannelReadyFuture(grpc.Future):
    _done_callbacks: Sequence[Callable] = '_ChannelReadyFuture'
    
    def __init__(self = None, channel = None):
        self._condition = threading.Condition()
        self._channel = channel
        self._matured = False
        self._cancelled = False
        self._done_callbacks = []

    
    def _block(self = None, timeout = None):
        pass
    # WARNING: Decompyle incomplete

    
    def _update(self = None, connectivity = None):
        self._condition
        if self._cancelled and connectivity is grpc.ChannelConnectivity.READY:
            self._matured = True
            self._channel.unsubscribe(self._update)
            self._condition.notify_all()
            done_callbacks = tuple(self._done_callbacks)
            self._done_callbacks = None
        else:
            None(None, None)
            return None
        None(None, None)

    
    def cancel(self = None):
        self._condition
        if not self._matured:
            self._cancelled = True
            self._channel.unsubscribe(self._update)
            self._condition.notify_all()
            done_callbacks = tuple(self._done_callbacks)
            self._done_callbacks = None
        else:
            None(None, None)
            return False
        None(None, None)

    
    def cancelled(self = None):
        self._condition
        None(None, None)
        return 
        with None:
            if not None, self._cancelled:
                pass

    
    def running(self = None):
        self._condition
        if not (self._cancelled):
            None(None, None)
            return 
        with None:
            if not not (self._cancelled):
                pass

    
    def done(self = None):
        self._condition
        if not self._cancelled:
            None(None, None)
            return 
        with None:
            if not self._cancelled:
                pass

    
    def result(self = None, timeout = None):
        self._block(timeout)

    
    def exception(self = None, timeout = None):
        self._block(timeout)

    
    def traceback(self = None, timeout = None):
        self._block(timeout)

    
    def add_done_callback(self = None, fn = None):
        self._condition
        if not self._cancelled and self._matured:
            self._done_callbacks.append(fn)
            None(None, None)
            return None
        None(None, None)

    
    def start(self):
        self._condition
        self._channel.subscribe(self._update, try_to_connect = True)
        None(None, None)
        return None
        with None:
            if not None:
                pass

    
    def __del__(self):
        self._condition
        if not self._cancelled and self._matured:
            self._channel.unsubscribe(self._update)
        None(None, None)
        return None
        with None:
            if not None:
                pass



def channel_ready_future(channel = None):
    ready_future = _ChannelReadyFuture(channel)
    ready_future.start()
    return ready_future


def first_version_is_lower(version1 = None, version2 = None):
    """
    Compares two versions in the format '1.60.1' or '1.60.1.dev0'.

    This method will be used in all stubs generated by grpcio-tools to check whether
    the stub version is compatible with the runtime grpcio.

    Args:
        version1: The first version string.
        version2: The second version string.

    Returns:
        True if version1 is lower, False otherwise.
    """
    version1_list = version1.split('.')
    version2_list = version2.split('.')
    
    try:
        for i in range(3):
            if int(version1_list[i]) < int(version2_list[i]):
                return True
            if None(version1_list[i]) > int(version2_list[i]):
                return False
    except ValueError:
        return False
        return len(version1_list) < len(version2_list)
