# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: style_profile_filter.pyc (Python 3.11)

import re
from typing import Dict, List, Optional, Tuple
VISUAL_FIELD_ALIASES: Dict[(str, str)] = {
    'style': 'Style',
    'technique': 'Technique',
    'colors': 'Colors',
    'color': 'Colors',
    'lighting': 'Lighting',
    'mood': 'Mood',
    'atmosphere': 'Atmosphere',
    'effects': 'Effects',
    'quality': 'Quality',
    'texture': 'Texture',
    'composition': 'Composition',
    'expressions': 'Expressions',
    'expression': 'Expressions',
    'character design': 'Character design' }
VISUAL_FIELD_ORDER = [
    'Style',
    'Technique',
    'Colors',
    'Lighting',
    'Mood',
    'Atmosphere',
    'Effects',
    'Texture',
    'Quality',
    'Composition',
    'Expressions',
    'Character design']
CONTENT_FIELD_PREFIXES = {
    '소품',
    '인물',
    '캐릭터',
    'shot type',
    'when people appear',
    'era',
    'props',
    'nature',
    'period',
    'costume',
    'setting',
    'subject',
    'activity',
    'clothing',
    'costumes',
    'location',
    'character',
    'background',
    'characters',
    'backgrounds',
    'environment',
    '배경',
    '복장',
    '시대',
    '의상',
    '장소',
    '환경'}
CONTENT_LEAK_TERMS = [
    'historical',
    'modern',
    'futuristic',
    'ancient',
    'medieval',
    'joseon',
    'sageuk',
    'folktale',
    'murim',
    'wuxia',
    'cyberpunk',
    'dystopia',
    'dystopian',
    'megacity',
    'high-tech',
    'high tech',
    'low-life',
    'sci-fi',
    'science fiction',
    'environment',
    'background',
    'setting',
    'location',
    'indoor',
    'outdoor',
    'interior',
    'exterior',
    'city',
    'village',
    'urban',
    'rural',
    'street',
    'palace',
    'temple',
    'hanok',
    'hospital',
    'school',
    'office',
    'apartment',
    'cafe',
    'castle',
    'forest',
    'mountain',
    'battlefield',
    'spacecraft',
    'alien',
    'clothing',
    'costume',
    'hanbok',
    'robe',
    'armor',
    'spacesuit',
    'tech wear',
    'swordsman',
    'martial artist',
    'cultivator',
    '조선',
    '사극',
    '한옥',
    '한복',
    '궁궐',
    '배경',
    '장소',
    '환경',
    '의상',
    '복장',
    '시대',
    '실내',
    '실외']
IMPORTANT_FIELD_NAMES = {
    'important',
    'critical'}

def _normalize_field(field_name = None):
