# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: __init__.pyc (Python 3.11)

from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Dict, Optional, Sequence
from types import Assembly, Runtime, RuntimeInfo
from util import StrOrPath
from util.find import find_dotnet_root, find_libmono, find_runtimes
from util.runtime_spec import DotnetCoreRuntimeSpec
__all__ = [
    'get_mono',
    'get_netfx',
    'get_coreclr',
    'find_dotnet_root',
    'find_libmono',
    'find_runtimes',
    'Runtime',
    'Assembly',
    'RuntimeInfo',
    'DotnetCoreRuntimeSpec']

def get_mono(*, config_file, global_config_file, libmono, sgen, debug, jit_options, assembly_dir, config_dir, set_signal_chaining, trace_mask, trace_level):
    '''Get a Mono runtime instance

    :param config_file:
        Path to the domain configuration file
    :param global_config_file:
        Path to the global configuration file to load (defaults to, e.g.,
        ``/etc/mono/config``)
    :param libmono:
        Path to the Mono runtime dll/so/dylib. If this is not specified, we try
        to discover a globally installed instance using :py:func:`find_libmono`
    :param sgen:
        If ``libmono`` is not specified, this is passed to
        :py:func:`find_libmono`
    :param debug:
        Whether to initialise Mono debugging
    :param jit_options:
        "Command line options" passed to Mono\'s ``mono_jit_parse_options``
    :param assembly_dir:
        The base directory for assemblies, passed to ``mono_set_dirs``
    :param config_dir:
        The base directory for configuration files, passed to ``mono_set_dirs``
    :param set_signal_chaining:
        Whether to enable signal chaining, passed to ``mono_set_signal_chaining``.
        If it is enabled, the runtime saves the original signal handlers before
        installing its own, and calls the original ones in the following cases:

        - SIGSEGV/SIGABRT while executing native code
        - SIGPROF
        - SIGFPE
        - SIGQUIT
        - SIGUSR2

        This currently only works on POSIX platforms
    '''
    Mono = Mono
    import mono
    libmono = _maybe_path(libmono)
# WARNING: Decompyle incomplete


def get_coreclr(*, runtime_config, entry_dll, dotnet_root, properties, runtime_spec):
    '''Get a CoreCLR (.NET Core) runtime instance

    The returned ``DotnetCoreRuntime`` also acts as a mapping of the config
    properties. They can be retrieved using the index operator and can be
    written until the runtime is initialized. The runtime is initialized when
    the first function object is retrieved.

    :param runtime_config:
        Path to a ``runtimeconfig.json`` as generated by
        ``dotnet publish``. If this parameter is not given, a temporary runtime
        config will be generated.
    :param entry_dll:
        The path to the entry dll. If this parameter is given, the runtime will
        be initialized using the command line hosting API instead of using the
        runtime config.
    :param dotnet_root:
        The root directory of the .NET Core installation. If this is not
        specified, we try to discover it using :py:func:`find_dotnet_root`.
    :param properties:
        Additional runtime properties. These can also be passed using the
        ``configProperties`` section in the runtime config.
    :param runtime_spec:
        If the ``runtime_config`` is not specified, the concrete runtime to use
        can be controlled by passing this parameter. Possible values can be
        retrieved using :py:func:`find_runtimes`.'''
    DotnetCoreRuntime = DotnetCoreRuntime
    import hostfxr
    dotnet_root = _maybe_path(dotnet_root)
# WARNING: Decompyle incomplete


def get_netfx(*, domain, config_file):
    '''Get a .NET Framework runtime instance

    :param domain:
        Name of the domain to create. If no value is passed, assemblies will be
        loaded into the root domain.
    :param config_file:
        Configuration file to use to initialize the ``AppDomain``. This will
        only be used for non-root-domains as we can not control the
        configuration of the implicitly loaded root domain.
    '''
    NetFx = NetFx
    import netfx
    impl = NetFx(domain = domain, config_file = _maybe_path(config_file))
    return impl


def _maybe_path(p = None):
    pass
# WARNING: Decompyle incomplete
