# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: html.pyc (Python 3.11)

'''
    pygments.formatters.html
    ~~~~~~~~~~~~~~~~~~~~~~~~

    Formatter for HTML output.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
'''
import functools
import os
import sys
import os.path as os
from io import StringIO
from pygments.formatter import Formatter
from pygments.token import Token, Text, STANDARD_TYPES
from pygments.util import get_bool_opt, get_int_opt, get_list_opt

try:
    import ctags
except ImportError:
    ctags = None

__all__ = [
    'HtmlFormatter']
_escape_html_table = {
    ord("'"): '&#39;',
    ord('"'): '&quot;',
    ord('>'): '&gt;',
    ord('<'): '&lt;',
    ord('&'): '&amp;' }

def escape_html(text, table = (_escape_html_table,)):
    '''Escape &, <, > as well as single and double quotes for HTML.'''
    return text.translate(table)


def webify(color):
    if color.startswith('calc') or color.startswith('var'):
        return color
    color = None.upper()
    if len(color) == 6 and color[0] == color[1] and color[2] == color[3] and color[4] == color[5]:
        return f'''#{color[0]}{color[2]}{color[4]}'''
    return f'''{color}'''


def _get_ttype_class(ttype):
    fname = STANDARD_TYPES.get(ttype)
    if fname:
        return fname
    aname = None
# WARNING: Decompyle incomplete

CSSFILE_TEMPLATE = '/*\ngenerated by Pygments <https://pygments.org/>\nCopyright 2006-2025 by the Pygments team.\nLicensed under the BSD license, see LICENSE for details.\n*/\n%(styledefs)s\n'
DOC_HEADER = '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"\n   "http://www.w3.org/TR/html4/strict.dtd">\n<!--\ngenerated by Pygments <https://pygments.org/>\nCopyright 2006-2025 by the Pygments team.\nLicensed under the BSD license, see LICENSE for details.\n-->\n<html>\n<head>\n  <title>%(title)s</title>\n  <meta http-equiv="content-type" content="text/html; charset=%(encoding)s">\n  <style type="text/css">\n' + CSSFILE_TEMPLATE + '\n  </style>\n</head>\n<body>\n<h2>%(title)s</h2>\n\n'
DOC_HEADER_EXTERNALCSS = '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"\n   "http://www.w3.org/TR/html4/strict.dtd">\n\n<html>\n<head>\n  <title>%(title)s</title>\n  <meta http-equiv="content-type" content="text/html; charset=%(encoding)s">\n  <link rel="stylesheet" href="%(cssfile)s" type="text/css">\n</head>\n<body>\n<h2>%(title)s</h2>\n\n'
DOC_FOOTER = '</body>\n</html>\n'

class HtmlFormatter(Formatter):
    '''
    Format tokens as HTML 4 ``<span>`` tags. By default, the content is enclosed
    in a ``<pre>`` tag, itself wrapped in a ``<div>`` tag (but see the `nowrap` option).
    The ``<div>``\'s CSS class can be set by the `cssclass` option.

    If the `linenos` option is set to ``"table"``, the ``<pre>`` is
    additionally wrapped inside a ``<table>`` which has one row and two
    cells: one containing the line numbers and one containing the code.
    Example:

    .. sourcecode:: html

        <div class="highlight" >
        <table><tr>
          <td class="linenos" title="click to toggle"
            onclick="with (this.firstChild.style)
                     { display = (display == \'\') ? \'none\' : \'\' }">
            <pre>1
            2</pre>
          </td>
          <td class="code">
            <pre><span class="Ke">def </span><span class="NaFu">foo</span>(bar):
              <span class="Ke">pass</span>
            </pre>
          </td>
        </tr></table></div>

    (whitespace added to improve clarity).

    A list of lines can be specified using the `hl_lines` option to make these
    lines highlighted (as of Pygments 0.11).

    With the `full` option, a complete HTML 4 document is output, including
    the style definitions inside a ``<style>`` tag, or in a separate file if
    the `cssfile` option is given.

    When `tagsfile` is set to the path of a ctags index file, it is used to
    generate hyperlinks from names to their definition.  You must enable
    `lineanchors` and run ctags with the `-n` option for this to work.  The
    `python-ctags` module from PyPI must be installed to use this feature;
    otherwise a `RuntimeError` will be raised.

    The `get_style_defs(arg=\'\')` method of a `HtmlFormatter` returns a string
    containing CSS rules for the CSS classes used by the formatter. The
    argument `arg` can be used to specify additional CSS selectors that
    are prepended to the classes. A call `fmter.get_style_defs(\'td .code\')`
    would result in the following CSS classes:

    .. sourcecode:: css

        td .code .kw { font-weight: bold; color: #00FF00 }
        td .code .cm { color: #999999 }
        ...

    If you have Pygments 0.6 or higher, you can also pass a list or tuple to the
    `get_style_defs()` method to request multiple prefixes for the tokens:

    .. sourcecode:: python

        formatter.get_style_defs([\'div.syntax pre\', \'pre.syntax\'])

    The output would then look like this:

    .. sourcecode:: css

        div.syntax pre .kw,
        pre.syntax .kw { font-weight: bold; color: #00FF00 }
        div.syntax pre .cm,
        pre.syntax .cm { color: #999999 }
        ...

    Additional options accepted:

    `nowrap`
        If set to ``True``, don\'t add a ``<pre>`` and a ``<div>`` tag
        around the tokens. This disables most other options (default: ``False``).

    `full`
        Tells the formatter to output a "full" document, i.e. a complete
        self-contained document (default: ``False``).

    `title`
        If `full` is true, the title that should be used to caption the
        document (default: ``\'\'``).

    `style`
        The style to use, can be a string or a Style subclass (default:
        ``\'default\'``). This option has no effect if the `cssfile`
        and `noclobber_cssfile` option are given and the file specified in
        `cssfile` exists.

    `noclasses`
        If set to true, token ``<span>`` tags (as well as line number elements)
        will not use CSS classes, but inline styles. This is not recommended
        for larger pieces of code since it increases output size by quite a bit
        (default: ``False``).

    `classprefix`
        Since the token types use relatively short class names, they may clash
        with some of your own class names. In this case you can use the
        `classprefix` option to give a string to prepend to all Pygments-generated
        CSS class names for token types.
        Note that this option also affects the output of `get_style_defs()`.

    `cssclass`
        CSS class for the wrapping ``<div>`` tag (default: ``\'highlight\'``).
        If you set this option, the default selector for `get_style_defs()`
        will be this class.

        .. versionadded:: 0.9
           If you select the ``\'table\'`` line numbers, the wrapping table will
           have a CSS class of this string plus ``\'table\'``, the default is
           accordingly ``\'highlighttable\'``.

    `cssstyles`
        Inline CSS styles for the wrapping ``<div>`` tag (default: ``\'\'``).

    `prestyles`
        Inline CSS styles for the ``<pre>`` tag (default: ``\'\'``).

        .. versionadded:: 0.11

    `cssfile`
        If the `full` option is true and this option is given, it must be the
        name of an external file. If the filename does not include an absolute
        path, the file\'s path will be assumed to be relative to the main output
        file\'s path, if the latter can be found. The stylesheet is then written
        to this file instead of the HTML file.

        .. versionadded:: 0.6

    `noclobber_cssfile`
        If `cssfile` is given and the specified file exists, the css file will
        not be overwritten. This allows the use of the `full` option in
        combination with a user specified css file. Default is ``False``.

        .. versionadded:: 1.1

    `linenos`
        If set to ``\'table\'``, output line numbers as a table with two cells,
        one containing the line numbers, the other the whole code.  This is
        copy-and-paste-friendly, but may cause alignment problems with some
        browsers or fonts.  If set to ``\'inline\'``, the line numbers will be
        integrated in the ``<pre>`` tag that contains the code (that setting
        is *new in Pygments 0.8*).

        For compatibility with Pygments 0.7 and earlier, every true value
        except ``\'inline\'`` means the same as ``\'table\'`` (in particular, that
        means also ``True``).

        The default value is ``False``, which means no line numbers at all.

        **Note:** with the default ("table") line number mechanism, the line
        numbers and code can have different line heights in Internet Explorer
        unless you give the enclosing ``<pre>`` tags an explicit ``line-height``
        CSS property (you get the default line spacing with ``line-height:
        125%``).

    `hl_lines`
        Specify a list of lines to be highlighted. The line numbers are always
        relative to the input (i.e. the first line is line 1) and are
        independent of `linenostart`.

        .. versionadded:: 0.11

    `linenostart`
        The line number for the first line (default: ``1``).

    `linenostep`
        If set to a number n > 1, only every nth line number is printed.

    `linenospecial`
        If set to a number n > 0, every nth line number is given the CSS
        class ``"special"`` (default: ``0``).

    `nobackground`
        If set to ``True``, the formatter won\'t output the background color
        for the wrapping element (this automatically defaults to ``False``
        when there is no wrapping element [eg: no argument for the
        `get_syntax_defs` method given]) (default: ``False``).

        .. versionadded:: 0.6

    `lineseparator`
        This string is output between lines of code. It defaults to ``"\\n"``,
        which is enough to break a line inside ``<pre>`` tags, but you can
        e.g. set it to ``"<br>"`` to get HTML line breaks.

        .. versionadded:: 0.7

    `lineanchors`
        If set to a nonempty string, e.g. ``foo``, the formatter will wrap each
        output line in an anchor tag with an ``id`` (and `name`) of ``foo-linenumber``.
        This allows easy linking to certain lines.

        .. versionadded:: 0.9

    `linespans`
        If set to a nonempty string, e.g. ``foo``, the formatter will wrap each
        output line in a span tag with an ``id`` of ``foo-linenumber``.
        This allows easy access to lines via javascript.

        .. versionadded:: 1.6

    `anchorlinenos`
        If set to `True`, will wrap line numbers in <a> tags. Used in
        combination with `linenos` and `lineanchors`.

    `tagsfile`
        If set to the path of a ctags file, wrap names in anchor tags that
        link to their definitions. `lineanchors` should be used, and the
        tags file should specify line numbers (see the `-n` option to ctags).
        The tags file is assumed to be encoded in UTF-8.

        .. versionadded:: 1.6

    `tagurlformat`
        A string formatting pattern used to generate links to ctags definitions.
        Available variables are `%(path)s`, `%(fname)s` and `%(fext)s`.
        Defaults to an empty string, resulting in just `#prefix-number` links.

        .. versionadded:: 1.6

    `filename`
        A string used to generate a filename when rendering ``<pre>`` blocks,
        for example if displaying source code. If `linenos` is set to
        ``\'table\'`` then the filename will be rendered in an initial row
        containing a single `<th>` which spans both columns.

        .. versionadded:: 2.1

    `wrapcode`
        Wrap the code inside ``<pre>`` blocks using ``<code>``, as recommended
        by the HTML5 specification.

        .. versionadded:: 2.4

    `debug_token_types`
        Add ``title`` attributes to all token ``<span>`` tags that show the
        name of the token.

        .. versionadded:: 2.10


    **Subclassing the HTML formatter**

    .. versionadded:: 0.7

    The HTML formatter is now built in a way that allows easy subclassing, thus
    customizing the output HTML code. The `format()` method calls
    `self._format_lines()` which returns a generator that yields tuples of ``(1,
    line)``, where the ``1`` indicates that the ``line`` is a line of the
    formatted source code.

    If the `nowrap` option is set, the generator is the iterated over and the
    resulting HTML is output.

    Otherwise, `format()` calls `self.wrap()`, which wraps the generator with
    other generators. These may add some HTML code to the one generated by
    `_format_lines()`, either by modifying the lines generated by the latter,
    then yielding them again with ``(1, line)``, and/or by yielding other HTML
    code before or after the lines, with ``(0, html)``. The distinction between
    source lines and other code makes it possible to wrap the generator multiple
    times.

    The default `wrap()` implementation adds a ``<div>`` and a ``<pre>`` tag.

    A custom `HtmlFormatter` subclass could look like this:

    .. sourcecode:: python

        class CodeHtmlFormatter(HtmlFormatter):

            def wrap(self, source, *, include_div):
                return self._wrap_code(source)

            def _wrap_code(self, source):
                yield 0, \'<code>\'
                for i, t in source:
                    if i == 1:
                        # it\'s a line of formatted code
                        t += \'<br>\'
                    yield i, t
                yield 0, \'</code>\'

    This results in wrapping the formatted lines with a ``<code>`` tag, where the
    source lines are broken using ``<br>`` tags.

    After calling `wrap()`, the `format()` method also adds the "line numbers"
    and/or "full document" wrappers if the respective options are set. Then, all
    HTML yielded by the wrapped generator is output.
    '''
    name = 'HTML'
    aliases = [
        'html']
    filenames = [
        '*.html',
        '*.htm']
    
    def __init__(self, **options):
        pass
    # WARNING: Decompyle incomplete

    
    def _get_css_class(self, ttype):
        '''Return the css class of this token type prefixed with
        the classprefix option.'''
        ttypeclass = _get_ttype_class(ttype)
        if ttypeclass:
            return self.classprefix + ttypeclass

    
    def _get_css_classes(self, ttype):
        '''Return the CSS classes of this token type prefixed with the classprefix option.'''
        cls = self._get_css_class(ttype)
    # WARNING: Decompyle incomplete

    
    def _get_css_inline_styles(self, ttype):
        '''Return the inline CSS styles for this token type.'''
        cclass = self.ttype2class.get(ttype)
    # WARNING: Decompyle incomplete

    
    def _create_stylesheet(self):
        t2c = {
            Token: '' }
        self.ttype2class = {
            Token: '' }
        c2s = { }
        self.class2style = { }
        for ttype, ndef in self.style:
            name = self._get_css_class(ttype)
            style = ''
            if ndef['color']:
                style += 'color: {}; '.format(webify(ndef['color']))
            if ndef['bold']:
                style += 'font-weight: bold; '
            if ndef['italic']:
                style += 'font-style: italic; '
            if ndef['underline']:
                style += 'text-decoration: underline; '
            if ndef['bgcolor']:
                style += 'background-color: {}; '.format(webify(ndef['bgcolor']))
            if ndef['border']:
                style += 'border: 1px solid {}; '.format(webify(ndef['border']))
            if style:
                t2c[ttype] = name
                c2s[name] = (style[:-2], ttype, len(ttype))
            return None

    
    def get_style_defs(self, arg = (None,)):
        '''
        Return CSS style definitions for the classes produced by the current
        highlighting style. ``arg`` can be a string or list of selectors to
        insert before the token type classes.
        '''
        style_lines = []
        style_lines.extend(self.get_linenos_style_defs())
        style_lines.extend(self.get_background_style_defs(arg))
        style_lines.extend(self.get_token_style_defs(arg))
        return '\n'.join(style_lines)

    
    def get_token_style_defs(self, arg = (None,)):
        pass
    # WARNING: Decompyle incomplete

    
    def get_background_style_defs(self, arg = (None,)):
        prefix = self.get_css_prefix(arg)
        bg_color = self.style.background_color
        hl_color = self.style.highlight_color
        lines = []
    # WARNING: Decompyle incomplete

    
    def get_linenos_style_defs(self):
        lines = [
            f'''pre {{ {self._pre_style} }}''',
            f'''td.linenos .normal {{ {self._linenos_style} }}''',
            f'''span.linenos {{ {self._linenos_style} }}''',
            f'''td.linenos .special {{ {self._linenos_special_style} }}''',
            f'''span.linenos.special {{ {self._linenos_special_style} }}''']
        return lines

    
    def get_css_prefix(self, arg):
        pass
    # WARNING: Decompyle incomplete

    _pre_style = (lambda self: 'line-height: 125%;')()
    _linenos_style = (lambda self: color = self.style.line_number_colorbackground_color = self.style.line_number_background_colorf'''color: {color}; background-color: {background_color}; padding-left: 5px; padding-right: 5px;''')()
    _linenos_special_style = (lambda self: color = self.style.line_number_special_colorbackground_color = self.style.line_number_special_background_colorf'''color: {color}; background-color: {background_color}; padding-left: 5px; padding-right: 5px;''')()
    
    def _decodeifneeded(self, value):
        if isinstance(value, bytes):
            if self.encoding:
                return value.decode(self.encoding)
            return None.decode()

    
    def _wrap_full(self, inner, outfile):
        pass
    # WARNING: Decompyle incomplete

    
    def _wrap_tablelinenos(self, inner):
        pass
    # WARNING: Decompyle incomplete

    
    def _wrap_inlinelinenos(self, inner):
        pass
    # WARNING: Decompyle incomplete

    
    def _wrap_lineanchors(self, inner):
        pass
    # WARNING: Decompyle incomplete

    
    def _wrap_linespans(self, inner):
        pass
    # WARNING: Decompyle incomplete

    
    def _wrap_div(self, inner):
        pass
    # WARNING: Decompyle incomplete

    
    def _wrap_pre(self, inner):
        pass
    # WARNING: Decompyle incomplete

    
    def _wrap_code(self, inner):
        pass
    # WARNING: Decompyle incomplete

    _translate_parts = (lambda self, value: value.translate(_escape_html_table).split('\n'))()
    
    def _format_lines(self, tokensource):
        '''
        Just format the tokens, without any wrapping tags.
        Yield individual lines.
        '''
        pass
    # WARNING: Decompyle incomplete

    
    def _lookup_ctag(self, token):
        entry = ctags.TagEntry()
        if self._ctags.find(entry, token.encode(), 0):
            return (entry['file'].decode(), entry['lineNumber'])

    
    def _highlight_lines(self, tokensource):
        '''
        Highlighted the lines specified in the `hl_lines` option by
        post-processing the token stream coming from `_format_lines`.
        '''
        pass
    # WARNING: Decompyle incomplete

    
    def wrap(self, source):
        '''
        Wrap the ``source``, which is a generator yielding
        individual lines, in custom generators. See docstring
        for `format`. Can be overridden.
        '''
        output = source
        if self.wrapcode:
            output = self._wrap_code(output)
        output = self._wrap_pre(output)
        return output

    
    def format_unencoded(self, tokensource, outfile):
        '''
        The formatting process uses several nested generators; which of
        them are used is determined by the user\'s options.

        Each generator should take at least one argument, ``inner``,
        and wrap the pieces of text generated by this.

        Always yield 2-tuples: (code, text). If "code" is 1, the text
        is part of the original tokensource being highlighted, if it\'s
        0, the text is some piece of wrapping. This makes it possible to
        use several different wrappers that process the original source
        linewise, e.g. line number generators.
        '''
        source = self._format_lines(tokensource)
        if self.nowrap and self.linenos == 2:
            source = self._wrap_inlinelinenos(source)
        if self.hl_lines:
            source = self._highlight_lines(source)
        if not self.nowrap:
            if self.lineanchors:
                source = self._wrap_lineanchors(source)
            if self.linespans:
                source = self._wrap_linespans(source)
            source = self.wrap(source)
            if self.linenos == 1:
                source = self._wrap_tablelinenos(source)
            source = self._wrap_div(source)
            if self.full:
                source = self._wrap_full(source, outfile)
        for t, piece in source:
            outfile.write(piece)
            return None
