# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: chat_completion_message.pyc (Python 3.11)

from typing import List, Optional
from typing_extensions import Literal
from _models import BaseModel
from chat_completion_audio import ChatCompletionAudio
from chat_completion_message_tool_call import ChatCompletionMessageToolCallUnion
__all__ = [
    'ChatCompletionMessage',
    'Annotation',
    'AnnotationURLCitation',
    'FunctionCall']

class AnnotationURLCitation(BaseModel):
    url: str = 'A URL citation when using web search.'


class Annotation(BaseModel):
    url_citation: AnnotationURLCitation = 'A URL citation when using web search.'


class FunctionCall(BaseModel):
    name: str = 'Deprecated and replaced by `tool_calls`.\n\n    The name and arguments of a function that should be called, as generated by the model.\n    '


class ChatCompletionMessage(BaseModel):
    '''A chat completion message generated by the model.'''
    content: Optional[str] = None
    role: Literal['assistant'] = None
    annotations: Optional[List[Annotation]] = None
    audio: Optional[ChatCompletionAudio] = None
    function_call: Optional[FunctionCall] = None
    tool_calls: Optional[List[ChatCompletionMessageToolCallUnion]] = None
