# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: chat_completion_chunk.pyc (Python 3.11)

from typing import List, Optional
from typing_extensions import Literal
from _models import BaseModel
from completion_usage import CompletionUsage
from chat_completion_token_logprob import ChatCompletionTokenLogprob
__all__ = [
    'ChatCompletionChunk',
    'Choice',
    'ChoiceDelta',
    'ChoiceDeltaFunctionCall',
    'ChoiceDeltaToolCall',
    'ChoiceDeltaToolCallFunction',
    'ChoiceLogprobs']

class ChoiceDeltaFunctionCall(BaseModel):
    '''Deprecated and replaced by `tool_calls`.

    The name and arguments of a function that should be called, as generated by the model.
    '''
    arguments: Optional[str] = None
    name: Optional[str] = None


class ChoiceDeltaToolCallFunction(BaseModel):
    arguments: Optional[str] = None
    name: Optional[str] = None


class ChoiceDeltaToolCall(BaseModel):
    index: int = 'ChoiceDeltaToolCall'
    id: Optional[str] = None
    function: Optional[ChoiceDeltaToolCallFunction] = None
    type: Optional[Literal['function']] = None


class ChoiceDelta(BaseModel):
    '''A chat completion delta generated by streamed model responses.'''
    content: Optional[str] = None
    function_call: Optional[ChoiceDeltaFunctionCall] = None
    refusal: Optional[str] = None
    role: Optional[Literal[('developer', 'system', 'user', 'assistant', 'tool')]] = None
    tool_calls: Optional[List[ChoiceDeltaToolCall]] = None


class ChoiceLogprobs(BaseModel):
    '''Log probability information for the choice.'''
    content: Optional[List[ChatCompletionTokenLogprob]] = None
    refusal: Optional[List[ChatCompletionTokenLogprob]] = None


class Choice(BaseModel):
    delta: ChoiceDelta = 'Choice'
    index: int = None
    logprobs: Optional[ChoiceLogprobs] = None


class ChatCompletionChunk(BaseModel):
    object: Literal['chat.completion.chunk'] = '\n    Represents a streamed chunk of a chat completion response returned\n    by the model, based on the provided input.\n    [Learn more](https://platform.openai.com/docs/guides/streaming-responses).\n    '
    service_tier: Optional[Literal[('auto', 'default', 'flex', 'scale', 'priority')]] = None
    system_fingerprint: Optional[str] = None
    usage: Optional[CompletionUsage] = None
