# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: chat_completion_store_message.pyc (Python 3.11)

from typing import List, Union, Optional
from typing_extensions import TypeAlias
from chat_completion_message import ChatCompletionMessage
from chat_completion_content_part_text import ChatCompletionContentPartText
from chat_completion_content_part_image import ChatCompletionContentPartImage
__all__ = [
    'ChatCompletionStoreMessage',
    'ChatCompletionStoreMessageContentPart']
ChatCompletionStoreMessageContentPart: TypeAlias = Union[(ChatCompletionContentPartText, ChatCompletionContentPartImage)]

class ChatCompletionStoreMessage(ChatCompletionMessage):
    id: str = 'A chat completion message generated by the model.'
    content_parts: Optional[List[ChatCompletionStoreMessageContentPart]] = None
