# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: chat_completion_assistant_message_param.pyc (Python 3.11)

from __future__ import annotations
from typing import Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict
from chat_completion_content_part_text_param import ChatCompletionContentPartTextParam
from chat_completion_content_part_refusal_param import ChatCompletionContentPartRefusalParam
from chat_completion_message_tool_call_union_param import ChatCompletionMessageToolCallUnionParam
__all__ = [
    'ChatCompletionAssistantMessageParam',
    'Audio',
    'ContentArrayOfContentPart',
    'FunctionCall']

def Audio():
    '''Audio'''
    id: 'Required[str]' = '\n    Data about a previous audio response from the model.\n    [Learn more](https://platform.openai.com/docs/guides/audio).\n    '

Audio = <NODE:27>(Audio, 'Audio', TypedDict, total = False)
ContentArrayOfContentPart: 'TypeAlias' = Union[(ChatCompletionContentPartTextParam, ChatCompletionContentPartRefusalParam)]

def FunctionCall():
    '''FunctionCall'''
    name: 'Required[str]' = 'Deprecated and replaced by `tool_calls`.\n\n    The name and arguments of a function that should be called, as generated by the model.\n    '

FunctionCall = <NODE:27>(FunctionCall, 'FunctionCall', TypedDict, total = False)

def ChatCompletionAssistantMessageParam():
    '''ChatCompletionAssistantMessageParam'''
    tool_calls: 'Iterable[ChatCompletionMessageToolCallUnionParam]' = 'Messages sent by the model in response to user messages.'

ChatCompletionAssistantMessageParam = <NODE:27>(ChatCompletionAssistantMessageParam, 'ChatCompletionAssistantMessageParam', TypedDict, total = False)
