# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: dimension_definitions.pyc (Python 3.11)

from sympy.physics.units import Dimension
angle = Dimension(name = 'angle')
length = Dimension(name = 'length', symbol = 'L')
mass = Dimension(name = 'mass', symbol = 'M')
time = Dimension(name = 'time', symbol = 'T')
current = Dimension(name = 'current', symbol = 'I')
temperature = Dimension('temperature', 'T')
amount_of_substance = Dimension('amount_of_substance')
luminous_intensity = Dimension('luminous_intensity')
velocity = Dimension(name = 'velocity')
acceleration = Dimension(name = 'acceleration')
momentum = Dimension(name = 'momentum')
force = Dimension(name = 'force', symbol = 'F')
energy = Dimension(name = 'energy', symbol = 'E')
power = Dimension(name = 'power')
pressure = Dimension(name = 'pressure')
frequency = Dimension(name = 'frequency', symbol = 'f')
action = Dimension(name = 'action', symbol = 'A')
area = Dimension('area')
volume = Dimension('volume')
voltage = Dimension(name = 'voltage', symbol = 'U')
impedance = Dimension(name = 'impedance', symbol = 'Z')
conductance = Dimension(name = 'conductance', symbol = 'G')
capacitance = Dimension(name = 'capacitance')
inductance = Dimension(name = 'inductance')
charge = Dimension(name = 'charge', symbol = 'Q')
magnetic_density = Dimension(name = 'magnetic_density', symbol = 'B')
magnetic_flux = Dimension(name = 'magnetic_flux')
information = Dimension(name = 'information')
