# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: unit_definitions.pyc (Python 3.11)

from sympy.physics.units.definitions.dimension_definitions import current, temperature, amount_of_substance, luminous_intensity, angle, charge, voltage, impedance, conductance, capacitance, inductance, magnetic_density, magnetic_flux, information
from sympy.core.numbers import Rational, pi
from sympy.core.singleton import S as S_singleton
from sympy.physics.units.prefixes import kilo, mega, milli, micro, deci, centi, nano, pico, kibi, mebi, gibi, tebi, pebi, exbi
from sympy.physics.units.quantities import PhysicalConstant, Quantity
One = S_singleton.One
percent = Quantity('percent', latex_repr = '\\%')
percents = Quantity('percent', latex_repr = '\\%')
percent.set_global_relative_scale_factor(Rational(1, 100), One)
permille = Quantity('permille')
permille.set_global_relative_scale_factor(Rational(1, 1000), One)
rad = Quantity('radian', abbrev = 'rad')
radian = Quantity('radian', abbrev = 'rad')
radians = Quantity('radian', abbrev = 'rad')
radian.set_global_dimension(angle)
deg = Quantity('degree', abbrev = 'deg', latex_repr = '^\\circ')
degree = Quantity('degree', abbrev = 'deg', latex_repr = '^\\circ')
degrees = Quantity('degree', abbrev = 'deg', latex_repr = '^\\circ')
degree.set_global_relative_scale_factor(pi / 180, radian)
sr = Quantity('steradian', abbrev = 'sr')
steradian = Quantity('steradian', abbrev = 'sr')
steradians = Quantity('steradian', abbrev = 'sr')
mil = Quantity('angular_mil', abbrev = 'mil')
angular_mil = Quantity('angular_mil', abbrev = 'mil')
angular_mils = Quantity('angular_mil', abbrev = 'mil')
m = Quantity('meter', abbrev = 'm')
meter = Quantity('meter', abbrev = 'm')
meters = Quantity('meter', abbrev = 'm')
g = Quantity('gram', abbrev = 'g')
gram = Quantity('gram', abbrev = 'g')
grams = Quantity('gram', abbrev = 'g')
kg = Quantity('kilogram', abbrev = 'kg')
kilogram = Quantity('kilogram', abbrev = 'kg')
kilograms = Quantity('kilogram', abbrev = 'kg')
kg.set_global_relative_scale_factor(kilo, gram)
s = Quantity('second', abbrev = 's')
second = Quantity('second', abbrev = 's')
seconds = Quantity('second', abbrev = 's')
A = Quantity('ampere', abbrev = 'A')
ampere = Quantity('ampere', abbrev = 'A')
amperes = Quantity('ampere', abbrev = 'A')
ampere.set_global_dimension(current)
K = Quantity('kelvin', abbrev = 'K')
kelvin = Quantity('kelvin', abbrev = 'K')
kelvins = Quantity('kelvin', abbrev = 'K')
kelvin.set_global_dimension(temperature)
mol = Quantity('mole', abbrev = 'mol')
mole = Quantity('mole', abbrev = 'mol')
moles = Quantity('mole', abbrev = 'mol')
mole.set_global_dimension(amount_of_substance)
cd = Quantity('candela', abbrev = 'cd')
candela = Quantity('candela', abbrev = 'cd')
candelas = Quantity('candela', abbrev = 'cd')
candela.set_global_dimension(luminous_intensity)
newton = Quantity('newton', abbrev = 'N')
newtons = Quantity('newton', abbrev = 'N')
N = Quantity('newton', abbrev = 'N')
kilonewton = Quantity('kilonewton', abbrev = 'kN')
kilonewtons = Quantity('kilonewton', abbrev = 'kN')
kN = Quantity('kilonewton', abbrev = 'kN')
kilonewton.set_global_relative_scale_factor(kilo, newton)
meganewton = Quantity('meganewton', abbrev = 'MN')
meganewtons = Quantity('meganewton', abbrev = 'MN')
MN = Quantity('meganewton', abbrev = 'MN')
meganewton.set_global_relative_scale_factor(mega, newton)
joule = Quantity('joule', abbrev = 'J')
joules = Quantity('joule', abbrev = 'J')
J = Quantity('joule', abbrev = 'J')
watt = Quantity('watt', abbrev = 'W')
watts = Quantity('watt', abbrev = 'W')
W = Quantity('watt', abbrev = 'W')
pascal = Quantity('pascal', abbrev = 'Pa')
pascals = Quantity('pascal', abbrev = 'Pa')
Pa = Quantity('pascal', abbrev = 'Pa')
pa = Quantity('pascal', abbrev = 'Pa')
hertz = Quantity('hertz', abbrev = 'Hz')
hz = Quantity('hertz', abbrev = 'Hz')
Hz = Quantity('hertz', abbrev = 'Hz')
dyne = Quantity('dyne')
dyne.set_global_relative_scale_factor(One / 100000, newton)
erg = Quantity('erg')
erg.set_global_relative_scale_factor(One / 10000000, joule)
coulomb = Quantity('coulomb', abbrev = 'C')
coulombs = Quantity('coulomb', abbrev = 'C')
C = Quantity('coulomb', abbrev = 'C')
coulomb.set_global_dimension(charge)
volt = Quantity('volt', abbrev = 'V')
volts = Quantity('volt', abbrev = 'V')
v = Quantity('volt', abbrev = 'V')
V = Quantity('volt', abbrev = 'V')
volt.set_global_dimension(voltage)
ohm = Quantity('ohm', abbrev = 'ohm', latex_repr = '\\Omega')
ohms = Quantity('ohm', abbrev = 'ohm', latex_repr = '\\Omega')
ohm.set_global_dimension(impedance)
siemens = Quantity('siemens', abbrev = 'S')
S = Quantity('siemens', abbrev = 'S')
mho = Quantity('siemens', abbrev = 'S')
mhos = Quantity('siemens', abbrev = 'S')
siemens.set_global_dimension(conductance)
farad = Quantity('farad', abbrev = 'F')
farads = Quantity('farad', abbrev = 'F')
F = Quantity('farad', abbrev = 'F')
farad.set_global_dimension(capacitance)
henry = Quantity('henry', abbrev = 'H')
henrys = Quantity('henry', abbrev = 'H')
H = Quantity('henry', abbrev = 'H')
henry.set_global_dimension(inductance)
tesla = Quantity('tesla', abbrev = 'T')
teslas = Quantity('tesla', abbrev = 'T')
T = Quantity('tesla', abbrev = 'T')
tesla.set_global_dimension(magnetic_density)
weber = Quantity('weber', abbrev = 'Wb')
webers = Quantity('weber', abbrev = 'Wb')
Wb = Quantity('weber', abbrev = 'Wb')
wb = Quantity('weber', abbrev = 'Wb')
weber.set_global_dimension(magnetic_flux)
statampere = Quantity('statampere')
statcoulomb = Quantity('statcoulomb', abbrev = 'statC')
statC = Quantity('statcoulomb', abbrev = 'statC')
franklin = Quantity('statcoulomb', abbrev = 'statC')
statvolt = Quantity('statvolt')
gauss = Quantity('gauss')
maxwell = Quantity('maxwell')
debye = Quantity('debye')
oersted = Quantity('oersted')
optical_power = Quantity('dioptre')
dioptre = Quantity('dioptre')
diopter = Quantity('dioptre')
D = Quantity('dioptre')
lux = Quantity('lux', abbrev = 'lx')
lx = Quantity('lux', abbrev = 'lx')
katal = Quantity('katal', abbrev = 'kat')
kat = Quantity('katal', abbrev = 'kat')
gray = Quantity('gray')
Gy = Quantity('gray')
becquerel = Quantity('becquerel', abbrev = 'Bq')
Bq = Quantity('becquerel', abbrev = 'Bq')
mg = Quantity('milligram', abbrev = 'mg')
milligram = Quantity('milligram', abbrev = 'mg')
milligrams = Quantity('milligram', abbrev = 'mg')
mg.set_global_relative_scale_factor(milli, gram)
ug = Quantity('microgram', abbrev = 'ug', latex_repr = '\\mu\\text{g}')
microgram = Quantity('microgram', abbrev = 'ug', latex_repr = '\\mu\\text{g}')
micrograms = Quantity('microgram', abbrev = 'ug', latex_repr = '\\mu\\text{g}')
ug.set_global_relative_scale_factor(micro, gram)
Da = PhysicalConstant('atomic_mass_constant')
dalton = PhysicalConstant('atomic_mass_constant')
amu = PhysicalConstant('atomic_mass_constant')
amus = PhysicalConstant('atomic_mass_constant')
atomic_mass_unit = PhysicalConstant('atomic_mass_constant')
atomic_mass_constant = PhysicalConstant('atomic_mass_constant')
t = Quantity('tonne', abbrev = 't')
metric_ton = Quantity('tonne', abbrev = 't')
tonne = Quantity('tonne', abbrev = 't')
tonne.set_global_relative_scale_factor(mega, gram)
me = Quantity('electron_rest_mass', abbrev = 'me')
electron_rest_mass = Quantity('electron_rest_mass', abbrev = 'me')
km = Quantity('kilometer', abbrev = 'km')
kilometer = Quantity('kilometer', abbrev = 'km')
kilometers = Quantity('kilometer', abbrev = 'km')
km.set_global_relative_scale_factor(kilo, meter)
dm = Quantity('decimeter', abbrev = 'dm')
decimeter = Quantity('decimeter', abbrev = 'dm')
decimeters = Quantity('decimeter', abbrev = 'dm')
dm.set_global_relative_scale_factor(deci, meter)
cm = Quantity('centimeter', abbrev = 'cm')
centimeter = Quantity('centimeter', abbrev = 'cm')
centimeters = Quantity('centimeter', abbrev = 'cm')
cm.set_global_relative_scale_factor(centi, meter)
mm = Quantity('millimeter', abbrev = 'mm')
millimeter = Quantity('millimeter', abbrev = 'mm')
millimeters = Quantity('millimeter', abbrev = 'mm')
mm.set_global_relative_scale_factor(milli, meter)
um = Quantity('micrometer', abbrev = 'um', latex_repr = '\\mu\\text{m}')
micrometer = Quantity('micrometer', abbrev = 'um', latex_repr = '\\mu\\text{m}')
micrometers = Quantity('micrometer', abbrev = 'um', latex_repr = '\\mu\\text{m}')
micron = Quantity('micrometer', abbrev = 'um', latex_repr = '\\mu\\text{m}')
microns = Quantity('micrometer', abbrev = 'um', latex_repr = '\\mu\\text{m}')
um.set_global_relative_scale_factor(micro, meter)
nm = Quantity('nanometer', abbrev = 'nm')
nanometer = Quantity('nanometer', abbrev = 'nm')
nanometers = Quantity('nanometer', abbrev = 'nm')
nm.set_global_relative_scale_factor(nano, meter)
pm = Quantity('picometer', abbrev = 'pm')
picometer = Quantity('picometer', abbrev = 'pm')
picometers = Quantity('picometer', abbrev = 'pm')
pm.set_global_relative_scale_factor(pico, meter)
ft = Quantity('foot', abbrev = 'ft')
foot = Quantity('foot', abbrev = 'ft')
feet = Quantity('foot', abbrev = 'ft')
ft.set_global_relative_scale_factor(Rational(3048, 10000), meter)
inch = Quantity('inch')
inches = Quantity('inch')
inch.set_global_relative_scale_factor(Rational(1, 12), foot)
yd = Quantity('yard', abbrev = 'yd')
yard = Quantity('yard', abbrev = 'yd')
yards = Quantity('yard', abbrev = 'yd')
yd.set_global_relative_scale_factor(3, feet)
mi = Quantity('mile')
mile = Quantity('mile')
miles = Quantity('mile')
mi.set_global_relative_scale_factor(5280, feet)
nmi = Quantity('nautical_mile')
nautical_mile = Quantity('nautical_mile')
nautical_miles = Quantity('nautical_mile')
nmi.set_global_relative_scale_factor(6076, feet)
angstrom = Quantity('angstrom', latex_repr = '\\r{A}')
angstroms = Quantity('angstrom', latex_repr = '\\r{A}')
angstrom.set_global_relative_scale_factor(Rational(1, 0x2540BE400), meter)
ha = Quantity('hectare', abbrev = 'ha')
hectare = Quantity('hectare', abbrev = 'ha')
l = Quantity('liter', abbrev = 'l')
L = Quantity('liter', abbrev = 'l')
liter = Quantity('liter', abbrev = 'l')
liters = Quantity('liter', abbrev = 'l')
dl = Quantity('deciliter', abbrev = 'dl')
dL = Quantity('deciliter', abbrev = 'dl')
deciliter = Quantity('deciliter', abbrev = 'dl')
deciliters = Quantity('deciliter', abbrev = 'dl')
dl.set_global_relative_scale_factor(Rational(1, 10), liter)
cl = Quantity('centiliter', abbrev = 'cl')
cL = Quantity('centiliter', abbrev = 'cl')
centiliter = Quantity('centiliter', abbrev = 'cl')
centiliters = Quantity('centiliter', abbrev = 'cl')
cl.set_global_relative_scale_factor(Rational(1, 100), liter)
ml = Quantity('milliliter', abbrev = 'ml')
mL = Quantity('milliliter', abbrev = 'ml')
milliliter = Quantity('milliliter', abbrev = 'ml')
milliliters = Quantity('milliliter', abbrev = 'ml')
ml.set_global_relative_scale_factor(Rational(1, 1000), liter)
ms = Quantity('millisecond', abbrev = 'ms')
millisecond = Quantity('millisecond', abbrev = 'ms')
milliseconds = Quantity('millisecond', abbrev = 'ms')
millisecond.set_global_relative_scale_factor(milli, second)
us = Quantity('microsecond', abbrev = 'us', latex_repr = '\\mu\\text{s}')
microsecond = Quantity('microsecond', abbrev = 'us', latex_repr = '\\mu\\text{s}')
microseconds = Quantity('microsecond', abbrev = 'us', latex_repr = '\\mu\\text{s}')
microsecond.set_global_relative_scale_factor(micro, second)
ns = Quantity('nanosecond', abbrev = 'ns')
nanosecond = Quantity('nanosecond', abbrev = 'ns')
nanoseconds = Quantity('nanosecond', abbrev = 'ns')
nanosecond.set_global_relative_scale_factor(nano, second)
ps = Quantity('picosecond', abbrev = 'ps')
picosecond = Quantity('picosecond', abbrev = 'ps')
picoseconds = Quantity('picosecond', abbrev = 'ps')
picosecond.set_global_relative_scale_factor(pico, second)
minute = Quantity('minute')
minutes = Quantity('minute')
minute.set_global_relative_scale_factor(60, second)
h = Quantity('hour')
hour = Quantity('hour')
hours = Quantity('hour')
hour.set_global_relative_scale_factor(60, minute)
day = Quantity('day')
days = Quantity('day')
day.set_global_relative_scale_factor(24, hour)
anomalistic_year = Quantity('anomalistic_year')
anomalistic_years = Quantity('anomalistic_year')
anomalistic_year.set_global_relative_scale_factor(365.26, day)
sidereal_year = Quantity('sidereal_year')
sidereal_years = Quantity('sidereal_year')
sidereal_year.set_global_relative_scale_factor(3.15581e+07, seconds)
tropical_year = Quantity('tropical_year')
tropical_years = Quantity('tropical_year')
tropical_year.set_global_relative_scale_factor(365.242, day)
common_year = Quantity('common_year')
common_years = Quantity('common_year')
common_year.set_global_relative_scale_factor(365, day)
julian_year = Quantity('julian_year')
julian_years = Quantity('julian_year')
julian_year.set_global_relative_scale_factor(365 + One / 4, day)
draconic_year = Quantity('draconic_year')
draconic_years = Quantity('draconic_year')
draconic_year.set_global_relative_scale_factor(346.62, day)
gaussian_year = Quantity('gaussian_year')
gaussian_years = Quantity('gaussian_year')
gaussian_year.set_global_relative_scale_factor(365.257, day)
full_moon_cycle = Quantity('full_moon_cycle')
full_moon_cycles = Quantity('full_moon_cycle')
full_moon_cycle.set_global_relative_scale_factor(411.784, day)
year = tropical_year
years = tropical_year
G = PhysicalConstant('gravitational_constant', abbrev = 'G')
gravitational_constant = PhysicalConstant('gravitational_constant', abbrev = 'G')
c = PhysicalConstant('speed_of_light', abbrev = 'c')
speed_of_light = PhysicalConstant('speed_of_light', abbrev = 'c')
elementary_charge = PhysicalConstant('elementary_charge', abbrev = 'e')
planck = PhysicalConstant('planck', abbrev = 'h')
hbar = PhysicalConstant('hbar', abbrev = 'hbar')
eV = PhysicalConstant('electronvolt', abbrev = 'eV')
electronvolt = PhysicalConstant('electronvolt', abbrev = 'eV')
electronvolts = PhysicalConstant('electronvolt', abbrev = 'eV')
avogadro_number = PhysicalConstant('avogadro_number')
avogadro = PhysicalConstant('avogadro_constant')
avogadro_constant = PhysicalConstant('avogadro_constant')
boltzmann = PhysicalConstant('boltzmann_constant')
boltzmann_constant = PhysicalConstant('boltzmann_constant')
stefan = PhysicalConstant('stefan_boltzmann_constant')
stefan_boltzmann_constant = PhysicalConstant('stefan_boltzmann_constant')
R = PhysicalConstant('molar_gas_constant', abbrev = 'R')
molar_gas_constant = PhysicalConstant('molar_gas_constant', abbrev = 'R')
faraday_constant = PhysicalConstant('faraday_constant')
josephson_constant = PhysicalConstant('josephson_constant', abbrev = 'K_j')
von_klitzing_constant = PhysicalConstant('von_klitzing_constant', abbrev = 'R_k')
gee = PhysicalConstant('acceleration_due_to_gravity', abbrev = 'g')
gees = PhysicalConstant('acceleration_due_to_gravity', abbrev = 'g')
acceleration_due_to_gravity = PhysicalConstant('acceleration_due_to_gravity', abbrev = 'g')
u0 = PhysicalConstant('magnetic_constant')
magnetic_constant = PhysicalConstant('magnetic_constant')
vacuum_permeability = PhysicalConstant('magnetic_constant')
e0 = PhysicalConstant('vacuum_permittivity')
electric_constant = PhysicalConstant('vacuum_permittivity')
vacuum_permittivity = PhysicalConstant('vacuum_permittivity')
Z0 = PhysicalConstant('vacuum_impedance', abbrev = 'Z_0', latex_repr = 'Z_{0}')
vacuum_impedance = PhysicalConstant('vacuum_impedance', abbrev = 'Z_0', latex_repr = 'Z_{0}')
coulomb_constant = PhysicalConstant('coulomb_constant', abbrev = 'k_e')
coulombs_constant = PhysicalConstant('coulomb_constant', abbrev = 'k_e')
electric_force_constant = PhysicalConstant('coulomb_constant', abbrev = 'k_e')
atmosphere = Quantity('atmosphere', abbrev = 'atm')
atmospheres = Quantity('atmosphere', abbrev = 'atm')
atm = Quantity('atmosphere', abbrev = 'atm')
kPa = Quantity('kilopascal', abbrev = 'kPa')
kilopascal = Quantity('kilopascal', abbrev = 'kPa')
kilopascal.set_global_relative_scale_factor(kilo, Pa)
bar = Quantity('bar', abbrev = 'bar')
bars = Quantity('bar', abbrev = 'bar')
pound = Quantity('pound')
pounds = Quantity('pound')
psi = Quantity('psi')
dHg0 = 13.5951
mmHg = Quantity('mmHg')
torr = Quantity('mmHg')
atmosphere.set_global_relative_scale_factor(101325, pascal)
bar.set_global_relative_scale_factor(100, kPa)
pound.set_global_relative_scale_factor(Rational(45359237, 100000000), kg)
mmu = Quantity('milli_mass_unit')
mmus = Quantity('milli_mass_unit')
milli_mass_unit = Quantity('milli_mass_unit')
quart = Quantity('quart')
quarts = Quantity('quart')
ly = Quantity('lightyear', abbrev = 'ly')
lightyear = Quantity('lightyear', abbrev = 'ly')
lightyears = Quantity('lightyear', abbrev = 'ly')
au = Quantity('astronomical_unit', abbrev = 'AU')
astronomical_unit = Quantity('astronomical_unit', abbrev = 'AU')
astronomical_units = Quantity('astronomical_unit', abbrev = 'AU')
planck_mass = Quantity('planck_mass', abbrev = 'm_P', latex_repr = 'm_\\text{P}')
planck_time = Quantity('planck_time', abbrev = 't_P', latex_repr = 't_\\text{P}')
planck_temperature = Quantity('planck_temperature', abbrev = 'T_P', latex_repr = 'T_\\text{P}')
planck_length = Quantity('planck_length', abbrev = 'l_P', latex_repr = 'l_\\text{P}')
planck_charge = Quantity('planck_charge', abbrev = 'q_P', latex_repr = 'q_\\text{P}')
planck_area = Quantity('planck_area')
planck_volume = Quantity('planck_volume')
planck_momentum = Quantity('planck_momentum')
planck_energy = Quantity('planck_energy', abbrev = 'E_P', latex_repr = 'E_\\text{P}')
planck_force = Quantity('planck_force', abbrev = 'F_P', latex_repr = 'F_\\text{P}')
planck_power = Quantity('planck_power', abbrev = 'P_P', latex_repr = 'P_\\text{P}')
planck_density = Quantity('planck_density', abbrev = 'rho_P', latex_repr = '\\rho_\\text{P}')
planck_energy_density = Quantity('planck_energy_density', abbrev = 'rho^E_P')
planck_intensity = Quantity('planck_intensity', abbrev = 'I_P', latex_repr = 'I_\\text{P}')
planck_angular_frequency = Quantity('planck_angular_frequency', abbrev = 'omega_P', latex_repr = '\\omega_\\text{P}')
planck_pressure = Quantity('planck_pressure', abbrev = 'p_P', latex_repr = 'p_\\text{P}')
planck_current = Quantity('planck_current', abbrev = 'I_P', latex_repr = 'I_\\text{P}')
planck_voltage = Quantity('planck_voltage', abbrev = 'V_P', latex_repr = 'V_\\text{P}')
planck_impedance = Quantity('planck_impedance', abbrev = 'Z_P', latex_repr = 'Z_\\text{P}')
planck_acceleration = Quantity('planck_acceleration', abbrev = 'a_P', latex_repr = 'a_\\text{P}')
bit = Quantity('bit')
bits = Quantity('bit')
bit.set_global_dimension(information)
byte = Quantity('byte')
bytes = Quantity('byte')
kibibyte = Quantity('kibibyte')
kibibytes = Quantity('kibibyte')
mebibyte = Quantity('mebibyte')
mebibytes = Quantity('mebibyte')
gibibyte = Quantity('gibibyte')
gibibytes = Quantity('gibibyte')
tebibyte = Quantity('tebibyte')
tebibytes = Quantity('tebibyte')
pebibyte = Quantity('pebibyte')
pebibytes = Quantity('pebibyte')
exbibyte = Quantity('exbibyte')
exbibytes = Quantity('exbibyte')
byte.set_global_relative_scale_factor(8, bit)
kibibyte.set_global_relative_scale_factor(kibi, byte)
mebibyte.set_global_relative_scale_factor(mebi, byte)
gibibyte.set_global_relative_scale_factor(gibi, byte)
tebibyte.set_global_relative_scale_factor(tebi, byte)
pebibyte.set_global_relative_scale_factor(pebi, byte)
exbibyte.set_global_relative_scale_factor(exbi, byte)
curie = Quantity('curie', abbrev = 'Ci')
Ci = Quantity('curie', abbrev = 'Ci')
rutherford = Quantity('rutherford', abbrev = 'Rd')
Rd = Quantity('rutherford', abbrev = 'Rd')
