# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: pascal.pyc (Python 3.11)

'''
    pygments.lexers.pascal
    ~~~~~~~~~~~~~~~~~~~~~~

    Lexers for Pascal family languages.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
'''
import re
from pygments.lexer import Lexer
from pygments.util import get_bool_opt, get_list_opt
from pygments.token import Comment, Operator, Keyword, Name, String, Number, Punctuation, Error, Whitespace
from pygments.scanner import Scanner
from pygments.lexers.modula2 import Modula2Lexer
__all__ = [
    'DelphiLexer',
    'PortugolLexer']

class PortugolLexer(Lexer):
    '''For Portugol, a Pascal dialect with keywords in Portuguese.'''
    name = 'Portugol'
    aliases = [
        'portugol']
    filenames = [
        '*.alg',
        '*.portugol']
    mimetypes = []
    url = 'https://www.apoioinformatica.inf.br/produtos/visualg/linguagem'
    version_added = ''
    
    def __init__(self, **options):
        pass
    # WARNING: Decompyle incomplete

    
    def get_tokens_unprocessed(self, text):
        return self.lexer.get_tokens_unprocessed(text)



class DelphiLexer(Lexer):
    '''
    For Delphi (Borland Object Pascal),
    Turbo Pascal and Free Pascal source code.

    Additional options accepted:

    `turbopascal`
        Highlight Turbo Pascal specific keywords (default: ``True``).
    `delphi`
        Highlight Borland Delphi specific keywords (default: ``True``).
    `freepascal`
        Highlight Free Pascal specific keywords (default: ``True``).
    `units`
        A list of units that should be considered builtin, supported are
        ``System``, ``SysUtils``, ``Classes`` and ``Math``.
        Default is to consider all of them builtin.
    '''
    name = 'Delphi'
    aliases = [
        'delphi',
        'pas',
        'pascal',
        'objectpascal']
    filenames = [
        '*.pas',
        '*.dpr']
    mimetypes = [
        'text/x-pascal']
    url = 'https://www.embarcadero.com/products/delphi'
    version_added = ''
    TURBO_PASCAL_KEYWORDS = ('absolute', 'and', 'array', 'asm', 'begin', 'break', 'case', 'const', 'constructor', 'continue', 'destructor', 'div', 'do', 'downto', 'else', 'end', 'file', 'for', 'function', 'goto', 'if', 'implementation', 'in', 'inherited', 'inline', 'interface', 'label', 'mod', 'nil', 'not', 'object', 'of', 'on', 'operator', 'or', 'packed', 'procedure', 'program', 'record', 'reintroduce', 'repeat', 'self', 'set', 'shl', 'shr', 'string', 'then', 'to', 'type', 'unit', 'until', 'uses', 'var', 'while', 'with', 'xor')
    DELPHI_KEYWORDS = ('as', 'class', 'except', 'exports', 'finalization', 'finally', 'initialization', 'is', 'library', 'on', 'property', 'raise', 'threadvar', 'try')
    FREE_PASCAL_KEYWORDS = ('dispose', 'exit', 'false', 'new', 'true')
    BLOCK_KEYWORDS = {
        'end',
        'var',
        'type',
        'unit',
        'uses',
        'begin',
        'class',
        'const',
        'label',
        'record',
        'library',
        'program',
        'function',
        'operator',
        'property',
        'procedure',
        'threadvar',
        'destructor',
        'constructor',
        'finalization',
        'implementation',
        'initialization'}
    FUNCTION_MODIFIERS = {
        'name',
        'near',
        'alias',
        'cdecl',
        'export',
        'inline',
        'pascal',
        'dynamic',
        'stdcall',
        'varargs',
        'virtual',
        'external',
        'override',
        'register',
        'safecall',
        'assembler',
        'interrupt',
        'softfloat',
        'nostackframe'}
    DIRECTIVES = {
        'far',
        'far16',
        'index',
        'public',
        'cppdecl',
        'default',
        'forward',
        'private',
        'absolute',
        'abstract',
        'assembler',
        'protected',
        'published',
        'oldfpccall'}
    BUILTIN_TYPES = {
        'bool',
        'byte',
        'char',
        'comp',
        'real',
        'word',
        'dword',
        'int64',
        'pbool',
        'pbyte',
        'pchar',
        'pcomp',
        'pdate',
        'pword',
        'tdate',
        'ttime',
        'double',
        'pdword',
        'pint64',
        'real48',
        'single',
        'string',
        'tclass',
        'boolean',
        'integer',
        'longint',
        'pdouble',
        'phandle',
        'pointer',
        'psingle',
        'pstring',
        'thandle',
        'tobject',
        'variant',
        'ansichar',
        'bytebool',
        'cardinal',
        'currency',
        'extended',
        'iunknown',
        'longbool',
        'longword',
        'pboolean',
        'pinteger',
        'plongint',
        'ppointer',
        'pvariant',
        'shortint',
        'smallint',
        'textfile',
        'widechar',
        'wordbool',
        'pansichar',
        'pcardinal',
        'pcurrency',
        'pdatetime',
        'pextended',
        'plongword',
        'pshortint',
        'psmallint',
        'pwidechar',
        'pwordbool',
        'tdatetime',
        'ansistring',
        'pbytearray',
        'pwordarray',
        'widestring',
        'pansistring',
        'pwidestring',
        'shortstring',
        'pshortstring'}
    BUILTIN_UNITS = {
        'System': ('abs', 'acquireexceptionobject', 'addr', 'ansitoutf8', 'append', 'arctan', 'assert', 'assigned', 'assignfile', 'beginthread', 'blockread', 'blockwrite', 'break', 'chdir', 'chr', 'close', 'closefile', 'comptocurrency', 'comptodouble', 'concat', 'continue', 'copy', 'cos', 'dec', 'delete', 'dispose', 'doubletocomp', 'endthread', 'enummodules', 'enumresourcemodules', 'eof', 'eoln', 'erase', 'exceptaddr', 'exceptobject', 'exclude', 'exit', 'exp', 'filepos', 'filesize', 'fillchar', 'finalize', 'findclasshinstance', 'findhinstance', 'findresourcehinstance', 'flush', 'frac', 'freemem', 'get8087cw', 'getdir', 'getlasterror', 'getmem', 'getmemorymanager', 'getmodulefilename', 'getvariantmanager', 'halt', 'hi', 'high', 'inc', 'include', 'initialize', 'insert', 'int', 'ioresult', 'ismemorymanagerset', 'isvariantmanagerset', 'length', 'ln', 'lo', 'low', 'mkdir', 'move', 'new', 'odd', 'olestrtostring', 'olestrtostrvar', 'ord', 'paramcount', 'paramstr', 'pi', 'pos', 'pred', 'ptr', 'pucs4chars', 'random', 'randomize', 'read', 'readln', 'reallocmem', 'releaseexceptionobject', 'rename', 'reset', 'rewrite', 'rmdir', 'round', 'runerror', 'seek', 'seekeof', 'seekeoln', 'set8087cw', 'setlength', 'setlinebreakstyle', 'setmemorymanager', 'setstring', 'settextbuf', 'setvariantmanager', 'sin', 'sizeof', 'slice', 'sqr', 'sqrt', 'str', 'stringofchar', 'stringtoolestr', 'stringtowidechar', 'succ', 'swap', 'trunc', 'truncate', 'typeinfo', 'ucs4stringtowidestring', 'unicodetoutf8', 'uniquestring', 'upcase', 'utf8decode', 'utf8encode', 'utf8toansi', 'utf8tounicode', 'val', 'vararrayredim', 'varclear', 'widecharlentostring', 'widecharlentostrvar', 'widechartostring', 'widechartostrvar', 'widestringtoucs4string', 'write', 'writeln'),
        'SysUtils': ('abort', 'addexitproc', 'addterminateproc', 'adjustlinebreaks', 'allocmem', 'ansicomparefilename', 'ansicomparestr', 'ansicomparetext', 'ansidequotedstr', 'ansiextractquotedstr', 'ansilastchar', 'ansilowercase', 'ansilowercasefilename', 'ansipos', 'ansiquotedstr', 'ansisamestr', 'ansisametext', 'ansistrcomp', 'ansistricomp', 'ansistrlastchar', 'ansistrlcomp', 'ansistrlicomp', 'ansistrlower', 'ansistrpos', 'ansistrrscan', 'ansistrscan', 'ansistrupper', 'ansiuppercase', 'ansiuppercasefilename', 'appendstr', 'assignstr', 'beep', 'booltostr', 'bytetocharindex', 'bytetocharlen', 'bytetype', 'callterminateprocs', 'changefileext', 'charlength', 'chartobyteindex', 'chartobytelen', 'comparemem', 'comparestr', 'comparetext', 'createdir', 'createguid', 'currentyear', 'currtostr', 'currtostrf', 'date', 'datetimetofiledate', 'datetimetostr', 'datetimetostring', 'datetimetosystemtime', 'datetimetotimestamp', 'datetostr', 'dayofweek', 'decodedate', 'decodedatefully', 'decodetime', 'deletefile', 'directoryexists', 'diskfree', 'disksize', 'disposestr', 'encodedate', 'encodetime', 'exceptionerrormessage', 'excludetrailingbackslash', 'excludetrailingpathdelimiter', 'expandfilename', 'expandfilenamecase', 'expanduncfilename', 'extractfiledir', 'extractfiledrive', 'extractfileext', 'extractfilename', 'extractfilepath', 'extractrelativepath', 'extractshortpathname', 'fileage', 'fileclose', 'filecreate', 'filedatetodatetime', 'fileexists', 'filegetattr', 'filegetdate', 'fileisreadonly', 'fileopen', 'fileread', 'filesearch', 'fileseek', 'filesetattr', 'filesetdate', 'filesetreadonly', 'filewrite', 'finalizepackage', 'findclose', 'findcmdlineswitch', 'findfirst', 'findnext', 'floattocurr', 'floattodatetime', 'floattodecimal', 'floattostr', 'floattostrf', 'floattotext', 'floattotextfmt', 'fmtloadstr', 'fmtstr', 'forcedirectories', 'format', 'formatbuf', 'formatcurr', 'formatdatetime', 'formatfloat', 'freeandnil', 'getcurrentdir', 'getenvironmentvariable', 'getfileversion', 'getformatsettings', 'getlocaleformatsettings', 'getmodulename', 'getpackagedescription', 'getpackageinfo', 'gettime', 'guidtostring', 'incamonth', 'includetrailingbackslash', 'includetrailingpathdelimiter', 'incmonth', 'initializepackage', 'interlockeddecrement', 'interlockedexchange', 'interlockedexchangeadd', 'interlockedincrement', 'inttohex', 'inttostr', 'isdelimiter', 'isequalguid', 'isleapyear', 'ispathdelimiter', 'isvalidident', 'languages', 'lastdelimiter', 'loadpackage', 'loadstr', 'lowercase', 'msecstotimestamp', 'newstr', 'nextcharindex', 'now', 'outofmemoryerror', 'quotedstr', 'raiselastoserror', 'raiselastwin32error', 'removedir', 'renamefile', 'replacedate', 'replacetime', 'safeloadlibrary', 'samefilename', 'sametext', 'setcurrentdir', 'showexception', 'sleep', 'stralloc', 'strbufsize', 'strbytetype', 'strcat', 'strcharlength', 'strcomp', 'strcopy', 'strdispose', 'strecopy', 'strend', 'strfmt', 'stricomp', 'stringreplace', 'stringtoguid', 'strlcat', 'strlcomp', 'strlcopy', 'strlen', 'strlfmt', 'strlicomp', 'strlower', 'strmove', 'strnew', 'strnextchar', 'strpas', 'strpcopy', 'strplcopy', 'strpos', 'strrscan', 'strscan', 'strtobool', 'strtobooldef', 'strtocurr', 'strtocurrdef', 'strtodate', 'strtodatedef', 'strtodatetime', 'strtodatetimedef', 'strtofloat', 'strtofloatdef', 'strtoint', 'strtoint64', 'strtoint64def', 'strtointdef', 'strtotime', 'strtotimedef', 'strupper', 'supports', 'syserrormessage', 'systemtimetodatetime', 'texttofloat', 'time', 'timestamptodatetime', 'timestamptomsecs', 'timetostr', 'trim', 'trimleft', 'trimright', 'tryencodedate', 'tryencodetime', 'tryfloattocurr', 'tryfloattodatetime', 'trystrtobool', 'trystrtocurr', 'trystrtodate', 'trystrtodatetime', 'trystrtofloat', 'trystrtoint', 'trystrtoint64', 'trystrtotime', 'unloadpackage', 'uppercase', 'widecomparestr', 'widecomparetext', 'widefmtstr', 'wideformat', 'wideformatbuf', 'widelowercase', 'widesamestr', 'widesametext', 'wideuppercase', 'win32check', 'wraptext'),
        'Classes': ('activateclassgroup', 'allocatehwnd', 'bintohex', 'checksynchronize', 'collectionsequal', 'countgenerations', 'deallocatehwnd', 'equalrect', 'extractstrings', 'findclass', 'findglobalcomponent', 'getclass', 'groupdescendantswith', 'hextobin', 'identtoint', 'initinheritedcomponent', 'inttoident', 'invalidpoint', 'isuniqueglobalcomponentname', 'linestart', 'objectbinarytotext', 'objectresourcetotext', 'objecttexttobinary', 'objecttexttoresource', 'pointsequal', 'readcomponentres', 'readcomponentresex', 'readcomponentresfile', 'rect', 'registerclass', 'registerclassalias', 'registerclasses', 'registercomponents', 'registerintegerconsts', 'registernoicon', 'registernonactivex', 'smallpoint', 'startclassgroup', 'teststreamformat', 'unregisterclass', 'unregisterclasses', 'unregisterintegerconsts', 'unregistermoduleclasses', 'writecomponentresfile'),
        'Math': ('arccos', 'arccosh', 'arccot', 'arccoth', 'arccsc', 'arccsch', 'arcsec', 'arcsech', 'arcsin', 'arcsinh', 'arctan2', 'arctanh', 'ceil', 'comparevalue', 'cosecant', 'cosh', 'cot', 'cotan', 'coth', 'csc', 'csch', 'cycletodeg', 'cycletograd', 'cycletorad', 'degtocycle', 'degtograd', 'degtorad', 'divmod', 'doubledecliningbalance', 'ensurerange', 'floor', 'frexp', 'futurevalue', 'getexceptionmask', 'getprecisionmode', 'getroundmode', 'gradtocycle', 'gradtodeg', 'gradtorad', 'hypot', 'inrange', 'interestpayment', 'interestrate', 'internalrateofreturn', 'intpower', 'isinfinite', 'isnan', 'iszero', 'ldexp', 'lnxp1', 'log10', 'log2', 'logn', 'max', 'maxintvalue', 'maxvalue', 'mean', 'meanandstddev', 'min', 'minintvalue', 'minvalue', 'momentskewkurtosis', 'netpresentvalue', 'norm', 'numberofperiods', 'payment', 'periodpayment', 'poly', 'popnstddev', 'popnvariance', 'power', 'presentvalue', 'radtocycle', 'radtodeg', 'radtograd', 'randg', 'randomrange', 'roundto', 'samevalue', 'sec', 'secant', 'sech', 'setexceptionmask', 'setprecisionmode', 'setroundmode', 'sign', 'simpleroundto', 'sincos', 'sinh', 'slndepreciation', 'stddev', 'sum', 'sumint', 'sumofsquares', 'sumsandsquares', 'syddepreciation', 'tan', 'tanh', 'totalvariance', 'variance') }
    ASM_REGISTERS = {
        'ah',
        'al',
        'ax',
        'bh',
        'bl',
        'bp',
        'bx',
        'ch',
        'cl',
        'cs',
        'cx',
        'dh',
        'di',
        'dl',
        'ds',
        'dx',
        'es',
        'fs',
        'gs',
        'si',
        'sp',
        'ss',
        'cr0',
        'cr1',
        'cr2',
        'cr3',
        'cr4',
        'dr0',
        'dr1',
        'dr2',
        'dr3',
        'dr4',
        'dr5',
        'dr6',
        'dr7',
        'eax',
        'ebp',
        'ebx',
        'ecx',
        'edi',
        'edx',
        'esi',
        'esp',
        'mm0',
        'mm1',
        'mm2',
        'mm3',
        'mm4',
        'mm5',
        'mm6',
        'mm7',
        'st0',
        'st1',
        'st2',
        'st3',
        'st4',
        'st5',
        'st6',
        'st7',
        'xmm0',
        'xmm1',
        'xmm2',
        'xmm3',
        'xmm4',
        'xmm5',
        'xmm6',
        'xmm7'}
    ASM_INSTRUCTIONS = {
        'bt',
        'in',
        'ja',
        'jb',
        'jc',
        'je',
        'jg',
        'jl',
        'jo',
        'jp',
        'js',
        'jz',
        'or',
        'aaa',
        'aad',
        'aam',
        'aas',
        'adc',
        'add',
        'and',
        'bsf',
        'bsr',
        'btc',
        'btr',
        'bts',
        'cbw',
        'cdq',
        'clc',
        'cld',
        'cli',
        'cmc',
        'cmp',
        'cwd',
        'daa',
        'das',
        'dec',
        'div',
        'hlt',
        'inc',
        'int',
        'jae',
        'jbe',
        'jge',
        'jle',
        'jmp',
        'jna',
        'jnb',
        'jnc',
        'jne',
        'jng',
        'jnl',
        'jno',
        'jnp',
        'jns',
        'jnz',
        'jpe',
        'jpo',
        'lar',
        'lds',
        'lea',
        'les',
        'lfs',
        'lgs',
        'lsl',
        'lss',
        'ltr',
        'mov',
        'mul',
        'neg',
        'nop',
        'not',
        'out',
        'pop',
        'rcl',
        'rcr',
        'rep',
        'ret',
        'rol',
        'ror',
        'rsm',
        'sal',
        'sar',
        'sbb',
        'shl',
        'shr',
        'smi',
        'stc',
        'std',
        'sti',
        'str',
        'sub',
        'ud1',
        'ud2',
        'xor',
        'arpl',
        'call',
        'clts',
        'cwde',
        'emms',
        'ibts',
        'idiv',
        'imul',
        'insb',
        'insd',
        'insw',
        'int1',
        'int3',
        'into',
        'invd',
        'iret',
        'jcxz',
        'jnae',
        'jnbe',
        'jnge',
        'jnle',
        'lahf',
        'lgdt',
        'lidt',
        'ljmp',
        'lldt',
        'lmsw',
        'lock',
        'loop',
        'movd',
        'movq',
        'popa',
        'popf',
        'push',
        'repe',
        'repz',
        'retf',
        'retn',
        'rsdc',
        'sahf',
        'salc',
        'seta',
        'setb',
        'setc',
        'sete',
        'setg',
        'setl',
        'seto',
        'setp',
        'sets',
        'setz',
        'sgdt',
        'shld',
        'shrd',
        'sidt',
        'sldt',
        'smsw',
        'svdc',
        'svts',
        'test',
        'umov',
        'verr',
        'verw',
        'wait',
        'xadd',
        'xbts',
        'xchg',
        'xlat',
        'bound',
        'bswap',
        'cmova',
        'cmovb',
        'cmovc',
        'cmove',
        'cmovg',
        'cmovl',
        'cmovo',
        'cmovp',
        'cmovs',
        'cmovz',
        'cmpsb',
        'cmpsd',
        'cmpsw',
        'cpuid',
        'enter',
        'icebp',
        'int01',
        'int03',
        'iretd',
        'iretw',
        'jecxz',
        'lcall',
        'leave',
        'lodsb',
        'lodsd',
        'lodsw',
        'loope',
        'loopz',
        'movsb',
        'movsd',
        'movsw',
        'movsx',
        'movzx',
        'outsb',
        'outsd',
        'outsw',
        'popad',
        'popaw',
        'popfd',
        'popfw',
        'pusha',
        'pushf',
        'rdmsr',
        'rdpmc',
        'rdshr',
        'rdtsc',
        'repne',
        'repnz',
        'rsldt',
        'scasb',
        'scasd',
        'scasw',
        'setae',
        'setbe',
        'setge',
        'setle',
        'setna',
        'setnb',
        'setnc',
        'setne',
        'setng',
        'setnl',
        'setno',
        'setnp',
        'setns',
        'setnz',
        'setpe',
        'setpo',
        'smint',
        'stosb',
        'stosd',
        'stosw',
        'svldt',
        'wrmsr',
        'wrshr',
        'xlatb',
        'cmovae',
        'cmovbe',
        'cmovge',
        'cmovle',
        'cmovna',
        'cmovnb',
        'cmovnc',
        'cmovne',
        'cmovng',
        'cmovnl',
        'cmovno',
        'cmovnp',
        'cmovns',
        'cmovnz',
        'cmovpe',
        'cmovpo',
        'invlpg',
        'loopne',
        'loopnz',
        'pushad',
        'pushaw',
        'pushfd',
        'pushfw',
        'setcxz',
        'setnae',
        'setnbe',
        'setnge',
        'setnle',
        'sysret',
        'wbinvd',
        'cmovcxz',
        'cmovnae',
        'cmovnbe',
        'cmovnge',
        'cmovnle',
        'cmpxchg',
        'loadall',
        'syscall',
        'sysexit',
        'smintold',
        'sysenter',
        'cmpxchg8b',
        'cmpxchg486',
        'loadall286'}
    PORTUGOL_KEYWORDS = ('aleatorio', 'algoritmo', 'arquivo', 'ate', 'caso', 'cronometro', 'debug', 'e', 'eco', 'enquanto', 'entao', 'escolha', 'escreva', 'escreval', 'faca', 'falso', 'fimalgoritmo', 'fimenquanto', 'fimescolha', 'fimfuncao', 'fimpara', 'fimprocedimento', 'fimrepita', 'fimse', 'funcao', 'inicio', 'int', 'interrompa', 'leia', 'limpatela', 'mod', 'nao', 'ou', 'outrocaso', 'para', 'passo', 'pausa', 'procedimento', 'repita', 'retorne', 'se', 'senao', 'timer', 'var', 'vetor', 'verdadeiro', 'xou', 'div', 'mod', 'abs', 'arccos', 'arcsen', 'arctan', 'cos', 'cotan', 'Exp', 'grauprad', 'int', 'log', 'logn', 'pi', 'quad', 'radpgrau', 'raizq', 'rand', 'randi', 'sen', 'Tan', 'asc', 'carac', 'caracpnum', 'compr', 'copia', 'maiusc', 'minusc', 'numpcarac', 'pos')
    PORTUGOL_BUILTIN_TYPES = {
        'real',
        'logico',
        'inteiro',
        'caractere'}
    
    def __init__(self, **options):
        pass
    # WARNING: Decompyle incomplete

    
    def get_tokens_unprocessed(self, text):
        pass
    # WARNING: Decompyle incomplete
