# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: slash.pyc (Python 3.11)

'''
    pygments.lexers.slash
    ~~~~~~~~~~~~~~~~~~~~~

    Lexer for the Slash programming language.

    :copyright: Copyright 2006-2025 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
'''
from pygments.lexer import ExtendedRegexLexer, bygroups, DelegatingLexer
from pygments.token import Name, Number, String, Comment, Punctuation, Other, Keyword, Operator, Whitespace
__all__ = [
    'SlashLexer']

class SlashLanguageLexer(ExtendedRegexLexer):
    _nkw = '(?=[^a-zA-Z_0-9])'
    
    def move_state(new_state):
        return ('#pop', new_state)

    
    def right_angle_bracket(lexer, match, ctx):
        pass
    # WARNING: Decompyle incomplete

    tokens = {
        'root': [][('%>', Comment.Preproc, move_state('root'))][('\\"', String, move_state('string'))][("'[a-zA-Z0-9_]+", String)][('%r{', String.Regex, move_state('regexp'))][('/\\*.*?\\*/', Comment.Multiline)][('(#|//).*?\\n', Comment.Single)][('-?[0-9]+e[+-]?[0-9]+', Number.Float)][('-?[0-9]+\\.[0-9]+(e[+-]?[0-9]+)?', Number.Float)][('-?[0-9]+', Number.Integer)][('nil' + _nkw, Name.Builtin)][('true' + _nkw, Name.Builtin)][('false' + _nkw, Name.Builtin)][('self' + _nkw, Name.Builtin)][("(class)(\\s+)([A-Z][a-zA-Z0-9_\\']*)", bygroups(Keyword, Whitespace, Name.Class))][('class' + _nkw, Keyword)][('extends' + _nkw, Keyword)][("(def)(\\s+)(self)(\\s*)(\\.)(\\s*)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Builtin, Whitespace, Punctuation, Whitespace, Name.Function))][("(def)(\\s+)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Function))][('def' + _nkw, Keyword)][('if' + _nkw, Keyword)][('elsif' + _nkw, Keyword)][('else' + _nkw, Keyword)][('unless' + _nkw, Keyword)][('for' + _nkw, Keyword)][('in' + _nkw, Keyword)][('while' + _nkw, Keyword)][('until' + _nkw, Keyword)][('and' + _nkw, Keyword)][('or' + _nkw, Keyword)][('not' + _nkw, Keyword)][('lambda' + _nkw, Keyword)][('try' + _nkw, Keyword)][('catch' + _nkw, Keyword)][('return' + _nkw, Keyword)][('next' + _nkw, Keyword)][('last' + _nkw, Keyword)][('throw' + _nkw, Keyword)][('use' + _nkw, Keyword)][('switch' + _nkw, Keyword)][('\\\\', Keyword)][('λ', Keyword)][('__FILE__' + _nkw, Name.Builtin.Pseudo)][('__LINE__' + _nkw, Name.Builtin.Pseudo)][("[A-Z][a-zA-Z0-9_\\']*" + _nkw, Name.Constant)][("[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name)][("@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Instance)][("@@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Class)][('\\(', Punctuation)][('\\)', Punctuation)][('\\[', Punctuation)][('\\]', Punctuation)][('\\{', Punctuation)][('\\}', right_angle_bracket)][(';', Punctuation)][(',', Punctuation)][('<<=', Operator)][('>>=', Operator)][('<<', Operator)][('>>', Operator)][('==', Operator)][('!=', Operator)][('=>', Operator)][('=', Operator)][('<=>', Operator)][('<=', Operator)][('>=', Operator)][('<', Operator)][('>', Operator)][('\\+\\+', Operator)][('\\+=', Operator)][('-=', Operator)][('\\*\\*=', Operator)][('\\*=', Operator)][('\\*\\*', Operator)][('\\*', Operator)][('/=', Operator)][('\\+', Operator)][('-', Operator)][('/', Operator)][('%=', Operator)][('%', Operator)][('^=', Operator)][('&&=', Operator)][('&=', Operator)][('&&', Operator)][('&', Operator)][('\\|\\|=', Operator)][('\\|=', Operator)][('\\|\\|', Operator)][('\\|', Operator)][('!', Operator)][('\\.\\.\\.', Operator)][('\\.\\.', Operator)],
        'string': [][('%>', Comment.Preproc, move_state('root'))][('\\"', String, move_state('string'))][("'[a-zA-Z0-9_]+", String)][('%r{', String.Regex, move_state('regexp'))][('/\\*.*?\\*/', Comment.Multiline)][('(#|//).*?\\n', Comment.Single)][('-?[0-9]+e[+-]?[0-9]+', Number.Float)][('-?[0-9]+\\.[0-9]+(e[+-]?[0-9]+)?', Number.Float)][('-?[0-9]+', Number.Integer)][('nil' + _nkw, Name.Builtin)][('true' + _nkw, Name.Builtin)][('false' + _nkw, Name.Builtin)][('self' + _nkw, Name.Builtin)][("(class)(\\s+)([A-Z][a-zA-Z0-9_\\']*)", bygroups(Keyword, Whitespace, Name.Class))][('class' + _nkw, Keyword)][('extends' + _nkw, Keyword)][("(def)(\\s+)(self)(\\s*)(\\.)(\\s*)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Builtin, Whitespace, Punctuation, Whitespace, Name.Function))][("(def)(\\s+)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Function))][('def' + _nkw, Keyword)][('if' + _nkw, Keyword)][('elsif' + _nkw, Keyword)][('else' + _nkw, Keyword)][('unless' + _nkw, Keyword)][('for' + _nkw, Keyword)][('in' + _nkw, Keyword)][('while' + _nkw, Keyword)][('until' + _nkw, Keyword)][('and' + _nkw, Keyword)][('or' + _nkw, Keyword)][('not' + _nkw, Keyword)][('lambda' + _nkw, Keyword)][('try' + _nkw, Keyword)][('catch' + _nkw, Keyword)][('return' + _nkw, Keyword)][('next' + _nkw, Keyword)][('last' + _nkw, Keyword)][('throw' + _nkw, Keyword)][('use' + _nkw, Keyword)][('switch' + _nkw, Keyword)][('\\\\', Keyword)][('λ', Keyword)][('__FILE__' + _nkw, Name.Builtin.Pseudo)][('__LINE__' + _nkw, Name.Builtin.Pseudo)][("[A-Z][a-zA-Z0-9_\\']*" + _nkw, Name.Constant)][("[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name)][("@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Instance)][("@@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Class)][('\\(', Punctuation)][('\\)', Punctuation)][('\\[', Punctuation)][('\\]', Punctuation)][('\\{', Punctuation)][('\\}', right_angle_bracket)][(';', Punctuation)][(',', Punctuation)][('<<=', Operator)][('>>=', Operator)][('<<', Operator)][('>>', Operator)][('==', Operator)][('!=', Operator)][('=>', Operator)][('=', Operator)][('<=>', Operator)][('<=', Operator)][('>=', Operator)][('<', Operator)][('>', Operator)][('\\+\\+', Operator)][('\\+=', Operator)][('-=', Operator)][('\\*\\*=', Operator)][('\\*=', Operator)][('\\*\\*', Operator)][('\\*', Operator)][('/=', Operator)][('\\+', Operator)][('-', Operator)][('/', Operator)][('%=', Operator)][('%', Operator)][('^=', Operator)][('&&=', Operator)][('&=', Operator)][('&&', Operator)][('&', Operator)][('\\|\\|=', Operator)][('\\|=', Operator)][('\\|\\|', Operator)][('\\|', Operator)][('!', Operator)][('\\.\\.\\.', Operator)][('\\.\\.', Operator)][('\\.', Operator)],
        'string_e': [][('%>', Comment.Preproc, move_state('root'))][('\\"', String, move_state('string'))][("'[a-zA-Z0-9_]+", String)][('%r{', String.Regex, move_state('regexp'))][('/\\*.*?\\*/', Comment.Multiline)][('(#|//).*?\\n', Comment.Single)][('-?[0-9]+e[+-]?[0-9]+', Number.Float)][('-?[0-9]+\\.[0-9]+(e[+-]?[0-9]+)?', Number.Float)][('-?[0-9]+', Number.Integer)][('nil' + _nkw, Name.Builtin)][('true' + _nkw, Name.Builtin)][('false' + _nkw, Name.Builtin)][('self' + _nkw, Name.Builtin)][("(class)(\\s+)([A-Z][a-zA-Z0-9_\\']*)", bygroups(Keyword, Whitespace, Name.Class))][('class' + _nkw, Keyword)][('extends' + _nkw, Keyword)][("(def)(\\s+)(self)(\\s*)(\\.)(\\s*)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Builtin, Whitespace, Punctuation, Whitespace, Name.Function))][("(def)(\\s+)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Function))][('def' + _nkw, Keyword)][('if' + _nkw, Keyword)][('elsif' + _nkw, Keyword)][('else' + _nkw, Keyword)][('unless' + _nkw, Keyword)][('for' + _nkw, Keyword)][('in' + _nkw, Keyword)][('while' + _nkw, Keyword)][('until' + _nkw, Keyword)][('and' + _nkw, Keyword)][('or' + _nkw, Keyword)][('not' + _nkw, Keyword)][('lambda' + _nkw, Keyword)][('try' + _nkw, Keyword)][('catch' + _nkw, Keyword)][('return' + _nkw, Keyword)][('next' + _nkw, Keyword)][('last' + _nkw, Keyword)][('throw' + _nkw, Keyword)][('use' + _nkw, Keyword)][('switch' + _nkw, Keyword)][('\\\\', Keyword)][('λ', Keyword)][('__FILE__' + _nkw, Name.Builtin.Pseudo)][('__LINE__' + _nkw, Name.Builtin.Pseudo)][("[A-Z][a-zA-Z0-9_\\']*" + _nkw, Name.Constant)][("[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name)][("@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Instance)][("@@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Class)][('\\(', Punctuation)][('\\)', Punctuation)][('\\[', Punctuation)][('\\]', Punctuation)][('\\{', Punctuation)][('\\}', right_angle_bracket)][(';', Punctuation)][(',', Punctuation)][('<<=', Operator)][('>>=', Operator)][('<<', Operator)][('>>', Operator)][('==', Operator)][('!=', Operator)][('=>', Operator)][('=', Operator)][('<=>', Operator)][('<=', Operator)][('>=', Operator)][('<', Operator)][('>', Operator)][('\\+\\+', Operator)][('\\+=', Operator)][('-=', Operator)][('\\*\\*=', Operator)][('\\*=', Operator)][('\\*\\*', Operator)][('\\*', Operator)][('/=', Operator)][('\\+', Operator)][('-', Operator)][('/', Operator)][('%=', Operator)][('%', Operator)][('^=', Operator)][('&&=', Operator)][('&=', Operator)][('&&', Operator)][('&', Operator)][('\\|\\|=', Operator)][('\\|=', Operator)][('\\|\\|', Operator)][('\\|', Operator)][('!', Operator)][('\\.\\.\\.', Operator)][('\\.\\.', Operator)][('\\.', Operator)][('::', Operator)],
        'regexp': [][('%>', Comment.Preproc, move_state('root'))][('\\"', String, move_state('string'))][("'[a-zA-Z0-9_]+", String)][('%r{', String.Regex, move_state('regexp'))][('/\\*.*?\\*/', Comment.Multiline)][('(#|//).*?\\n', Comment.Single)][('-?[0-9]+e[+-]?[0-9]+', Number.Float)][('-?[0-9]+\\.[0-9]+(e[+-]?[0-9]+)?', Number.Float)][('-?[0-9]+', Number.Integer)][('nil' + _nkw, Name.Builtin)][('true' + _nkw, Name.Builtin)][('false' + _nkw, Name.Builtin)][('self' + _nkw, Name.Builtin)][("(class)(\\s+)([A-Z][a-zA-Z0-9_\\']*)", bygroups(Keyword, Whitespace, Name.Class))][('class' + _nkw, Keyword)][('extends' + _nkw, Keyword)][("(def)(\\s+)(self)(\\s*)(\\.)(\\s*)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Builtin, Whitespace, Punctuation, Whitespace, Name.Function))][("(def)(\\s+)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Function))][('def' + _nkw, Keyword)][('if' + _nkw, Keyword)][('elsif' + _nkw, Keyword)][('else' + _nkw, Keyword)][('unless' + _nkw, Keyword)][('for' + _nkw, Keyword)][('in' + _nkw, Keyword)][('while' + _nkw, Keyword)][('until' + _nkw, Keyword)][('and' + _nkw, Keyword)][('or' + _nkw, Keyword)][('not' + _nkw, Keyword)][('lambda' + _nkw, Keyword)][('try' + _nkw, Keyword)][('catch' + _nkw, Keyword)][('return' + _nkw, Keyword)][('next' + _nkw, Keyword)][('last' + _nkw, Keyword)][('throw' + _nkw, Keyword)][('use' + _nkw, Keyword)][('switch' + _nkw, Keyword)][('\\\\', Keyword)][('λ', Keyword)][('__FILE__' + _nkw, Name.Builtin.Pseudo)][('__LINE__' + _nkw, Name.Builtin.Pseudo)][("[A-Z][a-zA-Z0-9_\\']*" + _nkw, Name.Constant)][("[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name)][("@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Instance)][("@@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Class)][('\\(', Punctuation)][('\\)', Punctuation)][('\\[', Punctuation)][('\\]', Punctuation)][('\\{', Punctuation)][('\\}', right_angle_bracket)][(';', Punctuation)][(',', Punctuation)][('<<=', Operator)][('>>=', Operator)][('<<', Operator)][('>>', Operator)][('==', Operator)][('!=', Operator)][('=>', Operator)][('=', Operator)][('<=>', Operator)][('<=', Operator)][('>=', Operator)][('<', Operator)][('>', Operator)][('\\+\\+', Operator)][('\\+=', Operator)][('-=', Operator)][('\\*\\*=', Operator)][('\\*=', Operator)][('\\*\\*', Operator)][('\\*', Operator)][('/=', Operator)][('\\+', Operator)][('-', Operator)][('/', Operator)][('%=', Operator)][('%', Operator)][('^=', Operator)][('&&=', Operator)][('&=', Operator)][('&&', Operator)][('&', Operator)][('\\|\\|=', Operator)][('\\|=', Operator)][('\\|\\|', Operator)][('\\|', Operator)][('!', Operator)][('\\.\\.\\.', Operator)][('\\.\\.', Operator)][('\\.', Operator)][('::', Operator)][(':', Operator)],
        'regexp_r': [][('%>', Comment.Preproc, move_state('root'))][('\\"', String, move_state('string'))][("'[a-zA-Z0-9_]+", String)][('%r{', String.Regex, move_state('regexp'))][('/\\*.*?\\*/', Comment.Multiline)][('(#|//).*?\\n', Comment.Single)][('-?[0-9]+e[+-]?[0-9]+', Number.Float)][('-?[0-9]+\\.[0-9]+(e[+-]?[0-9]+)?', Number.Float)][('-?[0-9]+', Number.Integer)][('nil' + _nkw, Name.Builtin)][('true' + _nkw, Name.Builtin)][('false' + _nkw, Name.Builtin)][('self' + _nkw, Name.Builtin)][("(class)(\\s+)([A-Z][a-zA-Z0-9_\\']*)", bygroups(Keyword, Whitespace, Name.Class))][('class' + _nkw, Keyword)][('extends' + _nkw, Keyword)][("(def)(\\s+)(self)(\\s*)(\\.)(\\s*)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Builtin, Whitespace, Punctuation, Whitespace, Name.Function))][("(def)(\\s+)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Function))][('def' + _nkw, Keyword)][('if' + _nkw, Keyword)][('elsif' + _nkw, Keyword)][('else' + _nkw, Keyword)][('unless' + _nkw, Keyword)][('for' + _nkw, Keyword)][('in' + _nkw, Keyword)][('while' + _nkw, Keyword)][('until' + _nkw, Keyword)][('and' + _nkw, Keyword)][('or' + _nkw, Keyword)][('not' + _nkw, Keyword)][('lambda' + _nkw, Keyword)][('try' + _nkw, Keyword)][('catch' + _nkw, Keyword)][('return' + _nkw, Keyword)][('next' + _nkw, Keyword)][('last' + _nkw, Keyword)][('throw' + _nkw, Keyword)][('use' + _nkw, Keyword)][('switch' + _nkw, Keyword)][('\\\\', Keyword)][('λ', Keyword)][('__FILE__' + _nkw, Name.Builtin.Pseudo)][('__LINE__' + _nkw, Name.Builtin.Pseudo)][("[A-Z][a-zA-Z0-9_\\']*" + _nkw, Name.Constant)][("[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name)][("@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Instance)][("@@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Class)][('\\(', Punctuation)][('\\)', Punctuation)][('\\[', Punctuation)][('\\]', Punctuation)][('\\{', Punctuation)][('\\}', right_angle_bracket)][(';', Punctuation)][(',', Punctuation)][('<<=', Operator)][('>>=', Operator)][('<<', Operator)][('>>', Operator)][('==', Operator)][('!=', Operator)][('=>', Operator)][('=', Operator)][('<=>', Operator)][('<=', Operator)][('>=', Operator)][('<', Operator)][('>', Operator)][('\\+\\+', Operator)][('\\+=', Operator)][('-=', Operator)][('\\*\\*=', Operator)][('\\*=', Operator)][('\\*\\*', Operator)][('\\*', Operator)][('/=', Operator)][('\\+', Operator)][('-', Operator)][('/', Operator)][('%=', Operator)][('%', Operator)][('^=', Operator)][('&&=', Operator)][('&=', Operator)][('&&', Operator)][('&', Operator)][('\\|\\|=', Operator)][('\\|=', Operator)][('\\|\\|', Operator)][('\\|', Operator)][('!', Operator)][('\\.\\.\\.', Operator)][('\\.\\.', Operator)][('\\.', Operator)][('::', Operator)][(':', Operator)][('(\\s|\\n)+', Whitespace)],
        'slash': [][('%>', Comment.Preproc, move_state('root'))][('\\"', String, move_state('string'))][("'[a-zA-Z0-9_]+", String)][('%r{', String.Regex, move_state('regexp'))][('/\\*.*?\\*/', Comment.Multiline)][('(#|//).*?\\n', Comment.Single)][('-?[0-9]+e[+-]?[0-9]+', Number.Float)][('-?[0-9]+\\.[0-9]+(e[+-]?[0-9]+)?', Number.Float)][('-?[0-9]+', Number.Integer)][('nil' + _nkw, Name.Builtin)][('true' + _nkw, Name.Builtin)][('false' + _nkw, Name.Builtin)][('self' + _nkw, Name.Builtin)][("(class)(\\s+)([A-Z][a-zA-Z0-9_\\']*)", bygroups(Keyword, Whitespace, Name.Class))][('class' + _nkw, Keyword)][('extends' + _nkw, Keyword)][("(def)(\\s+)(self)(\\s*)(\\.)(\\s*)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Builtin, Whitespace, Punctuation, Whitespace, Name.Function))][("(def)(\\s+)([a-z_][a-zA-Z0-9_\\']*=?|<<|>>|==|<=>|<=|<|>=|>|\\+|-(self)?|~(self)?|\\*|/|%|^|&&|&|\\||\\[\\]=?)", bygroups(Keyword, Whitespace, Name.Function))][('def' + _nkw, Keyword)][('if' + _nkw, Keyword)][('elsif' + _nkw, Keyword)][('else' + _nkw, Keyword)][('unless' + _nkw, Keyword)][('for' + _nkw, Keyword)][('in' + _nkw, Keyword)][('while' + _nkw, Keyword)][('until' + _nkw, Keyword)][('and' + _nkw, Keyword)][('or' + _nkw, Keyword)][('not' + _nkw, Keyword)][('lambda' + _nkw, Keyword)][('try' + _nkw, Keyword)][('catch' + _nkw, Keyword)][('return' + _nkw, Keyword)][('next' + _nkw, Keyword)][('last' + _nkw, Keyword)][('throw' + _nkw, Keyword)][('use' + _nkw, Keyword)][('switch' + _nkw, Keyword)][('\\\\', Keyword)][('λ', Keyword)][('__FILE__' + _nkw, Name.Builtin.Pseudo)][('__LINE__' + _nkw, Name.Builtin.Pseudo)][("[A-Z][a-zA-Z0-9_\\']*" + _nkw, Name.Constant)][("[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name)][("@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Instance)][("@@[a-z_][a-zA-Z0-9_\\']*" + _nkw, Name.Variable.Class)][('\\(', Punctuation)][('\\)', Punctuation)][('\\[', Punctuation)][('\\]', Punctuation)][('\\{', Punctuation)][('\\}', right_angle_bracket)][(';', Punctuation)][(',', Punctuation)][('<<=', Operator)][('>>=', Operator)][('<<', Operator)][('>>', Operator)][('==', Operator)][('!=', Operator)][('=>', Operator)][('=', Operator)][('<=>', Operator)][('<=', Operator)][('>=', Operator)][('<', Operator)][('>', Operator)][('\\+\\+', Operator)][('\\+=', Operator)][('-=', Operator)][('\\*\\*=', Operator)][('\\*=', Operator)][('\\*\\*', Operator)][('\\*', Operator)][('/=', Operator)][('\\+', Operator)][('-', Operator)][('/', Operator)][('%=', Operator)][('%', Operator)][('^=', Operator)][('&&=', Operator)][('&=', Operator)][('&&', Operator)][('&', Operator)][('\\|\\|=', Operator)][('\\|=', Operator)][('\\|\\|', Operator)][('\\|', Operator)][('!', Operator)][('\\.\\.\\.', Operator)][('\\.\\.', Operator)][('\\.', Operator)][('::', Operator)][(':', Operator)][('(\\s|\\n)+', Whitespace)][("[a-z_][a-zA-Z0-9_\\']*", Name.Variable)] }


class SlashLexer(DelegatingLexer):
    pass
# WARNING: Decompyle incomplete
