# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: parallel.pyc (Python 3.11)

'''
This file implements the code-generator for parallel-vectorize.

ParallelUFunc is the platform independent base class for generating
the thread dispatcher.  This thread dispatcher launches threads
that execute the generated function of UFuncCore.
UFuncCore is subclassed to specialize for the input/output types.
The actual workload is invoked inside the function generated by UFuncCore.
UFuncCore also defines a work-stealing mechanism that allows idle threads
to steal works from other threads.
'''
import os
import sys
import warnings
from threading import RLock as threadRLock
from ctypes import CFUNCTYPE, c_int, CDLL, POINTER, c_uint
import numpy as np
from llvmlite.binding import binding as ll
from llvmlite import ir
from numba.np.numpy_support import as_dtype
from numba.core import types, cgutils, config, errors
from numba.core.typing import signature
from numba.np.ufunc.wrappers import _wrapper_info
from numba.np.ufunc import ufuncbuilder
from numba.extending import overload, intrinsic
_IS_OSX = sys.platform.startswith('darwin')
_IS_LINUX = sys.platform.startswith('linux')
_IS_WINDOWS = sys.platform.startswith('win32')

def get_thread_count():
    '''
    Gets the available thread count.
    '''
    t = config.NUMBA_NUM_THREADS
    if t < 1:
        raise ValueError('Number of threads specified must be > 0.')
    return t

NUM_THREADS = get_thread_count()

def build_gufunc_kernel(library, ctx, info, sig, inner_ndim):
    """Wrap the original CPU ufunc/gufunc with a parallel dispatcher.
    This function will wrap gufuncs and ufuncs something like.

    Args
    ----
    ctx
        numba's codegen context

    info: (library, env, name)
        inner function info

    sig
        type signature of the gufunc

    inner_ndim
        inner dimension of the gufunc (this is len(sig.args) in the case of a
        ufunc)

    Returns
    -------
    wrapper_info : (library, env, name)
        The info for the gufunc wrapper.

    Details
    -------

    The kernel signature looks like this:

    void kernel(char **args, npy_intp *dimensions, npy_intp* steps, void* data)

    args - the input arrays + output arrays
    dimensions - the dimensions of the arrays
    steps - the step size for the array (this is like sizeof(type))
    data - any additional data

    The parallel backend then stages multiple calls to this kernel concurrently
    across a number of threads. Practically, for each item of work, the backend
    duplicates `dimensions` and adjusts the first entry to reflect the size of
    the item of work, it also forms up an array of pointers into the args for
    offsets to read/write from/to with respect to its position in the items of
    work. This allows the same kernel to be used for each item of work, with
    simply adjusted reads/writes/domain sizes and is safe by virtue of the
    domain partitioning.

    NOTE: The execution backend is passed the requested thread count, but it can
    choose to ignore it (TBB)!
    """
    pass
# WARNING: Decompyle incomplete


class ParallelUFuncBuilder(ufuncbuilder.UFuncBuilder):
    
    def build(self, cres, sig):
        _launch_threads()
        ctx = cres.target_context
        signature = cres.signature
        library = cres.library
        fname = cres.fndesc.llvm_func_name
        info = build_ufunc_wrapper(library, ctx, fname, signature, cres)
        ptr = info.library.get_pointer_to_function(info.name)
        dtypenums = signature.args()
        dtypenums.append(np.dtype(signature.return_type.name).num)
        keepalive = ()
        return (dtypenums, ptr, keepalive)



def build_ufunc_wrapper(library, ctx, fname, signature, cres):
    innerfunc = ufuncbuilder.build_ufunc_wrapper(library, ctx, fname, signature, objmode = False, cres = cres)
    info = build_gufunc_kernel(library, ctx, innerfunc, signature, len(signature.args))
    return info


class ParallelGUFuncBuilder(ufuncbuilder.GUFuncBuilder):
    pass
# WARNING: Decompyle incomplete


def build_gufunc_wrapper(py_func, cres, sin, sout, cache, is_parfors):
    '''Build gufunc wrapper for the given arguments.
    The *is_parfors* is a boolean indicating whether the gufunc is being
    built for use as a ParFors kernel. This changes codegen and caching
    behavior.
    '''
    library = cres.library
    ctx = cres.target_context
    signature = cres.signature
    innerinfo = ufuncbuilder.build_gufunc_wrapper(py_func, cres, sin, sout, cache = cache, is_parfors = is_parfors)
    sym_in = (lambda .0: pass# WARNING: Decompyle incomplete
)(sin())
    sym_out = (lambda .0: pass# WARNING: Decompyle incomplete
)(sout())
    inner_ndim = len(sym_in | sym_out)
    info = build_gufunc_kernel(library, ctx, innerinfo, signature, inner_ndim)
    return info

_backend_init_thread_lock = threadRLock()
_windows = sys.platform.startswith('win32')

class _nop(object):
    '''A no-op contextmanager
    '''
    
    def __enter__(self):
        pass

    
    def __exit__(self, *args):
        pass


_backend_init_process_lock = None

def _set_init_process_lock():
    global _backend_init_process_lock, _backend_init_process_lock, _backend_init_process_lock
    
    try:
        _backend_init_thread_lock
        import multiprocessing
        if 'fork' in multiprocessing.get_start_method() or _windows:
            ctx = multiprocessing.get_context()
            _backend_init_process_lock = ctx.RLock()
        else:
            _backend_init_process_lock = _nop()
            
            try:
                None(None, None)
                return None
                with None:
                    if not None:
                        
                        try:
                            
                            try:
                                return None
                            except OSError:
                                e = None
                                msg = "Could not obtain multiprocessing lock due to OS level error: %s\nA likely cause of this problem is '/dev/shm' is missing or read-only such that necessary semaphores cannot be written.\n*** The responsibility of ensuring multiprocessing safe access to this initialization sequence/module import is deferred to the user! ***\n"
                                warnings.warn(msg % str(e), errors.NumbaSystemWarning)
                                _backend_init_process_lock = _nop()
                                e = None
                                del e
                                return None
                                e = None
                                del e





_is_initialized = False
_threading_layer = None

def threading_layer():
    '''
    Get the name of the threading layer in use for parallel CPU targets
    '''
    pass
# WARNING: Decompyle incomplete


def _check_tbb_version_compatible():
    '''
    Checks that if TBB is present it is of a compatible version.
    '''
    
    try:
        if _IS_WINDOWS:
            libtbb_name = 'tbb12.dll'
        elif _IS_OSX:
            libtbb_name = 'libtbb.12.dylib'
        elif _IS_LINUX:
            libtbb_name = 'libtbb.so.12'
        else:
            raise ValueError('Unknown operating system')
        libtbb = CDLL(libtbb_name)
        version_func = libtbb.TBB_runtime_interface_version
        version_func.argtypes = []
        version_func.restype = c_int
        tbb_iface_ver = version_func()
        if tbb_iface_ver < 12060:
            msg = 'The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = %s. The TBB threading layer is disabled.' % tbb_iface_ver
            problem = errors.NumbaWarning(msg)
            warnings.warn(problem)
            raise ImportError('Problem with TBB. Reason: %s' % msg)
        return None
    except (ValueError, OSError):
        e = None
        raise ImportError('Problem with TBB. Reason: %s' % e)
        e = None
        del e



def _launch_threads():
    pass
# WARNING: Decompyle incomplete


def _load_threading_functions(lib):
    global _set_num_threads, _get_num_threads, _get_thread_id, _set_parallel_chunksize, _get_parallel_chunksize, _get_sched_size
    ll.add_symbol('get_num_threads', lib.get_num_threads)
    ll.add_symbol('set_num_threads', lib.set_num_threads)
    ll.add_symbol('get_thread_id', lib.get_thread_id)
    _set_num_threads = CFUNCTYPE(None, c_int)(lib.set_num_threads)
    _set_num_threads(NUM_THREADS)
    _get_num_threads = CFUNCTYPE(c_int)(lib.get_num_threads)
    _get_thread_id = CFUNCTYPE(c_int)(lib.get_thread_id)
    ll.add_symbol('set_parallel_chunksize', lib.set_parallel_chunksize)
    ll.add_symbol('get_parallel_chunksize', lib.get_parallel_chunksize)
    ll.add_symbol('get_sched_size', lib.get_sched_size)
    _set_parallel_chunksize = CFUNCTYPE(c_uint, c_uint)(lib.set_parallel_chunksize)
    _get_parallel_chunksize = CFUNCTYPE(c_uint)(lib.get_parallel_chunksize)
    _get_sched_size = CFUNCTYPE(c_uint, c_uint, c_uint, POINTER(c_int), POINTER(c_int))(lib.get_sched_size)


def gen_snt_check():
    pass
# WARNING: Decompyle incomplete

snt_check = gen_snt_check()
ol_snt_check = (lambda n: snt_check)()

def set_num_threads(n):
    '''
    Set the number of threads to use for parallel execution.

    By default, all :obj:`numba.config.NUMBA_NUM_THREADS` threads are used.

    This functionality works by masking out threads that are not used.
    Therefore, the number of threads *n* must be less than or equal to
    :obj:`~.NUMBA_NUM_THREADS`, the total number of threads that are launched.
    See its documentation for more details.

    This function can be used inside of a jitted function.

    Parameters
    ----------
    n: The number of threads. Must be between 1 and NUMBA_NUM_THREADS.

    See Also
    --------
    get_num_threads, numba.config.NUMBA_NUM_THREADS,
    numba.config.NUMBA_DEFAULT_NUM_THREADS, :envvar:`NUMBA_NUM_THREADS`

    '''
    _launch_threads()
    if not isinstance(n, (int, np.integer)):
        raise TypeError('The number of threads specified must be an integer')
    snt_check(n)
    _set_num_threads(n)

ol_set_num_threads = (lambda n: _launch_threads()if not isinstance(n, types.Integer):
msg = 'The number of threads specified must be an integer'raise errors.TypingError(msg)
def impl(n):
snt_check(n)_set_num_threads(n)impl)()

def get_num_threads():
    '''
    Get the number of threads used for parallel execution.

    By default (if :func:`~.set_num_threads` is never called), all
    :obj:`numba.config.NUMBA_NUM_THREADS` threads are used.

    This number is less than or equal to the total number of threads that are
    launched, :obj:`numba.config.NUMBA_NUM_THREADS`.

    This function can be used inside of a jitted function.

    Returns
    -------
    The number of threads.

    See Also
    --------
    set_num_threads, numba.config.NUMBA_NUM_THREADS,
    numba.config.NUMBA_DEFAULT_NUM_THREADS, :envvar:`NUMBA_NUM_THREADS`

    '''
    _launch_threads()
    num_threads = _get_num_threads()
    if num_threads <= 0:
        raise RuntimeError(f'''Invalid number of threads. This likely indicates a bug in Numba. (thread_id={get_thread_id()!s}, num_threads={num_threads!s})''')
    return num_threads

ol_get_num_threads = (lambda : _launch_threads()
def impl():
num_threads = _get_num_threads()if num_threads <= 0:
print('Broken thread_id: ', get_thread_id())print('num_threads: ', num_threads)raise RuntimeError('Invalid number of threads. This likely indicates a bug in Numba.')num_threadsimpl)()
_iget_num_threads = (lambda typingctx: _launch_threads()
def codegen(context, builder, signature, args):
mod = builder.modulefnty = ir.FunctionType(cgutils.intp_t, [])fn = cgutils.get_or_insert_function(mod, fnty, 'get_num_threads')builder.call(fn, [])(signature(types.intp), codegen))()

def get_thread_id():
    '''
    Returns a unique ID for each thread in the range 0 (inclusive)
    to :func:`~.get_num_threads` (exclusive).
    '''
    _launch_threads()
    return _get_thread_id()

ol_get_thread_id = (lambda : _launch_threads()
def impl():
_iget_thread_id()impl)()
_iget_thread_id = (lambda typingctx: 
def codegen(context, builder, signature, args):
mod = builder.modulefnty = ir.FunctionType(cgutils.intp_t, [])fn = cgutils.get_or_insert_function(mod, fnty, 'get_thread_id')builder.call(fn, [])(signature(types.intp), codegen))()
_DYLD_WORKAROUND_SET = 'NUMBA_DYLD_WORKAROUND' in os.environ
_DYLD_WORKAROUND_VAL = int(os.environ.get('NUMBA_DYLD_WORKAROUND', 0))
if _DYLD_WORKAROUND_SET and _DYLD_WORKAROUND_VAL:
    _launch_threads()

def set_parallel_chunksize(n):
    _launch_threads()
    if not isinstance(n, (int, np.integer)):
        raise TypeError('The parallel chunksize must be an integer')
    if n < 0:
        raise ValueError('chunksize must be greater than or equal to zero')
    return _set_parallel_chunksize(n)


def get_parallel_chunksize():
    _launch_threads()
    return _get_parallel_chunksize()

ol_set_parallel_chunksize = (lambda n: _launch_threads()if not isinstance(n, types.Integer):
msg = 'The parallel chunksize must be an integer'raise errors.TypingError(msg)
def impl(n):
if n < 0:
raise ValueError('chunksize must be greater than or equal to zero')_set_parallel_chunksize(n)impl)()
ol_get_parallel_chunksize = (lambda : _launch_threads()
def impl():
_get_parallel_chunksize()impl)()
