# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: easy_input_message_param.pyc (Python 3.11)

from __future__ import annotations
from typing import Union
from typing_extensions import Literal, Required, TypedDict
from response_input_message_content_list_param import ResponseInputMessageContentListParam
__all__ = [
    'EasyInputMessageParam']

def EasyInputMessageParam():
    '''EasyInputMessageParam'''
    type: "Literal['message']" = '\n    A message input to the model with a role indicating instruction following\n    hierarchy. Instructions given with the `developer` or `system` role take\n    precedence over instructions given with the `user` role. Messages with the\n    `assistant` role are presumed to have been generated by the model in previous\n    interactions.\n    '

EasyInputMessageParam = <NODE:27>(EasyInputMessageParam, 'EasyInputMessageParam', TypedDict, total = False)
