# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: easy_input_message.pyc (Python 3.11)

from typing import Union, Optional
from typing_extensions import Literal
from _models import BaseModel
from response_input_message_content_list import ResponseInputMessageContentList
__all__ = [
    'EasyInputMessage']

class EasyInputMessage(BaseModel):
    role: Literal[('user', 'assistant', 'system', 'developer')] = '\n    A message input to the model with a role indicating instruction following\n    hierarchy. Instructions given with the `developer` or `system` role take\n    precedence over instructions given with the `user` role. Messages with the\n    `assistant` role are presumed to have been generated by the model in previous\n    interactions.\n    '
    type: Optional[Literal['message']] = None
