# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: response_compaction_item_param_param.pyc (Python 3.11)

from __future__ import annotations
from typing import Optional
from typing_extensions import Literal, Required, TypedDict
__all__ = [
    'ResponseCompactionItemParamParam']

def ResponseCompactionItemParamParam():
    '''ResponseCompactionItemParamParam'''
    id: 'Optional[str]' = '\n    A compaction item generated by the [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).\n    '

ResponseCompactionItemParamParam = <NODE:27>(ResponseCompactionItemParamParam, 'ResponseCompactionItemParamParam', TypedDict, total = False)
