# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: label_model_grader.pyc (Python 3.11)

from typing import List, Union, Optional
from typing_extensions import Literal, TypeAlias
from _models import BaseModel
from grader_inputs import GraderInputs
from responses.response_input_text import ResponseInputText
from responses.response_input_audio import ResponseInputAudio
__all__ = [
    'LabelModelGrader',
    'Input',
    'InputContent',
    'InputContentOutputText',
    'InputContentInputImage']

class InputContentOutputText(BaseModel):
    type: Literal['output_text'] = 'A text output from the model.'


class InputContentInputImage(BaseModel):
    type: Literal['input_image'] = 'An image input block used within EvalItem content arrays.'
    detail: Optional[str] = None

InputContent: TypeAlias = Union[(str, ResponseInputText, InputContentOutputText, InputContentInputImage, ResponseInputAudio, GraderInputs)]

class Input(BaseModel):
    role: Literal[('user', 'assistant', 'system', 'developer')] = '\n    A message input to the model with a role indicating instruction following\n    hierarchy. Instructions given with the `developer` or `system` role take\n    precedence over instructions given with the `user` role. Messages with the\n    `assistant` role are presumed to have been generated by the model in previous\n    interactions.\n    '
    type: Optional[Literal['message']] = None


class LabelModelGrader(BaseModel):
    type: Literal['label_model'] = '\n    A LabelModelGrader object which uses a model to assign labels to each item\n    in the evaluation.\n    '
