# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: score_model_grader_param.pyc (Python 3.11)

from __future__ import annotations
from typing import Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict
from grader_inputs_param import GraderInputsParam
from shared.reasoning_effort import ReasoningEffort
from responses.response_input_text_param import ResponseInputTextParam
from responses.response_input_audio_param import ResponseInputAudioParam
__all__ = [
    'ScoreModelGraderParam',
    'Input',
    'InputContent',
    'InputContentOutputText',
    'InputContentInputImage',
    'SamplingParams']

def InputContentOutputText():
    '''InputContentOutputText'''
    type: "Required[Literal['output_text']]" = 'A text output from the model.'

InputContentOutputText = <NODE:27>(InputContentOutputText, 'InputContentOutputText', TypedDict, total = False)

def InputContentInputImage():
    '''InputContentInputImage'''
    detail: 'str' = 'An image input block used within EvalItem content arrays.'

InputContentInputImage = <NODE:27>(InputContentInputImage, 'InputContentInputImage', TypedDict, total = False)
InputContent: 'TypeAlias' = Union[(str, ResponseInputTextParam, InputContentOutputText, InputContentInputImage, ResponseInputAudioParam, GraderInputsParam)]

def Input():
    '''Input'''
    type: "Literal['message']" = '\n    A message input to the model with a role indicating instruction following\n    hierarchy. Instructions given with the `developer` or `system` role take\n    precedence over instructions given with the `user` role. Messages with the\n    `assistant` role are presumed to have been generated by the model in previous\n    interactions.\n    '

Input = <NODE:27>(Input, 'Input', TypedDict, total = False)

def SamplingParams():
    '''SamplingParams'''
    top_p: 'Optional[float]' = 'The sampling parameters for the model.'

SamplingParams = <NODE:27>(SamplingParams, 'SamplingParams', TypedDict, total = False)

def ScoreModelGraderParam():
    '''ScoreModelGraderParam'''
    sampling_params: 'SamplingParams' = 'A ScoreModelGrader object that uses a model to assign a score to the input.'

ScoreModelGraderParam = <NODE:27>(ScoreModelGraderParam, 'ScoreModelGraderParam', TypedDict, total = False)
