# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: refusal_content_block.pyc (Python 3.11)

from typing_extensions import Literal
from _models import BaseModel
__all__ = [
    'RefusalContentBlock']

class RefusalContentBlock(BaseModel):
    type: Literal['refusal'] = 'The refusal content generated by the assistant.'
