# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: record_queries.pyc (Python 3.11)

from __future__ import annotations
import dataclasses
import inspect
import typing as t
from time import perf_counter
import sqlalchemy as sa
from sqlalchemy.event import event as sa_event
from flask import current_app
from flask import g
from flask import has_app_context

def get_recorded_queries():
    '''Get the list of recorded query information for the current session. Queries are
    recorded if the config :data:`.SQLALCHEMY_RECORD_QUERIES` is enabled.

    Each query info object has the following attributes:

    ``statement``
        The string of SQL generated by SQLAlchemy with parameter placeholders.
    ``parameters``
        The parameters sent with the SQL statement.
    ``start_time`` / ``end_time``
        Timing info about when the query started execution and when the results where
        returned. Accuracy and value depends on the operating system.
    ``duration``
        The time the query took in seconds.
    ``location``
        A string description of where in your application code the query was executed.
        This may not be possible to calculate, and the format is not stable.

    .. versionchanged:: 3.0
        Renamed from ``get_debug_queries``.

    .. versionchanged:: 3.0
        The info object is a dataclass instead of a tuple.

    .. versionchanged:: 3.0
        The info object attribute ``context`` is renamed to ``location``.

    .. versionchanged:: 3.0
        Not enabled automatically in debug or testing mode.
    '''
    return g.get('_sqlalchemy_queries', [])

_QueryInfo = <NODE:12>()

def _listen(engine = None):
    sa_event.listen(engine, 'before_cursor_execute', _record_start, named = True)
    sa_event.listen(engine, 'after_cursor_execute', _record_end, named = True)


def _record_start(context = None, **kwargs):
    if not has_app_context():
        return None
    context._fsa_start_time = None()


def _record_end(context = None, **kwargs):
    if not has_app_context():
        return None
    if None not in g:
        g._sqlalchemy_queries = []
    import_top = current_app.import_name.partition('.')[0]
    import_dot = f'''{import_top}.'''
    frame = inspect.currentframe()
# WARNING: Decompyle incomplete
