# Source: pycdc (Decompyle++)
# Quality: HIGH - actual Python source

# Source Generated with Decompyle++
# File: project.pyc (Python 3.11)

import json
import logging
from app import db
from datetime import datetime
from sqlalchemy.orm.attributes import flag_modified
logger = logging.getLogger(__name__)

class Project(db.Model):
    __tablename__ = 'projects'
    id = db.Column(db.String(36), primary_key = True)
    title = db.Column(db.String(255), nullable = False)
    type = db.Column(db.String(10), nullable = False, default = 'direct')
    status = db.Column(db.String(20), default = 'draft')
    thumbnail = db.Column(db.String(500))
    current_step = db.Column(db.Integer, default = 0)
    topic = db.Column(db.Text)
    outline = db.Column(db.Text)
    script = db.Column(db.Text)
    audio_url = db.Column(db.String(500))
    typecast_audio_url = db.Column(db.String(500))
    web_tts_audio_url = db.Column(db.String(500))
    local_audio_url = db.Column(db.String(500))
    google_cloud_tts_audio_url = db.Column(db.String(500))
    google_cloud_tts_preview_url = db.Column(db.String(500))
    gemini_tts_audio_url = db.Column(db.String(500))
    gemini_tts_preview_url = db.Column(db.String(500))
    edge_tts_audio_url = db.Column(db.String(500))
    qwen3_tts_audio_url = db.Column(db.String(500))
    gemini_native_tts_audio_url = db.Column(db.String(500))
    elevenlabs_tts_audio_url = db.Column(db.String(500))
    selected_tts_method = db.Column(db.String(20))
    content_format = db.Column(db.String(20), default = 'longform')
    subtitle_url = db.Column(db.String(500))
    subtitles = db.Column(db.Text, nullable = True)
    youtube_title = db.Column(db.String(255))
    youtube_description = db.Column(db.Text)
    video_url = db.Column(db.String(500))
    sample_video_url = db.Column(db.String(500))
    youtube_video_id = db.Column(db.String(50), nullable = True)
    youtube_upload_status = db.Column(db.String(20), default = 'not_uploaded')
    youtube_upload_date = db.Column(db.DateTime, nullable = True)
    youtube_scheduled_time = db.Column(db.DateTime, nullable = True)
    youtube_metadata = db.Column(db.JSON, nullable = True)
    youtube_account_id = db.Column(db.Integer, nullable = True)
    uploaded_script_path = db.Column(db.String(500))
    video_settings = db.Column(db.JSON)
    subtitle_layers = db.Column(db.JSON)
    direct_progress = db.Column(db.JSON)
    simple_progress = db.Column(db.JSON)
    bgm_tracks = db.Column(db.JSON, nullable = True)
    mixed_audio_url = db.Column(db.String(500), nullable = True)
    sfx_tracks = db.Column(db.JSON, nullable = True)
    sfx_mixed_audio_url = db.Column(db.String(500), nullable = True)
    dependency_metadata = db.Column(db.JSON, nullable = True)
    llm_generation_metadata = db.Column(db.JSON, nullable = True)
    translated_scripts = db.Column(db.JSON, nullable = True)
    active_script_language = db.Column(db.String(20), default = '한국어')
    script_expansion_history = db.Column(db.JSON, nullable = True)
    editor_state = db.Column(db.JSON, nullable = True)
    shorts_data = db.Column(db.JSON, nullable = True)
    script_path = db.Column(db.String(500), nullable = True)
    script_version = db.Column(db.Integer, default = 1)
    use_speaker_separation = db.Column(db.Boolean, default = False)
    speaker_tts_data = db.Column(db.JSON, nullable = True)
    speaker_merged_audio_url = db.Column(db.String(500), nullable = True)
    speaker_tts_data_by_language = db.Column(db.JSON, nullable = True)
    tts_split_settings = db.Column(db.Text, nullable = True)
    thumbnail_candidates = db.Column(db.JSON, nullable = True)
    generated_images_history = db.Column(db.JSON, nullable = True)
    tts_audio_by_language = db.Column(db.JSON, nullable = True)
    subtitle_layers_by_language = db.Column(db.JSON, nullable = True)
    selected_tts_method_by_language = db.Column(db.JSON, nullable = True)
    created_at = db.Column(db.DateTime, default = datetime.utcnow)
    updated_at = db.Column(db.DateTime, default = datetime.utcnow, onupdate = datetime.utcnow)
    characters = db.relationship('Character', backref = 'project', lazy = True, cascade = 'all, delete-orphan')
    _ensure_video_settings_dict = (lambda value:
